In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        os.path.join(dirname, filename)

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
data = pd.read_csv(r'../input/kaggle-survey-2021/kaggle_survey_2021_responses.csv')

In [ ]:
def datacol(x):
    age= x.unique()
    age_grp = age[1:]
    tmp = list(x)
    cn = []
    for i in age_grp:
        cn.append(tmp.count(i))
    return age_grp, cn
age_grp, cn = datacol(data['Q1'])

# **Introduction**
 ![](https://analyticsinsight.b-cdn.net/wp-content/uploads/2020/03/Data-science.png)

In this growing world, Data Science and Machine Learning are become most popular in many countries. There is a lot of material available online as well as offline. There is no limit to it. Anyone can learn and make their career in this field and there is a lot of scope in this field. Due to covid-19, a lot of people have gained the interest in this field and they started doing courses online and developing their skills in data science field to fulfill the gap in Industry. In 2019, thousands of jobs are vaccant in data science field due to lack of skills in data science in India but after the covid-19 period, people got enough time to gain those skills and now jobs are less for the people.Even India has passed over the USA that's make India to be recognized in Data Science Field. By this Kaggle 2021 Survey, we will see how India is booming in Data Science and becoming most leading country than others. Let's see

In [ ]:
import matplotlib.pyplot as plt

import plotly.graph_objects as go
#from chart_studio.grid_objs import Column, Grid

from datetime import datetime as dt
import numpy as np
from IPython.display import IFrame

# **Different Age Group as Data Scientist**
There are 3 age group on which we have main focus as we can see in the below chart.
* **18-21 Age Group :** Mostly bachelor students come under this group. They are **18.87 %** in the world survey who are showing interest in Data Science and ML and wants to have career in this field.
* **22-24 Agr Group :** Mostly masters students and freshers comes under this group. They are **18.07 %** in the world survey who are pursuing Data Science and ML or freshers working in this field.
* **25-29 Age Group :** About **18.99 %** of people having experience of 2-4 years in this field which belongs to this group.

In [ ]:
with plt.xkcd():
    explode= [0,0,0,0.1,0.2,0,0,0,0,0,0]
    plt.figure(figsize = (8,8))
    plt.pie(cn, labels= age_grp,autopct = "%0.2f%%",explode = explode,shadow = True)
    plt.show()

# **Which countries are growing in Data Science and Machine Learning Industry ?**
* As data from Kaggle survey shows that India is most growing country in Data Science and Machine Learning Industry and it will continue in the future also. 
* If we compare India with USA, we can see India is **2.67 times of USA**. So,this shows that India is most leading country in Data Science and ML field as compared to other countries.
* In upcoming years, India will be largest mine of Data Scientists.

In [ ]:
#import chart_studio.plotly as py
import plotly.figure_factory as ff
with plt.xkcd():
    tmp = list(data['Q3'])
    da = ['India','United States of America','Japan','China','Others']
    cn = []
    di = {}
    for i in da:
        cn.append(tmp.count(i))
    #di[i]= tmp.count(i)
#usa = tmp.count()
    plt.figure(figsize = (11,8))
#plt.add_axes([0,0,1,1])
    plt.bar(da, cn , width = 0.4)
    plt.show()
    d = { 'country' : da, 'count': cn}

    c = pd.DataFrame(d)

In [ ]:
import plotly.graph_objects as go
with plt.xkcd():
    fig = go.Figure(data=[go.Table(header=dict(values=['Country', 'Frequency']),
                 cells=dict(values=[d['country'], d['count']]))
                     ])
    fig.show()

In [ ]:
country = data['Q3'].unique()
country = country[1:]
tm = list(data['Q3'])
cn = []
for i in country : 
    cn.append(tm.count(i))
di = {'country': country, 'count': cn }

In [ ]:
with plt.xkcd():
    import plotly.express as px
    df = pd.DataFrame(di)
#df = px.data.election()
#geojson = px.data.election_geojson()

    fig = px.choropleth(df, color="count",
                    locations="country", locationmode = 'country names', scope = 'world'
                   )
    fig.layout.template = None
    fig.update_geos(fitbounds="locations", visible=False)
    fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    fig.show()

In [ ]:
indian_data = data.loc[(data['Q3'] == 'India')]
usa_data = data.loc[(data['Q3']=='United States of America')]

# **Comparison of India and USA on Age Group factor**
* We can clearly see in India **18-21 age group** frequency is high but **in USA 18-21 and 60-69 age group** people frequency is high. 
* But in India, Data Science and Machine Learning is more popular in lower age group and go on decreasing towards higher age group. 
* In USA, both lower and high age group people numbers are almost **same**.

In [ ]:
with plt.xkcd(scale=1, length=100,randomness=2): 
    #india_data['Q1']
    x,y = datacol(indian_data['Q1'])
    xx,yy = datacol(usa_data['Q1'])
    x_axis = np.arange(len(x))
    plt.figure(figsize = (10,8))
    plt.bar(x_axis- 0.2, y,0.4, label= 'India')
    plt.bar(x_axis + 0.2, yy, 0.4, label = 'United States of America')
    plt.xticks(x_axis, x)
    plt.xlabel('Age Groups')
    plt.ylabel('No. of people')
    plt.legend()
    plt.show()
    fig = go.Figure(data=[go.Table(header=dict(values=['Age Group', 'India', 'USA']),
                 cells=dict(values=[x,y, yy]))])
    fig.show()

In [ ]:
with plt.xkcd(randomness=2): 
    x,y = datacol(data['Q4'])
    plt.figure(figsize = (8,8))
    explode = [0,0.2,0,0,0,0,0]
    plt.pie(y, labels= x,autopct = "%0.2f%%",explode = explode,shadow = True)
    plt.show()

# **Comparison of India and USA on Highest level of Formal Education factor**
In India, students who are pursing master degree are high in this field whereas in USA, Doctoral Degree Students are high in this field. This is main distinction we can draw from this chart. This conclude that new generation in India are more looking into new technologies.

In [ ]:
with plt.xkcd():
    x,y = datacol(indian_data['Q4'])
    xx,yy = datacol(usa_data['Q4'])
    x_axis = np.arange(len(x))
    plt.figure(figsize = (15,6))
    plt.bar(x_axis- 0.2, y,0.4, label= 'India')
    plt.bar(x_axis + 0.2, yy, 0.4, label = 'United States of America')
    plt.xticks(x_axis, x,rotation = 'vertical')
    plt.xlabel('Age Groups')
    plt.ylabel('No. of people')
    plt.legend()
    plt.show()
    fig = go.Figure(data=[go.Table(header=dict(values=['Higher Eductaion', 'India', 'USA']),
                 cells=dict(values=[x,y, yy]))])
    fig.show()

In [ ]:
with plt.xkcd():
    x,y = datacol(data['Q5'])
    plt.figure(figsize = (10,10))
#explode = [0.2,0,0,0,0,0,0]
    plt.pie(y, labels= x,autopct = "%0.2f%%",shadow = True)
    plt.show()

In [ ]:
python = 0
p1 = data['Q7_Part_1']
for i in p1 : 
    if i == 'Python':
        python = python + 1
r = 0
p2 = data['Q7_Part_2']
for i in p2:
    if i == 'R':
        r = r+ 1
        
s = 0
p3 = data['Q7_Part_3']
for i in p3:
    if i == 'SQL': 
        s = s + 1
#print(python,r,s)
lab = ['Python', 'R', 'SQL']
sizes = [python,r,s]

In [ ]:
#indian_data['Q26'].unique()

# **Comparison of India and USA on Notebooks Usage factor**
* About 53.64% of people in USA uses Jupyter Notebook whereas 44.06% of people uses in India.
* Indians(27.02%) uses Kaggle Notebooks as compared to USA(23.63%).
* About 28.92% of Indians uses Colab Notebook whereas 22.74% of USA uses it. This is because as colab linked to personal google drive where notebook can be stored easily and more accessible.

In [ ]:
arr = {}
total = 11722
li = list(indian_data['Q9_Part_11'])
arr['Jupyter Notebook'] = round((li.count(' Jupyter Notebook')/total) * 100, 2 )
arr['Kaggle Notebook'] = round((list(indian_data['Q10_Part_1']).count(' Kaggle Notebooks')/total) * 100,2)
arr['Colab Notebook'] = round((list(indian_data['Q10_Part_2']).count('Colab Notebooks')/total) * 100,2)

arr1 = {} 
tot = 2929 # total
li = list(usa_data['Q9_Part_11'])
arr1['Jupyter Notebook'] = round((li.count(' Jupyter Notebook')/tot) * 100,2)
arr1['Kaggle Notebook'] = round((list(usa_data['Q10_Part_1']).count(' Kaggle Notebooks')/tot) * 100,2)
arr1['Colab Notebook'] = round((list(usa_data['Q10_Part_2']).count('Colab Notebooks')/tot) * 100,2)

with plt.xkcd():
    x_axis = np.arange(len(arr.keys()))
    plt.figure(figsize = (15,10))
    y = list(arr.values())
    i = 1.0
    j = 2000
    y1 = list(arr1.values())
    plt.bar(x_axis- 0.2, arr.values(),0.4, label= 'India')
    plt.bar(x_axis + 0.2, arr1.values(), 0.4, label = 'United States of America')
    plt.xticks(x_axis, arr.keys())
    
    plt.xlabel('Salary Groups')
    plt.ylabel('No. of people')
    plt.legend()
    plt.show()
    fig = go.Figure(data=[go.Table(header=dict(values=['Notebooks', 'India', 'USA']),
                 cells=dict(values=[list(arr.keys()),list(arr.values()),list(arr1.values())]))])
    fig.show()

In [ ]:
from collections import OrderedDict
x,y= datacol(indian_data['Q26'])
x,y
dic1 = {}
for i in range(len(x)):
    
    if x[i] != np.nan:
        dic1[x[i]]= y[i]
nan = dic1[np.nan]
del dic1[np.nan]
#dic1, nan

In [ ]:
x1,y1 = datacol(usa_data['Q26'])
x1,y1
dic2 = {}
for i in range(len(x1)):
    dic2[x1[i]] = y1[i]
del dic2['$100-$999'] 
#dic2

In [ ]:
y = []
y1 = []
x = ['$0 ($USD)','$1-$99','$1000-$9,999','$10,000-$99,999','$100,000 or more ($USD)']
for i in x : 
    y.append(dic1[i])
    y1.append(dic2[i])

# **Unemployement factor is worst hitting the Indian Techies**
* This chart tell us that even though India youngester's having skills and knowledge but India's unemployement number is more than USA.
* Due to more supply than demand, companies are getting benefit and they are hiring people less than the average salary of Data Scientist in India
* This is main reason why Indian Techies are migrating to other countries.

In [ ]:
with plt.xkcd():
    x_axis = np.arange(len(x))
    plt.figure(figsize = (15,6))
    plt.bar(x_axis- 0.2, y,0.4, label= 'India')
    plt.bar(x_axis + 0.2, y1, 0.4, label = 'United States of America')
    plt.xticks(x_axis, x,rotation = 'vertical')
    plt.xlabel('Salary Groups')
    plt.ylabel('No. of people')
    plt.legend()
    plt.show()
#     fig = go.Figure(data=[go.Table(header=dict(values=['Salary', 'India', 'USA']),
#                  cells=dict(values=[x,y, y1]))])
#     fig.show()

In [ ]:
sal = indian_data['Q26']
stu = indian_data.loc[indian_data['Q5'] == 'Student']
st = len(stu)
st # Indian Students who are earning $0 
nan # Indians who not filled their earnings in survey

In [ ]:
def earn(dta, st,st1):
    sci = dta.loc[dta['Q5'] == st1]
    ear = len(sci.loc[sci['Q26'] == st])
    return ear
#earn(indian_data, '$0 ($USD)','Data Scientist')

In [ ]:
#earn(usa_data, '$0 ($USD)', 'Data Scientist')
# sci1 = usa_data.loc[usa_data['Q5'] == 'Data Scientist']
# ear1 = len(sci1.loc[sci1['Q26'] == '$0 ($USD)'])
# ear

In [ ]:
ds = []
ds1 = []
X = []
for i in x : 
    ds.append(earn(indian_data, i,'Data Scientist'))
    ds1.append(earn(usa_data,i,'Data Scientist'))
    X.append(i)
#ds,ds1,X
x = ['$0 ($USD)','NaN','$1-$99','$1000-$9,999','$10,000-$99,999','$100,000 or more ($USD)']

# **Comparison of India and USA on Earnings of Data Scientist factor**
* In both the countries, we can find a lot of Data Scientist whose earning is **$0** which is the main concern for people. There can be many reasons for it like there knowledge or skills may not be upto companies requirement or people are not able to find the jobs in their field or there can be others cases too. This is the major concern for Industries as they are not able to get good talent people to work. 
* If we see data of India's Data Scientists, **frequency is decreasing as earning goes high with negative slope**.
* But in USA, f**requency with earning is increasing with positive slope**.

In [ ]:
with plt.xkcd():
    # Salary of DataScientist in India Vs USA 
    plt.figure(figsize= (12,10))
    x_axis = np.arange(len(X))
    plt.xticks(x_axis,X)
    plt.plot(ds, linewidth = 4)
    plt.plot(ds1, linewidth = 4)
    plt.show()

# **Summary**
* From the **Kaggle Survey 2021**, we observed that there is less oportunity for data science beginners in India as numbers increases expontentialy but demand remains constant due to many factors like covid-19.  
* Average earning also affected in India if we compared with USA. As supplier is more than demand so companies have decreased average earning in this field. For Example a lot of internships in this field are without pay and companies says **You should focus on your experience** which is very irrelevent for students. 
* I think other countries where demand is not able to fulfill in this field have great opportunity that they can start hiring the good talents from India's Data Science Mine.

### IF YOU LIKE THIS NOTEBOOK, PLEASE **UPVOTE** IT THAT WILL ENCOURAGE ME MORE :)