**Just Simple DATA Analysis**

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 
#LEAVE IT ALONE
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['X_train.csv', 'sample_submission.csv', 'X_test.csv', 'y_train.csv']

****IMPORT tHE FILES. I KNOW Without bold YOu won't REad ME****

In [4]:
df1=pd.read_csv('../input/X_train.csv')  #This happens when comptetion maker try to be smart give x_train &Y_train to help
df2=pd.read_csv('../input/y_train.csv')  #but it ends up confusing you. 
test=pd.read_csv('../input/X_test.csv')
sample=pd.read_csv('../input/sample_submission.csv')

***Lets Check that shape and size!!!!***

In [6]:
print((df1.shape),(df2.shape),(test.shape),(sample.shape))

(487680, 13) (3810, 3) (488448, 13) (3816, 2)

****Something is bad !! Why are X_train and Y_train not simliar ?check data and columns quick!****

In [7]:
df1.head()

  row_id          ...            linear_acceleration_Z
0    0_0          ...                          -9.7532
1    0_1          ...                          -9.4128
2    0_2          ...                          -8.7267
3    0_3          ...                         -10.0960
4    0_4          ...                         -10.4410

[5 rows x 13 columns]

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 487680 entries, 0 to 487679
Data columns (total 13 columns):
row_id                   487680 non-null object
series_id                487680 non-null int64
measurement_number       487680 non-null int64
orientation_X            487680 non-null float64
orientation_Y            487680 non-null float64
orientation_Z            487680 non-null float64
orientation_W            487680 non-null float64
angular_velocity_X       487680 non-null float64
angular_velocity_Y       487680 non-null float64
angular_velocity_Z       487680 non-null float64
linear_acceleration_X    487680 non-null float64
linear_acceleration_Y    487680 non-null float64
linear_acceleration_Z    487680 non-null float64
dtypes: float64(10), int64(2), object(1)
memory usage: 48.4+ MB

In [11]:
df2.head()

   series_id  group_id        surface
0          0        13  fine_concrete
1          1        31       concrete
2          2        20       concrete
3          3        31       concrete
4          4        22     soft_tiles

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3810 entries, 0 to 3809
Data columns (total 3 columns):
series_id    3810 non-null int64
group_id     3810 non-null int64
surface      3810 non-null object
dtypes: int64(2), object(1)
memory usage: 89.4+ KB

In [13]:
sample.head()

   series_id   surface
0          0  concrete
1          1  concrete
2          2  concrete
3          3  concrete
4          4  concrete

In [14]:
test.head()

  row_id          ...            linear_acceleration_Z
0    0_0          ...                          -5.5439
1    0_1          ...                          -8.0273
2    0_2          ...                         -11.2990
3    0_3          ...                         -12.2270
4    0_4          ...                         -10.4100

[5 rows x 13 columns]

**OK !!! SO X_train have data Y_train have index and target. Sample will be used for submission**

**LEts SEE Unique types of surfaces we have???**

In [15]:
df2.surface.nunique()

9

**TO BE COntinued......**