# EDA

In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot') #Importing libraries

In [ ]:
df = pd.read_csv('../input/titanic/train.csv') #Read file
df.head()

In [ ]:
df.drop(['PassengerId','Ticket','Name'],inplace=True,axis=1)  #Droping few features

In [ ]:
table = pd.pivot_table(data=df,index=['Sex']) # ‘Sex’ column as the index,single index
table

In [ ]:
table.plot(kind='bar');

In [ ]:
table = pd.pivot_table(df,index=['Sex','Pclass']) #multiple indexes
table

In [ ]:
table = pd.pivot_table(df,index=['Sex','Pclass'],aggfunc={'Age':np.mean,'Survived':np.sum}) #aggregate functions
table

In [ ]:
table = pd.pivot_table(df,index=['Sex','Pclass'],values=['Survived'], aggfunc=np.mean)
table

In [ ]:
table.plot(kind='bar');

#  Relationship between features with columns parameter

In [ ]:
table = pd.pivot_table(df,index=['Sex'],columns=['Pclass'],values=['Survived'],aggfunc=np.sum)
table

In [ ]:
table.plot(kind='bar')

In [ ]:
table = pd.pivot_table(df,index=['Sex','Survived','Pclass'],columns=['Embarked'],values=['Age'],aggfunc=np.mean) #nullvalues
table

In [ ]:
table = pd.pivot_table(df,index=['Sex','Survived','Pclass'],columns=['Embarked'],values=['Age'],aggfunc=np.mean,fill_value=np.mean(df['Age'])) #replacing the NaN values with the mean value from the ‘Age’ column
table