In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

from plotly.subplots import make_subplots

In [ ]:
df=pd.read_csv('../input/kaggle-survey-2020/kaggle_survey_2020_responses.csv')
df_questions=df.iloc[0,:]
df_act=df.drop([0])

In [ ]:
df_act.head()

In [ ]:
'''Age Distribution
Age and Gender
Country Of residence
Education Background
Current Role title
Experience Years
Programming Languages
Programming Languages Based on Role title and Education Background
Programming Languages used for each Age range
Recommended First Programming language
Favorite Integrated development environments
Most Hosted Notebooks
Most used visualization libraries
Currently Yearly Compensation
Duration of using Machine learning methods
Machine Learning Frameworks used
Machine learning Algorithms used'''

In [ ]:
plt.xkcd(scale=0.8,randomness=0.5)
#AGE Distribution

In [ ]:
plt.xkcd()
plt.style.use('seaborn')

color_pal=['cyan', 'blue', 'red', 'cyan', 'cyan', 'cyan', 'cyan', 'cyan', 'cyan', 'cyan']
#AGE Distribution
order=df_act['Q1'].value_counts().sort_index()

fig,ax=plt.subplots(1,1,figsize=(20,7))
ax=sns.countplot(df_act['Q1'],order=order.index,palette=color_pal)
plt.xticks(rotation=90,fontsize=14)
plt.xlabel('Age',fontsize=14)
plt.ylabel('Count',fontsize=14)



for bar in ax.patches:
     ax.annotate(format(bar.get_height(), '.2f'),  
                   (bar.get_x() + bar.get_width() / 2,  
                    bar.get_height()), ha='center', va='center', 
                   size=15, xytext=(0, 10 ), 
                   textcoords='offset points') 
ax.text(6, 3000, 'Most of DS practisioner are below 30', style='italic',fontsize=20)
plt.show()

In [ ]:
#Age and Gender

In [ ]:
df_act["Gender"]=df_act['Q2'].apply(lambda x:'other' if x not in ['Man','Woman'] else x)

In [ ]:
a=df_act.groupby(['Q1','Gender']).count().reset_index()

fig=px.bar(a,x='Q1',y='Q2',color='Gender',barmode='group',text='Q2',labels={
                     "Q1": "AGE",
                     "Q2": "Count"})
fig.update_traces(textposition='outside')
fig.update_layout(title_text='Gender based on Age',)

In [ ]:
#COuntry of residence
a=df_act['Q3'].value_counts().sort_values(ascending=False)[:10]

In [ ]:
total=df_act['Q3'].value_counts().sum()
perc=[]
for i in df_act['Q3'].value_counts():
    perc.append(round((i/total)*100,2))
     

ax=a.plot(kind='bar')
for bar in ax.patches:
     ax.annotate(f'{round(bar.get_height()/total*100,2)}'+'%',  
                   (bar.get_x() + bar.get_width() / 2,  
                    bar.get_height()), ha='center', va='center', 
                   size=15, xytext=(0, 10 ), 
                   textcoords='offset points')
        
ax.text(4, 4000, 'Total_Practisioner=20036\n About 29% are from India', style='italic',fontsize=15,
       bbox={'facecolor': 'red', 'alpha': 0.5, 'pad': 10})
plt.show()

In [ ]:
#Lets compare Indian's survey with rest of world

In [ ]:
df_ind=df_act[df_act['Q3']=='India']
df_rest=df_act[df_act['Q3']!='India']

In [ ]:
#lets go with first question thats more common , whats should be the age 
fig,(ax1,ax2)=plt.subplots(1,2,figsize=(20,7))

#india
color_ind=['blue', 'cyan', 'cyan', 'cyan', 'cyan', 'cyan', 'cyan', 'cyan', 'cyan', 'cyan']
order=df_ind['Q1'].value_counts().sort_index()
a=sns.countplot(df_ind['Q1'],order=order.index,palette=color_ind,ax=ax1)
#ax1.set_xticks(rotation=90,fontsize=14)
ax1.set_xlabel('Age',fontsize=14)
ax1.set_ylabel('Count',fontsize=14)
for bar in a.patches:
     a.annotate(format(bar.get_height(), '.2f'),  
                   (bar.get_x() + bar.get_width() / 2,  
                    bar.get_height()), ha='center', va='center', 
                   size=15, xytext=(0, 10 ), 
                   textcoords='offset points') 
a.text(6, 1500, 'Most of DS practisioner in india\nare between 18-21', style='italic',fontsize=15)


#world
color_rest=['cyan', 'blue', 'blue', 'blue', 'cyan', 'cyan', 'cyan', 'cyan', 'cyan', 'cyan']
order=df_rest['Q1'].value_counts().sort_index()
b=sns.countplot(df_rest['Q1'],order=order.index,palette=color_rest,ax=ax2)
#ax1.set_xticks(rotation=90,fontsize=14)
ax1.set_xlabel('Age',fontsize=14)
ax1.set_ylabel('Count',fontsize=14)
for bar in b.patches:
     b.annotate(format(bar.get_height(), '.1f'),  
                   (bar.get_x() + bar.get_width() / 2,  
                    bar.get_height()), ha='center', va='center', 
                   size=15, xytext=(0, 10 ), 
                   textcoords='offset points') 
b.text(6, 2000, 'Most of DS practisioner generally \n are below 25-29', style='italic',fontsize=15)

In [ ]:

role=df_ind['Q5'].value_counts().sort_values(ascending=False).index
cnt=df_ind['Q5'].value_counts().sort_values(ascending=False).values
role_rest=df_rest['Q5'].value_counts().sort_values(ascending=False).index
cnt_rest=df_rest['Q5'].value_counts().sort_values(ascending=False).values

In [ ]:


color_seq=['ffbf69','f15bb5','dee2e6','d68c45','adb5bd','6c757d','495057','343a40','212529','98c1d9','bcb8b1','c5dedd','f5cac3']



fig = make_subplots(rows=1, cols=2, specs=[[{'type':'domain'}, {'type':'domain'}]],subplot_titles=['India_JOB_Titles','World_JOB_Title'])

fig.add_traces(go.Pie(labels=role,values=cnt),1,1)
fig.add_traces(go.Pie(labels=role_rest,values=cnt_rest),1,2)
fig.update_traces( textfont_size=10,
                  marker=dict(colors=color_seq,line=dict(color='#000000', width=2)))



#Most of learner are students in india and rest of world both student and software engineers

In [ ]:
#What shoudl be the Education level

deg=df_ind['Q4'].value_counts().index
values=df_ind['Q4'].value_counts().values

deg_rst=df_rest['Q4'].value_counts().index
val_rst=df_rest['Q4'].value_counts().values

In [ ]:
fig=make_subplots(1,2,specs=[[{'type':'domain'}, {'type':'domain'}]],subplot_titles=['India','World'])
fig.add_traces(go.Pie(labels=deg,values=values),1,1)
fig.add_traces(go.Pie(labels=deg_rst,values=val_rst),1,2)
fig.update_traces(marker=dict(line=dict(color='white', width=2)))
fig.update_layout(template= "plotly_dark",title='Education Levels')

#52.4% are bachelor degree Holder in India, whereas 43.4% are Masters

In [ ]:
#which language is most used
df_ind['Q7_Part_1'].value_counts()

In [ ]:
languages=[]
counts=[]
counts_rest=[]
columns=['Q7_Part_1', 'Q7_Part_2', 'Q7_Part_3', 'Q7_Part_4', 'Q7_Part_5','Q7_Part_6', 'Q7_Part_7', 'Q7_Part_8', 'Q7_Part_9', 'Q7_Part_10',
       'Q7_Part_11', 'Q7_Part_12', 'Q7_OTHER']
for i in columns:
    languages.append(df_ind[i].value_counts().index[0])
    counts.append(df_ind[i].value_counts().values[0])
    counts_rest.append(df_rest[i].value_counts().values[0])

In [ ]:
fig = go.Figure()
fig.add_trace(go.Bar(x=languages, y=counts,marker_color='red', name='India',
                     marker = dict(line=dict(color='white',width=1.5)),
                     text=counts ,textposition='outside'))
fig.add_trace(go.Bar(x=languages, y=[-i for i in counts_rest],
                
                marker_color='lightslategrey',
                name='World',text=counts_rest ,textposition='outside'
                ))
fig.update_layout(title='Most Common used Language',yaxis = dict(title ='Count'))
fig.update_yaxes(showticklabels=False)


#Python and SQL are most used

In [ ]:
#Most Recomended Language

In [ ]:
df_act['Q8'].value_counts().plot(kind='barh')
plt.title('Recomended Language')
plt.text(6000, 8, 'Python Rules', style='italic',fontsize=15,
       bbox={'facecolor': 'red', 'alpha': 0.5, 'pad': 10})
#python is most recomended language followed by R and then SQL

In [ ]:
#plt.style.use('fivethirtyeight')
plt.xkcd(False)

In [ ]:
ide_ind=[]
ide_val=[]
for i in df_ind.iloc[:,21:33].columns:
    ide_ind.append(df_ind[i].value_counts().index[0])
    ide_val.append(df_ind[i].value_counts().values[0])

In [ ]:
plt.rc_context({'xtick.color':'red', 'ytick.color':'green'})
a=sns.barplot(y=ide_ind,x=ide_val)
a.set_title("MOST USED IDE'S",{'color':'black'})
a.text(2000,5,'Jupyter is most used ide\n,VScode,pycharm  commonly used',{'color': 'black'})

In [ ]:
df_ind.iloc[:,133:140]
#34:47,48:52,52,53:65,65,66:82,82:94,107,108,109,110:118,119,120:132,133,140

def val_cnt(a,b): 

    ind=[]
    val=[]
    for i in df_ind.iloc[:,a:b].columns:
        ind.append(df_ind[i].value_counts().index[0])
        val.append(df_ind[i].value_counts().values[0])
        px.pie(values=val, labels=ind)
plt.show()
val_cnt(34,47)

In [ ]:
a = df_ind[[i for i in df_ind.columns if 'Q10' in i]]
c = pd.Series(dtype='int')
for i in a.columns:
      c[a[i].value_counts().index[0]]=a[i].count()
        
c=c.sort_values(ascending=False)  
plot=sns.barplot(c.values,c.index)
plt.title('Which of the following hosted notebook products do you use on a regular basis?',color='black')
total=c.sum()
for a in plot.patches:
     plot.annotate(f'{round(a.get_width()/total*100,2)}'+'%'  ,
                   (a.get_width()+40,a.get_y()),
                   size=10, xytext=(0, -10), 
                   textcoords='offset points',color='black') 
plot.text(1500,7,'Almost 50 % use Kaggle \nand Colab Notebooks',style='italic',fontsize=13,color='black')

In [ ]:
plt.style.use('fivethirtyeight')

In [ ]:
q_14 = df_ind[[i for i in df_ind.columns if 'Q14' in i]]
c = pd.Series(dtype='int')
for i in q_14.columns:
      c[q_14[i].value_counts().index[0]]=q_14[i].count()


q_29 = df_ind[[i for i in df_ind.columns if 'Q29' in i]]
c_1 = pd.Series(dtype='int')
for i in q_29.columns:
      c_1[q_29[i].value_counts().index[0]]=q_29[i].count()

fig=make_subplots(1,2,specs=[[{'type':'domain'}, {'type':'domain'}]],subplot_titles=['Viz Library','SQL'])
go_1=px.pie(names=c.index,values=c.values,title='Which of the data viz library do you use on a regular basis')
go_2=px.pie(names=c_1.index,values=c_1.values,title='Which of the data viz library do you use on a regular basis')
fig.add_traces(go_1['data'][0],1,1)
fig.add_traces(go_2['data'][0],1,2)
fig.update_traces( textinfo='percent')

In [ ]:
#Matplotlib, seaborn , plotly are highly used library for visualization. FOr Database,MYSQL,Mongodb are widely used

In [ ]:
a=sns.color_palette("RdBu", 16)

In [ ]:
import squarify as sq
framework=df_ind[[i for i in df_ind.columns if 'Q16' in i]]
frame = pd.Series(dtype='int')
for i in framework.columns:
      frame[framework[i].value_counts().index[0]]=framework[i].count()
        
frame=frame.sort_values(ascending=False)        




plt.figure(figsize=(14,6))
sq.plot(label=frame.index,sizes=frame.values,alpha=0.8,color=a)
plt.title('machine learning frameworks ')



#Sckit_learn,Tensorflow,Keras,xgboost are mostly used library

In [ ]:
algo=df_ind[[i for i in df_ind.columns if 'Q17' in i]]
a = pd.Series(dtype='int')
for i in algo.columns:
      a[algo[i].value_counts().index[0]]=algo[i].count()
        
a=a.sort_values(ascending=False)        

plt.figure(figsize=(14,6))
#colors = [plt.cm.Blues(norm(value)) for value in frame.values]
sns.barplot(x=a.values,y=a.index)
plt.title('machine learning Algorithms ',color='black')

In [ ]:
a=['#ffcccc','#ffb3b3','#ff9999','#ff8080','#ff6666','#ff4d4d','#ff3333','#ff1a1a','#ff0000','#e60000','#cc0000',
   '#b30000','#990000','#660000','#4d0000','#330000']

In [ ]:
df_ind.groupby(['Q24','Q5'])['Q5'].count().unstack().head()

In [ ]:
df_ind['Q24'].unique()

less=['$0-999']        
ten=['1,000-1,999','2,000-2,999','3,000-3,999','4,000-4,999','5,000-7,499','7,500-9,999']    
tsnd=['10,000-14,999','20,000-24,999','25,000-29,999','40,000-49,999','50,000-59,999','60,000-69,999',
      '70,000-79,999','90,000-99,999']
fty=['100,000-124,999','125,000-149,999','150,000-199,999','200,000-249,999','250,000-299,999','300,000-500,000']
more=['> $500,000']

In [ ]:
def sal(x):
    if x in less:
        return '<1000'
    elif x in ten:
        return  '1000-9999'
    elif x in tsnd:
        return '1000-99999'
    elif x in fty:
        return '100000-500000'
    elif x in more:
        return '<500000'
    else:
        return np.nan
df_ind['salary']=df_ind['Q24'].apply(lambda x:sal(x))    
df_ind['salary'].value_counts()

In [ ]:
plt.figure(figsize=(20,10))
sns.heatmap(df_ind.groupby(['Q5','salary'])['Q5'].count().unstack(),annot=True,cmap="YlGnBu")
plt.title('Salary range for diff title',fontdict={'fontsize':20},color='black')

In [ ]:
order=['$0-999', '1,000-1,999', '2,000-2,999', '3,000-3,999', '4,000-4,999', '5,000-7,499', '7,500-9,999',
        '10,000-14,999','15,000-19,999', '20,000-24,999', '25,000-29,999', '30,000-39,999', '40,000-49,999', 
       '50,000-59,999', '60,000-69,999', '70,000-79,999', '80,000-89,999', '90,000-99,999','100,000-124,999', 
       '125,000-149,999',  '150,000-199,999', '200,000-249,999',  '250,000-299,999', '300,000-500,000', '> $500,000']
women=df_ind[df_ind['Q2']=='Woman']['Q24'].value_counts()
man = df_ind[df_ind['Q2']=='Man']['Q24'].value_counts()[order]

In [ ]:
for i in man.index:
    if i not in women.index:
        women[i]=0
        
women=women[order]

In [ ]:
#lets compare how salary varies between gender and title
fig = go.Figure()
fig.add_trace(go.Bar(x=man.index, y=man.values,marker_color='red', name='Men',
                     marker = dict(line=dict(color='white',width=1.5)),
                     text=man.values ,textposition='outside'))
fig.add_trace(go.Bar(x=women.index, y=[-i for i in women.values],
                
                marker_color='lightslategrey',
                name='Women',text=women.values ,textposition='outside'
                ))
fig.update_layout(title='Men,Women Salary Range in India',yaxis = dict(title ='Count'))
fig.update_yaxes(showticklabels=False)
fig.update_xaxes(tickangle=90)

In [ ]:
courses=df_ind[[i for i in df_ind.columns if 'Q37' in i]]
c= pd.Series(dtype='int')
for i in courses.columns:
      c[courses[i].value_counts().index[0]]=courses[i].count()

In [ ]:
#which platforms have you begun or completed data science courses?

fig=px.pie(names=c.index,values=c.values)
fig.update_traces(textposition='inside', textinfo='percent+label')


# Coursera ,Udemy and Kaggle are ,ost preffered places to study

In [ ]:
media=df_ind[[i for i in df_ind.columns if 'Q39' in i]]
m = pd.Series(dtype='int')

In [ ]:
plt.style.use('fivethirtyeight')
ind=[]
val=[]
for i in media.columns:
    ind.append(df_ind[i].value_counts().index[0])
    val.append(df_ind[i].value_counts().values[0])
    
sns.barplot(x=val,y=ind)   
plt.title('Popular Media for DS ',color='black')


#Kaggle,Youtube,Blogs are most preffered ones

In [ ]:
#Type of work based on each job

In [ ]:
def col(q):
    col_lst = [name for name in df_ind.columns if q in name]
    colmn = df_ind[col_lst]
    return colmn

q23_5=pd.concat([col('Q23'),col('Q5')],axis=1)
q23_5=q23_5.melt(id_vars = 'Q5', var_name = 'work', value_name = 'response')
q23_5 = pd.DataFrame(q23_5.groupby('Q5')['response'].value_counts())
q23_5.columns= ['n_responses']
q23_5.reset_index(inplace=True)

In [ ]:
total = pd.DataFrame(df_ind['Q5'].value_counts()).reset_index()
total.columns = ['Q5', 'count']
merge=pd.merge(q23_5,total,on='Q5',how='left')
merge['perc']=round((merge['n_responses']/merge['count'])*100,2)
pvt=pd.pivot_table(merge,index='response',values='perc',columns='Q5')
pvt.index=['Analyze and understand data','Build or run  ML service that improves my product','Data infrastructure ','prototypes','research','Ml improvement and experiment','None','other']

#plt.style.use('fivethirtyeight')
plt.figure(figsize=(20,10))
sns.heatmap(pvt,annot=True,cmap='viridis')

plt.xlabel("Job title",fontdict = {'fontsize':20})
plt.ylabel("Work activities",fontdict={'fontsize':15})
plt.title("Q23: type of work based on Job title ", fontdict = {'fontsize':20}, pad=24);
plt.xticks(fontsize=14, rotation=90)
plt.yticks(fontsize=14)