**I used papago for translation :)**

# **읽기 전 참고사항**

**이 코드는 https://www.kaggle.com/songwonmin/swm-titanic 의 pandas, numpy 표현들에 대해 설명하는 코드입니다.**

**각 method별로 예시 코드와 기능, 실제 코드에서의 쓰임새를 설명하였습니다.**

**실제로 코드에서 column명, 옵션 등을 변경해 실행해보며 공부하는 것이 많은 도움이 될 것이라 생각합니다.**

**pandas의 내용이 굉장히 방대하기 때문에 rename등 여기에 포함되지 않은 내용은 다음 노트북에 차차 포함 될 예정입니다.**

---
**세로가 열, column이고**

**가로가 행, row입니다.**

**DataFrame은 pandas에서 제공하는 자료형으로 처음 본다면 표 형식 2차원 배열이라고 생각하시면 편합니다.**

**This code describes the panda, numpy representations at https://www.kaggle.com/songwonmin/swm-titanic.**

**Example code, method, and use in code were explained for each method.**

**I think it will be very helpful to study by changing the column name and option and run the code.**

**Since the contents of Pandas are very vast, contents that are not included here, such as renames, will be gradually included in the next laptop.**

---
**DataFrame is a data type provided by Pandas, and it is convenient to think of it as a two-dimensional table arrangement when viewed for the first time.**

# **pandas**

**pandas는 R의 DataFrame 형식을 참고하여 제작한 데이터 분석을 돕는 라이브러리입니다.**

**표 형식 데이터를 다룰 때 여러 method를 활용하여 통계값을 확인하여 도움을 받을 수 있습니다.**

**pandas is a library that helps analyze data produced by referring to R's DataFrame format.**

**When dealing with table format data, you can use several methods to check statistical values for help.**

# --import

In [ ]:
import pandas as pd

---
```python 
import pandas
import pandas as pd
import pandas as panda
```

**python에서 pandas 라이브러리를 사용하기 위해 import 하는 과정입니다.**

**as pd를 이용한다면 이후 method를 사용할 때 pd로 축약하여 사용할 수 있습니다.**

**마찬가지로 as panda로 사용한다면 이후 panda로 사용할 수 있습니다.**

**This is the process of import to use the panda library in Python.**

**If you use as pd, you can abbreviate it to pd when using the method later.**

**Likewise, if you use it as a panda, you can use it as a panda afterwards.**

---

# --read_csv()

In [ ]:
train = pd.read_csv("../input/titanic/train.csv")
test = pd.read_csv("../input/titanic/test.csv")
sample_submission = pd.read_csv("../input/titanic/gender_submission.csv")

---
```python
train = pd.read_csv("../input/titanic/train.csv")
test = pd.read_csv("../input/titanic/test.csv")
sample_submission = pd.read_csv("../input/titanic/gender_submission.csv")
```

**pandas의 read_csv 기능을 사용한다면 csv 파일을 읽어 pandas의 DataFrame 자료형으로 변수에 저장할 수 있습니다.**

**사용방법은 pd.read_csv 이후 소괄호에 파일의 경로를 입력해주면 됩니다.**

**이 코드에서는 input 폴더의 train.csv, test.csv, gender_submission.csv를 불러오기 위해 경로를 지정했습니다.**

**파일이 많은 경우에는 공통 경로를 지정하는 경우도 있습니다**

**If you use Pandas' read_csv method, you can read the csv file and store it in variables as Pandas' DataFrame data type.**

**To use, enter the path of the file in the parenthesis after pd.read_csv.**

**This code has specified a path to fetch train.csv, test.csv, and gender_submission.csv in the input folder.**

**If you have a lot of files, you may designate a common path.**

---

# --head()

In [ ]:
train.head()

---
```python
train.head()
train.head(10)
```
**head 기능을 사용하면 DataFrame의 데이터 중 위에서 n개의 자료를 리턴받습니다. (기본은 5개로 지정되어 있습니다.)**

**데이터를 살펴보면 이름, 성별, 나이 등의 데이터를 볼 수 있습니다. (승객번호 1번은 22살이셨네요.)**

**head method allows n data to be returned from above among the data in DataFrame. (Basically, there are five.)**

**If you look at the data, you can see data such as name, gender, and age. (The passenger number 1 was 22 years old.))**

---

# --shape

In [ ]:
train.shape

---
```python
train.shape
```
**shape기능을 사용하면 데이터의 모양, 즉 행과 열의 형태를 알 수 있습니다.**

**이 데이터는 12개의 column과 891개의 행으로 이루어져 있는 것을 알 수 있습니다.**

**shape metohd allows you to know the shape of the data, that is, the shape of the rows and columns.**

**It can be seen that this data consists of 12 columns and 891 rows.**

---

# --info()

In [ ]:
train.info()

---
```python
train.info()
test.info()
```
**info 기능은 이름에서도 알 수 있듯이 데이터의 정보를 보여줍니다.**

**데이터를 구성하는 column명, column의 자료형, null값의 수 등을 알려줍니다.**

**자료를 보면 나이, 선실 등에 결측값이 있는 것을 볼 수 있습니다.**

**Info mothod shows data information, as the name suggests.**

**It tells you the column name that makes up the data, the data type of the column, and the number of null values.**

**If you look at the data, you can see that there are missing values in age, cabin, etc.**

---

# --describe()

In [ ]:
train.describe()

---
```python
train.describe()
test.describe()
```

**describe는 말 그대로 데이터를 설명합니다.**

**데이터의 결측값 수, 평균, 표준편차, 최솟값, 최댓값 등을 알려줍니다.**

**생존여부는 0과 1로 이루어졌기 때문에 최솟값이 0이고 최댓값이 1이네요**

**describe literally describes the data.**

**It tells you the number of missing values, mean, standard deviation, minimum value, maximum value, etc. of the data.**

**Survival consists of 0 and 1, so the minimum value is 0 and the maximum value is 1.**

---

# --df["column"]

In [ ]:
train[["Name","Pclass"]]

---
```python
train["Name"]
train.Name
train[["Name","Pclass"]]
```
**DataFrame에 대괄호에 column명을 넣거나 .뒤에 column명을 입력하면 그 column의 데이터를 리턴받습니다.**

**특정 column들을 이용할 때는 column명 들의 list를 사용하여 그 columns의 데이터를 리턴받을 수 있습니다.**

**이처럼 이름과 선실의 등급을 알 수 있습니다.**

**If you put the column name in brackets in the Data Frame or enter the column name after, the column data will be returned.**

**When using a specific column, you can use the list of column names to get the data return from that column.**

**Like this, you can know the name and cabin rating.**

---

# --iloc[]

In [ ]:
train.iloc[:10]

---
```python
train.iloc[:10]
```
**iloc는 리스트 슬라이싱처럼 숫자를 이용하여 슬라이싱을 진행할 수 있습니다.**

**이 코드에서는 처음부터 10번째까지의 데이터를 리턴하였습니다.**

**iloc can proceed with slicing using numbers like list slicing.**

**This code returned data from the beginning to the 10th.**

---

# --loc[]

In [ ]:
df = train.set_index("Name")

In [ ]:
df.loc[:"Allen, Mr. William Henry"]

---
```python
df.loc[:"aaa"]
```
**loc는 index의 값을 이용하여 데이터를 슬라이싱할 수 있습니다.**

**이 코드에서는 처음부터 Allen, Mr. William Henry씨 까지의 데이터를 리턴하였습니다.**

**loc can slice data using the value of index.**

**This code returned data from the beginning to Allen, Mr. William Henry.**

---

# --set_index()

In [ ]:
train = train.set_index("PassengerId")
test = test.set_index("PassengerId")

---
```python
train = train.set_index("PassengerId")
```
**set_index는 특정 column을 index로 지정할 수 있습니다.**

**지정된 index는 자료의 위치를 찾을 때 사용되곤 합니다.**

**이 코드는 승객번호를 index로 설정하였습니다.** (이처럼 겹치는 값이 없는 column을 index로 설정하면 자료를 찾을 때 원하는 자료를 찾기가 쉽습니다.)

**set_index can specify a specific column as index.**

**Designated indexes are often used to locate data.**

**This code has set the passenger number to index.** (If you set a column without such overlapping values to index, it is easy to find the data you want when you find the data.)

---

# --str

In [ ]:
train["Name_2"] = train["Name"].str.split(",").str[1].str.split(".").str[0].str[1:]
test["Name_2"] = test["Name"].str.split(",").str[1].str.split(".").str[0].str[1:]

In [ ]:
train["Name"].str.split(",")

---
```python
train["Name"].str.split(",")
```

**DataFrame의 문자열을 한번에 나누거나 처리하려면 .str을 붙여주어야 합니다.**

**이 코드에서는 이름에서 경칭을 추출하기 위하여 사용되었습니다.** (문자열을 쉼표와 마침표를 기준으로 나누어서 추출했습니다.)

**To divide or process the string of DataFrame at once.You have to add str.**

**This code was used to extract honorifics from names.** (We extracted the string by dividing it by a comma and a period.)

---

# --unique(), nunique()

In [ ]:
train["Name_2"].unique()

In [ ]:
train["Name_2"].nunique()

---
```python
train["Name_2"].unique()
train["Name_2"].nunique()
```

**unique를 사용하면 데이터의 고유값들을 ndarray 형태로 리턴해줍니다.**

**그리고 nunique는 고유값들의 수를 리턴하는 것으로 unique를 적용한 다음 len()을 적용한 결과와 같습니다.**

**이 코드에서는 경칭의 고유값을 파악하기 위하여 사용되었습니다.**

**unique returns the eigenvalues of the data in the form of an ndarray.**

**And null is the same as the result of returning the number of eigenvalues, applying unique, and applying len().**

**This code was used to determine the eigenvalue of the honorifics.**

---

# --concat()

In [ ]:
all_df = pd.concat([train,test],axis=0)

---
```python
all_df = pd.concat([train,test],axis=0)
```

**concat은 두개 이상의 DataFrame을 결합할 수 있습니다 axis가 1이면 열을 기준으로하여 가로로 결합하고 axis가 0이라면 세로로 결합합니다.**

**이 코드에서는 column별로 전처리를 한번에 하려는 목적으로 train과 test DataFrame을 결합하였습니다.**

**concat can combine two or more DataFrames. If Axis is 1, combine horizontally based on the column, and if Axis is 0, combine vertically.**

**In this code, train and test Data Frame are combined for the purpose of preprocessing for each column at once.**

---

# --value_counts()

In [ ]:
all_df["Name_2"].value_counts()

In [ ]:
dict(all_df["Name_2"].value_counts())

---
```python
all_df["Name_2"].value_counts()
```
**각 고유값별로 전체 데이터에서 고유값의 수를 리턴합니다**

**dict를 이용하여 고유값을 key로, 고유값의 수를 value로 지정할 수 있습니다.**

**데이터를 보면 Mr을 사용하는 사람이 757명이 있었다는 것을 알 수 있습니다.**

**Returns the number of eigenvalues from the entire data for each eigenvalue.**

**dict allows you to specify an eigenvalue as a key and the number of eigenvalues as a value.**

**The data shows that there were 757 people using mr.**

---

# --map()

In [ ]:
train["Name_2"].map(dict(all_df["Name_2"].value_counts()))

---
```python
train["Name_2"].map(dictionary)
```
**map을 사용하면 dictionary를 사용하여 key값에 value 값을 대입해줍니다.**

**문자열 데이터를 처리하는 encoding 등에 활용됩니다.**

**이 코드에서는 문자열 값인 경칭을 숫자로 변환 시키기 위하여 사용되었습니다.**

**map uses dictionary to insert a value into the key value.**

**It is used for encoding processing string data.**

**In this code, it was used to convert the honorifics into numbers.**

---

# --drop()

In [ ]:
train = train.drop("Ticket",axis=1)

---
```python
train.drop(["Ticket"],axis=1)
```
**특정 열이나 행을 삭제합니다.**

**axis가 1이면 열을 삭제하고 0이면 행을 삭제합니다.**

**여러 열을 동시에 삭제하고 싶다면 리스트에 column명들을 넣어주면 됩니다.**

**이 코드에서는 이용하지 않는 Ticket열을 삭제하였습니다.**

**Delete a specific column or row.**

**Delete columns if axis is 1 and rows if it is 0.**

**If you want to delete multiple columns at the same time, you can put column names in the list.**

**I deleted the ticket column that is not used in this code.**

---

# **--조건에 맞는 행 리턴(if in DataFrame)**

In [ ]:
train[train["Name_2"]=="Rev"]

In [ ]:
train[(train["Parch"]==4) | (train["Parch"]==6)]

---
```python
train[train["Name_2"]=="Rev"]
```
**DataFrame의 대괄호 안에 조건을 입력하면 DataFrame 중에서 그 조건을 충족하는 데이터들을 리턴합니다.**

**if문과 비슷하게 or나 and를 사용하여 조건을 여러개 넣을 수 있습니다.**

**이 코드에서는 신부님의 데이터를 추출하거나 동승자 중 가족의 수가 4명과 6명인 특이 케이스를 확인하는데 사용되었습니다.**

**If you enter a condition in brackets of the DataFrame, it returns the data that meets the condition among the DataFrames.**

**You can put several conditions using or and similar to the if statement.**

**This code was used to extract the bride's data or to identify specific cases with 4 and 6 family members among the passengers.**

---

# --sort_values()

In [ ]:
train[train["SibSp"]>=5].sort_values("SibSp")

---
```python
train.sort_values("Age")
```
**특정 column을 기준으로 데이터를 정렬합니다.**

**이 코드에서는 조건에 맞는 데이터들을 SibSp column을 기준으로 정렬하였습니다.**

**Sorting data based on a specific column.**

**In this code, the data that meets the conditions were sorted based on the SibSp column.**

---

# --sort_index()

In [ ]:
train[train["SibSp"]>=5].sort_index()

---
```python
train.sort_index()
```
**index 기준으로 데이터를 정렬합니다.**

**이 코드에서는 조건에 맞는 데이터를 index를 기준으로 정렬하였습니다.**

**Sorting data based on index.**

**In this code, the data that meets the conditions were sorted based on the index.**

---

# --sum()

In [ ]:
train["Fare"].sum()

---
```python
train["Fare"].sum()
```
**sum 기능을 사용하면 행이나 열의 수를 합친 결과를 리턴합니다.**

**기본적으로 각 열의 합을 리턴합니다. axis를 1로 설정하면 각 행의 합을 리턴합니다.**

**이 코드에서는 가격의 합을 확인하였습니다**

**sum method returns the result of adding the number of rows or columns.**

**Returns the sum of each column by default. Setting Axis to 1 returns the sum of each row.**

**We checked the sum of the Fare in this code.**

---

# --isnull()

In [ ]:
train.isnull()

In [ ]:
train.isnull().sum()

---
```python
train.isnull()
```

**결측값여부를 boolean 형태로 리턴합니다.**

**보통 sum을 같이 사용하여 각 column의 결측값의 수를 확인합니다.**

**Return the missing value in the form of boolean.**

**Usually, check the number of missing values in each column with the sum method.**

---

# --notnull()

In [ ]:
train.notnull()

---
```python
train.notnull()
```

**값이 결측값이 아닌지 여부를 boolean 형태로 반환합니다.**

**보통 sum을 같이 사용하여 각 column의 결측값이 아닌 값의 수를 확인합니다.**

**Return the not missing value in the form of boolean.**

**Usually, check the number of not missing values in each column with the sum method.**

---

# --min()

In [ ]:
train["Age"].min()

---
```python
train["Age"].min()
```
**column의 최솟값을 리턴합니다.**

**결측치를 채우는 값에 이용되기도 합니다.**

**이 코드는 나이의 최솟값을 확인하였습니다.**

**Returns the minimum value of column.**

**It is also used to fill in missing values.**

**This code checked the minimum age value.**

---

# --max()

In [ ]:
train["Age"].max()

---
```python
train["Age"].max()
```
**column의 최댓값을 리턴합니다.**

**결측치를 채우는 값에 이용되기도 합니다.**

**이 코드는 나이의 최댓값을 확인하였습니다.**

**Returns the maximum value of column.**

**It is also used to fill in missing values.**

**This code checked the maximum age value.**

---

# --mean()

In [ ]:
test["Fare"].mean()

---
```python
train["Fare"].mean()
```
**column의 평균값을 리턴합니다.**

**결측치를 채우는 값에 이용되기도 합니다.**

**이 코드는 티켓 가격의 평균값을 확인하였습니다.**

**Returns the average value of the column.**

**It is also used to fill in missing values.**

**This code checked the average value of the Fare.**

---

# --mode()

In [ ]:
train["Embarked"].mode()[0]

---
```python
train["Embarked"].mode()[0]
```
**column의 최빈값을 리턴합니다.**

**결측치를 채우는 값에 이용되기도 합니다.**

**이 코드는 승선 위치의 최빈값을 확인하였습니다.**

**Returns the mode value of column.**

**It is also used to fill in missing values.**

**This code checked the mode value of the boarding location.**

---

# --count()

In [ ]:
train.count()

---
```python
train.count()
```
**결측값이 아닌 값의 수를 알 수 있습니다.**

**You can know the number of values that are not missing values.**

**The value is the same as**
```python
train.notnull().sum()
```
**와 값이 같습니다.**

**데이터를 보면 cabin에 결측치가 많은 것을 알 수 있습니다.**

**The data shows that cabin has many missing values.**

---

# --fillna()

In [ ]:
test["Fare"] = test["Fare"].fillna(test["Fare"].mean())
train["Embarked"] = train["Embarked"].fillna(train["Embarked"].mode()[0])

In [ ]:
test["Fare"].isnull().sum()

---
```python
test["Fare"] = test["Fare"].fillna(test["Fare"].mean())
train["Embarked"] = train["Embarked"].fillna(train["Embarked"].mode()[0])
```

**결측값을 특정값으로 대체할 수 있습니다.**

**평균이나 최빈값을 이용하거나 아예 새로운 값으로 지정하여 결측치를 표현하기도 합니다.**

**이 코드에서는 가격의 결측값을 가격의 평균으로 대체하고 승선위치의 결측값을 가장 많은 사람이 승선한 위치로 대체하였습니다.**

**You can replace missing values with specific values.**

**Express missing values by using the average or mode value or by designating them as completely new values.**

**In this code, the missing value of the Fare was replaced by the average of the Fare, and the missing value of the boarding location was replaced by the location where the largest number of people boarded.**

---

# --dropna()

In [ ]:
train.dropna()

---
```python
train.dropna()
```
**결측값이 있는 행이나 열을 삭제합니다. (결측치가 있는 행을 삭제하는 것을 기본으로 하며 axis를 1로 설정하면 열을 삭제합니다.)**

**이 코드에서는 결측값이 있는 행이 오류를 일으키기 전에 삭제겸 체크해주는 용도로 사용되었습니다.**

**Delete rows or columns with missing values. (It is based on deleting rows with missing values, and if Axis is set to 1, it deletes columns.)**

**This code was used to delete and check rows with missing values.**

---

# --get_dummies()

In [ ]:
train = pd.get_dummies(train, columns = ["SibSp","Parch","Name_2","Embarked"])
train = pd.get_dummies(train, columns = ["Cabin"], dummy_na = True)

---
```python
train = pd.get_dummies(train, columns = [cols])
```
**column의 값들에 대해서 one-hot encoding을 진행해줍니다.**

**dummy_na를 True로 설정하면 NaN값을 하나의 값으로 인식하여 one-hot encoding을 진행합니다.**

**이 코드에서는 범주형 변수를 one-hot encoding 했습니다.**

**One-hot encoding is performed on the values of the column.**

**If dummy_na is set to True, one-hot encoding proceeds by recognizing the NaN value as one value.**

**In this code, categorical variables were one-hot encoded.**

---

# --cut()

In [ ]:
train["Fare"] = pd.cut(train["Fare"], bins=10,labels=range(10))

---
```python
pd.cut(train["Fare"], bins=10,labels=range(10))
```
**연속된 수를 n개의 구간으로 나누어줍니다.**

**labels 옵션을 이용하여 labeling을 할 수 있습니다.**

**주로 수치형 변수를 범주형 변수로 바꾸는데 사용됩니다.**

**범주형 변수는 (조금 싸다, 싸다, 조금 비싸다, 비싸다) 이런식으로 구간이 나뉘어 있어서 해석이 용이합니다.**

**이 코드에서는 가격을 10개의 구간으로 나누는데 사용되었습니다.**

**Divide the consecutive number into n intervals.**

**You can label using the label option.**

**It is mainly used to replace numerical variables with categorical variables.**

**Category variables are easy to interpret because they are divided into sections like (a little cheap, cheap, a little expensive, and expensive).**

**This code was used to divide Fare into 10 sections.**

---

# --dtype

In [ ]:
train["Fare"].dtype

---
```python
train["Fare"].dtype
```
**특정 column의 자료형을 확인할 수 있습니다.**

**이 코드에서는 가격 column의 자료형을 확인하였고 float64인 것을 알 수 있습니다.**

**You can check the data type of a specific column.**

**In this code, we checked the data type of the Fare column and found that it is float64.**

---

# --astype()

In [ ]:
train["Fare"] = train["Fare"].astype(int)

In [ ]:
train["Fare"].dtype

---
```python
train["Fare"].astype(int)
```

**특정 column의 자료형을 변경할 수 있습니다.**

**이 코드에서는 범주형 변수로 변환된 가격을 int 형태로 변환해주었습니다.**

**You can change the data type of a specific column.**

**In this code, the Fare converted into a categorical variable was converted into an int form.**

---

# **numpy**

**numpy는 numerical python으로 다차원 배열의 수학적 연산에 특화된 python 라이브러리입니다.**

**말 그대로 수학적 연산을 빠르게 하는데 도움이 됩니다.**

**numpy is a python library specialized in mathematical operations of multidimensional arrays.**

**It literally helps speed up mathematical operations.**

# --import

In [ ]:
import numpy as np

---
```python 
import numpy
import numpy as np
import numpy as npy
```

**python에서 numpy 라이브러리를 사용하기 위해 import 하는 과정입니다.**

**as np를 이용한다면 이후 method를 사용할 때 np로 축약하여 사용할 수 있습니다.**

**마찬가지로 as npy로 사용한다면 이후 npy로 사용할 수 있습니다.**

**This is the process of exporting to use the numpy library in python.**

**If you use as np, you can abbreviate it to np when using the method later.**

**Likewise, if you use it as an npy, you can use it as an npy afterwards.**

---

# --around()

---
```python
imsi_df["Age"] = np.around(model.predict(train[train["Age"].isnull()].drop(["Survived","Age"],axis=1)))
```
**python의 round method처럼 반올림을 해줍니다.**

**이 코드에서는 다른 값들로 나이를 예측하여 소숫점으로 된 나이를 반올림 해주었습니다.**

**Round it up like Python's round method.**

**In this code, the age was predicted with different values and rounded to the decimal age.**

---

# --array()

In [ ]:
score = np.array([1,2,3,4,5])

In [ ]:
type(score)

---
```python
np.array(list또는 값)
```

**숫자로 이루어진 numpy 배열을 생성할 수 있습니다.**

**numpy 배열은 mean 등의 수학적 연산을 method를 이용하여 쉽게 진행할 수 있습니다.**

**이 코드는 1,2,3,4,5를 인자로 가지는 numpy 배열을 생성합니다.**

**You can create a numpy array consisting of numbers.**

**numpy arrangement can easily proceed with mathematical operations such as mean using a method.**

**This code creates a numpy array with factors 1, 2, 3, 4, 5.**

---

# --mean()

In [ ]:
print(np.mean(score))

---
```python
np.mean(array)
```

**numpy 배열값의 평균을 리턴합니다.**

**이 코드는 score array에 대한 평균을 리턴하였습니다.**

**Returns the average of the values in the numpy array.**

**This code returned the average for the score array.**

---

# **감사합니다**

# **Thank you**