In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['test.csv', 'train.csv', 'sample_submission.csv']

In [2]:
!pip install pyspark

Collecting pyspark
  Downloading https://files.pythonhosted.org/packages/37/98/244399c0daa7894cdf387e7007d5e8b3710a79b67f3fd991c0b0b644822d/pyspark-2.4.3.tar.gz (215.6MB)
    100% |████████████████████████████████| 215.6MB 183kB/s eta 0:00:01   35% |███████████▍                    | 77.0MB 16.5MB/s eta 0:00:09
Collecting py4j==0.10.7 (from pyspark)
  Downloading https://files.pythonhosted.org/packages/e3/53/c737818eb9a7dc32a7cd4f1396e787bd94200c3997c72c1dbe028587bd76/py4j-0.10.7-py2.py3-none-any.whl (197kB)
    100% |████████████████████████████████| 204kB 24.1MB/s ta 0:00:01
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Stored in directory: /tmp/.cache/pip/wheels/8d/20/f0/b30e2024226dc112e256930dd2cd4f06d00ab053c86278dcf3
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.7 pyspark-2.4.3
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [3]:
from pyspark import SparkContext
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

In [4]:
sc = SparkContext(appName = "Forest_Cover")

In [5]:
spark = SparkSession.Builder().getOrCreate()

In [6]:
from pyspark.ml.linalg import Vectors
from pyspark.ml.feature import StringIndexer
from pyspark.sql.types import StructType, StructField, IntegerType, StringType

In [7]:
train = spark.read.csv('../input/train.csv',header = True,inferSchema=True)
test = spark.read.csv('../input/test.csv',header = True,inferSchema=True)

In [8]:
train.limit(5).toPandas()

   Id  Elevation  Aspect     ...      Soil_Type39  Soil_Type40  Cover_Type
0   1       2596      51     ...                0            0           5
1   2       2590      56     ...                0            0           5
2   3       2804     139     ...                0            0           2
3   4       2785     155     ...                0            0           2
4   5       2595      45     ...                0            0           5

[5 rows x 56 columns]

In [9]:
test.limit(5).toPandas()

      Id  Elevation  Aspect     ...       Soil_Type38  Soil_Type39  Soil_Type40
0  15121       2680     354     ...                 0            0            0
1  15122       2683       0     ...                 0            0            0
2  15123       2713      16     ...                 0            0            0
3  15124       2709      24     ...                 0            0            0
4  15125       2706      29     ...                 0            0            0

[5 rows x 55 columns]

In [10]:
train.count()

15120

In [11]:
test.count()

565892

In [12]:
train_mod = train.withColumn("HF1", train.Horizontal_Distance_To_Hydrology + train.Horizontal_Distance_To_Fire_Points) \
.withColumn("HF2", abs(train.Horizontal_Distance_To_Hydrology - train.Horizontal_Distance_To_Fire_Points)) \
.withColumn("HR1", abs(train.Horizontal_Distance_To_Hydrology + train.Horizontal_Distance_To_Roadways)) \
.withColumn("HR2", abs(train.Horizontal_Distance_To_Hydrology - train.Horizontal_Distance_To_Roadways)) \
.withColumn("FR1", abs(train.Horizontal_Distance_To_Fire_Points + train.Horizontal_Distance_To_Roadways)) \
.withColumn("FR2", abs(train.Horizontal_Distance_To_Fire_Points - train.Horizontal_Distance_To_Roadways)) \
.withColumn("ele_vert", train.Elevation - train.Vertical_Distance_To_Hydrology) \
.withColumn("slope_hyd", pow((pow(train.Horizontal_Distance_To_Hydrology,2) + pow(train.Vertical_Distance_To_Hydrology,2)),0.5)) \
.withColumn("Mean_Amenities", (train.Horizontal_Distance_To_Fire_Points + train.Horizontal_Distance_To_Hydrology + train.Horizontal_Distance_To_Roadways)/3) \
.withColumn("Mean_Fire_Hyd", (train.Horizontal_Distance_To_Fire_Points + train.Horizontal_Distance_To_Hydrology)/2)

test_mod = test.withColumn("HF1", test.Horizontal_Distance_To_Hydrology + test.Horizontal_Distance_To_Fire_Points) \
.withColumn("HF2", abs(test.Horizontal_Distance_To_Hydrology - test.Horizontal_Distance_To_Fire_Points)) \
.withColumn("HR1", abs(test.Horizontal_Distance_To_Hydrology + test.Horizontal_Distance_To_Roadways)) \
.withColumn("HR2", abs(test.Horizontal_Distance_To_Hydrology - test.Horizontal_Distance_To_Roadways)) \
.withColumn("FR1", abs(test.Horizontal_Distance_To_Fire_Points + test.Horizontal_Distance_To_Roadways)) \
.withColumn("FR2", abs(test.Horizontal_Distance_To_Fire_Points - test.Horizontal_Distance_To_Roadways)) \
.withColumn("ele_vert", test.Elevation - test.Vertical_Distance_To_Hydrology) \
.withColumn("slope_hyd", pow((pow(test.Horizontal_Distance_To_Hydrology,2) + pow(test.Vertical_Distance_To_Hydrology,2)),0.5)) \
.withColumn("Mean_Amenities", (test.Horizontal_Distance_To_Fire_Points + test.Horizontal_Distance_To_Hydrology + test.Horizontal_Distance_To_Roadways)/3) \
.withColumn("Mean_Fire_Hyd", (test.Horizontal_Distance_To_Fire_Points + test.Horizontal_Distance_To_Hydrology)/2)

In [13]:
train_mod.limit(2).toPandas()

   Id  Elevation      ...        Mean_Amenities  Mean_Fire_Hyd
0   1       2596      ...           2349.000000         3268.5
1   2       2590      ...           2275.666667         3218.5

[2 rows x 66 columns]

In [14]:
test_mod.limit(2).toPandas()

      Id  Elevation      ...        Mean_Amenities  Mean_Fire_Hyd
0  15121       2680      ...           3109.666667         3322.5
1  15122       2683      ...           3109.666667         3337.5

[2 rows x 65 columns]

In [15]:
train_columns = test_mod.columns[1:]

In [16]:
train_mod.printSchema

<bound method DataFrame.printSchema of DataFrame[Id: int, Elevation: int, Aspect: int, Slope: int, Horizontal_Distance_To_Hydrology: int, Vertical_Distance_To_Hydrology: int, Horizontal_Distance_To_Roadways: int, Hillshade_9am: int, Hillshade_Noon: int, Hillshade_3pm: int, Horizontal_Distance_To_Fire_Points: int, Wilderness_Area1: int, Wilderness_Area2: int, Wilderness_Area3: int, Wilderness_Area4: int, Soil_Type1: int, Soil_Type2: int, Soil_Type3: int, Soil_Type4: int, Soil_Type5: int, Soil_Type6: int, Soil_Type7: int, Soil_Type8: int, Soil_Type9: int, Soil_Type10: int, Soil_Type11: int, Soil_Type12: int, Soil_Type13: int, Soil_Type14: int, Soil_Type15: int, Soil_Type16: int, Soil_Type17: int, Soil_Type18: int, Soil_Type19: int, Soil_Type20: int, Soil_Type21: int, Soil_Type22: int, Soil_Type23: int, Soil_Type24: int, Soil_Type25: int, Soil_Type26: int, Soil_Type27: int, Soil_Type28: int, Soil_Type29: int, Soil_Type30: int, Soil_Type31: int, Soil_Type32: int, Soil_Type33: int, Soil_Type34: int, Soil_Type35: int, Soil_Type36: int, Soil_Type37: int, Soil_Type38: int, Soil_Type39: int, Soil_Type40: int, Cover_Type: int, HF1: int, HF2: int, HR1: int, HR2: int, FR1: int, FR2: int, ele_vert: int, slope_hyd: double, Mean_Amenities: double, Mean_Fire_Hyd: double]>

In [17]:
from pyspark.ml.feature import VectorAssembler
assembler = VectorAssembler()\
.setInputCols(train_columns)\
.setOutputCol("features")
train_mod01 = assembler.transform(train_mod)

In [18]:
train_mod01.limit(2).toPandas()

   Id                        ...                                                                   features
0   1                        ...                          (2596.0, 51.0, 3.0, 258.0, 0.0, 510.0, 221.0, ...
1   2                        ...                          (2590.0, 56.0, 2.0, 212.0, -6.0, 390.0, 220.0,...

[2 rows x 67 columns]

In [19]:
train_mod02 = train_mod01.select("features","Cover_Type")

In [20]:
test_mod01 = assembler.transform(test_mod)
test_mod02 = test_mod01.select("Id","features")

In [21]:
from pyspark.ml.classification import RandomForestClassifier, RandomForestClassificationModel
rfClassifer = RandomForestClassifier(labelCol = "Cover_Type", numTrees = 100)

In [22]:
from pyspark.ml import Pipeline
pipeline = Pipeline(stages = [rfClassifer])

In [23]:
from pyspark.ml.tuning import CrossValidator, ParamGridBuilder
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

In [24]:
paramGrid = ParamGridBuilder()\
   .addGrid(rfClassifer.maxDepth, [1, 2, 4, 5, 6, 7, 8])\
   .addGrid(rfClassifer.minInstancesPerNode, [1, 2, 4, 5, 6, 7, 8])\
   .build()

In [25]:
evaluator = MulticlassClassificationEvaluator(labelCol = "Cover_Type", predictionCol = "prediction", metricName = "accuracy") 

crossval = CrossValidator(estimator = pipeline,
                          estimatorParamMaps = paramGrid,
                          evaluator = evaluator,
                          numFolds = 10)

In [26]:
cvModel = crossval.fit(train_mod02)

In [27]:
cvModel.avgMetrics

[0.40167241787808816,
 0.40167241787808816,
 0.40167241787808816,
 0.40167241787808816,
 0.40167241787808816,
 0.40167241787808816,
 0.40167241787808816,
 0.5875949376648597,
 0.5875949376648597,
 0.5875949376648597,
 0.5875949376648597,
 0.5875949376648597,
 0.5875949376648597,
 0.5875949376648597,
 0.6813604563665497,
 0.6814281318634647,
 0.6815920855388401,
 0.679682092914531,
 0.6802638697622924,
 0.6800018884758674,
 0.6803529518144835,
 0.7108593069449526,
 0.7114067795053509,
 0.7125265009056192,
 0.7117032388996498,
 0.7116966897223679,
 0.7118874827066354,
 0.7122561999413177,
 0.7346763018067033,
 0.7362870216412238,
 0.7340190789609228,
 0.7347786051743107,
 0.7338909804175221,
 0.7367275134033853,
 0.7344067931573102,
 0.7551220527150094,
 0.7571343044589359,
 0.7543322411300741,
 0.7544625205788414,
 0.7528042407009963,
 0.7542749508005651,
 0.755320058931209,
 0.779363210553066,
 0.7774005708839716,
 0.7745557864781036,
 0.7734629493084062,
 0.7728027120158414,
 0.7737390267165242,
 0.7735831012318796]

In [28]:
cvModel.bestModel.stages

[RandomForestClassificationModel (uid=RandomForestClassifier_b2d5b6ccc005) with 100 trees]

In [29]:
prediction = cvModel.transform(test_mod02)

In [30]:
selected = prediction.select("Id","features", "probability", "prediction")

In [31]:
selected.limit(5).toPandas()

      Id    ...     prediction
0  15121    ...            2.0
1  15122    ...            2.0
2  15123    ...            2.0
3  15124    ...            2.0
4  15125    ...            2.0

[5 rows x 4 columns]

In [32]:
sub_final = selected.select(col("Id"),col("prediction").cast(IntegerType()).alias("Cover_Type"))

In [33]:
sub_final.limit(2).toPandas()

      Id  Cover_Type
0  15121           2
1  15122           2