## 5.1 Pandas란?

- pandas는 <b>"python data analysis"</b>의 약자입니다.
> pandas는 정형 데이터 처리에 특화되어 있다.

- pandas 역시 다양한 머신러닝 라이브러리들에 의존성을 가지고 있습니다.
> scikit-learn, scipy, statsmodel, tensorflow, pytorch, ...


- 간단하게 생각하면, **python에서 excel의 기능을 사용**할 수 있게 됩니다.
> pandas = python + excel // pandas & excel // pandas VS MS Excel

- 하지만, pandas는 numpy array를 베이스로 지원하며 파이썬과 함께 강력한 시너지를 내기 때문에, 엑셀 그 이상의 퍼포먼스를 냅니다.
> pandas가 Excel에 비해 고성능 데이터처리에 적합하다.

![numpy_data_type](../images/pandas/dataframe.png)

- Pandas 라이브러리에서 기본적으로 데이터를 다루는 단위는 DataFrame입니다. 흔히 알고있는 spreadsheet와 같은 개념입니다.


- 이러한 형태의 데이터는 Structured Data 또는 Panel Data 또는 Tabular Data라고 부릅니다.


- pandas를 공부한다는 것은 결국 dataframe의 사용법을 익히고 활용하는 방법을 배운다는 것과 같습니다.


- pandas를 잘 활용하면 대부분의 structured data를 자유자재로 다룰 수 있게 됩니다.

![pandas_files](../images/pandas/pandas_files.png)

## 5.2. Pandas의 기본 자료구조(Series, DataFrame)

In [ ]:
# pandas 라이브러리를 불러옵니다. pd를 약칭으로 사용합니다.
import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt
#import seaborn as sns

- DataFrame은 2차원 테이블이고, 테이블의 한 줄(행/열)을 Series라고 합니다.


- Series의 모임이 곧, DataFrame이 됩니다.

In [ ]:
# s는 1, 3, 5, np.nan, 6, 8을 원소로 가지는 pandas.Series
pd.Series([1, 3, 5, np.nan, 6, 8])

- pandas는 date_range라는 함수를 통해, 날짜정보를 쉽게 생성해주는 객체도 제공합니다.

In [ ]:
# 20220101부터 6일간의 날짜 범위를 생성하는 pandas.date_range
dates = pd.date_range('20220101', periods=6)
dates

In [ ]:
# 6x4 행렬에 -1에서 1 사이의 랜덤한 숫자를 가지는 원소를 가지고, index열은 dates, 나머지 coulmns은 순서대로 A, B, C, D로 하는 DataFrame 생성
np.random.seed(0)

df = pd.DataFrame(index=dates, columns=["A", "B", "C", "D"],
                 data=np.random.randn(6, 4))
df

## 5.3. Dataframe 기초 method

In [ ]:
# dataframe의 맨 위 다섯줄을 보여주는 head()
df.head()

In [ ]:
# 3줄
df.head(3)

In [ ]:
# dataframe index
df.index

In [ ]:
# dataframe columns
df.columns

In [ ]:
# dataframe values
df.values

In [ ]:
# dataframe에 대한 전체적인 요약정보를 보여줍니다. index, columns, null/not-null/dtype/memory usage가 표시됩니다.
df.info()

In [ ]:
# dataframe에 대한 전체적인 통계정보를 보여줍니다.
df.describe()

In [ ]:
# column B를 기준으로 내림차순 정렬
df.sort_values(by="B", ascending=False)

## 5.4. DataFrame Indexing

> Indexing : 데이터에서 어떤 특정 조건을 만족하는 원소를 찾는 방법.

> 전체 DataFrame에서 조건에 만족하는 데이터를 쉽게 찾아서 조작할 때 유용하게 사용할 수 있습니다.

In [ ]:
# pandas dataframe은 column 이름을 이용하여 기본적인 Indexing이 가능합니다.
# column A를 indexing
df[["A", "D"]]

In [ ]:
# 특정날짜를 통한 Indexing
df.loc['2022-01-01']

In [ ]:
# 특정 위치를 통한 indexing
df.iloc[0]

In [ ]:
# dataframe에서 slicing을 이용하면 row 단위로 잘려나옵니다.
# 앞에서 3줄을 slicing 합니다.
df[1:4]

In [ ]:
# df에서 index value를 기준으로 indexing도 가능합니다. (여전히 row 단위)
# 20220102부터 20220104까지 잘라봅니다. # index의 값을 사용하게되면 Index를 이용한 slicing
df["2022-01-02":"2022.01.04"]

In [ ]:
df.loc['2021-01-02'] # index를 찾음.

In [ ]:
# df.loc는 특정값을 기준으로 indexing합니다. (key - value)
# 2021-01-01값을 가지는 row를 가져옵니다.
df.loc['2022-01-02', "D"]

In [ ]:
# df.loc에 2차원 indexing도 가능합니다. [:, ["A", "B"]]의 의미는 모든 row에 대해서 columns는 A, B만 가져오라는 의미입니다.
df.loc[:, ["A", "B"]]

In [ ]:
# 이번엔 slicing을 통해 특정 row중에서 columns는 A, B
df.loc['20220103':'20220105', "B":"D"]

In [ ]:
# 특정 row를 index값을 통한 indexing
df.iloc[1, 3]

In [ ]:
# 2차원 리스트 indexing과 같은 원리가 되었습니다.
df.iloc[1][3]

In [ ]:
# iloc로 2차원 indexing을 하게되면, row 기준으로 index 3,4를 가져오고 column 기준으로 0, 1을 가져옵니다.
df.iloc[[3, 4], [0, 1]]

In [ ]:
# slicing이 아닌 직접 리스트 형태로 기재하는 indexing
df.iloc[:, 1:3]

In [ ]:
# Q. 2차원 indexing에 뒤에가 : 면 어떤 의미일까요?
df.iloc[1:5, :]

In [ ]:
# numpy array의 2차원 indexing과 같다.

In [ ]:
df

In [ ]:
# pandas는 fancy indexing을 지원합니다. (사실 numpy에서 지원하기 때문에 pandas도 지원합니다.)
# fancy indexing이란 조건문을 통해 indexing을 할 수 있는 방법으로 True와 False를 원소로 하는 리스트를 통해 masking하는 원리로 동작합니다.
# column A에 있는 원소들중에 0보다 큰 데이터를 가져옵니다.
# 1. column A
df["A"]
# 2. column A에 있는 원소들중에 0보다 큰
df["A"] > 0  ## mask
# 3. 데이터를 가져옵니다.
df[df["A"] > 0]
# 4. column A에 있는 값만 가져옵니다.
df.loc[df["A"] > 0, "A"]

In [ ]:
# fancy indexing
## df에서 column B에 있는 값이 1보다 작은 모든 값들을 출력해주세요.
df.loc[df.B < 1, "B"]

In [ ]:
df[df < 0] = 0
df

In [ ]:
#df[df > 0]
df[df > 0] # NaN으로 나오는 친구들은 조건을 만족하지 못하는 값들입니다.

In [ ]:
# dataframe 하나를 복사합니다. 정말 말그대로 복사합니다.
df2 = df.copy()
df2

In [ ]:
# dataframe은 dictionary와 비슷한 방식으로 assignment가 가능합니다.
# df에 ['one', 'one','two','three','four','three'] 리스트를 column의 value로 하는 column E를 추가합니다.
df2["E"] = ['one', 'one', 'two', 'three', 'four', "three"] # categorical variable
df2

In [ ]:
# df.isin은 해당 value들이 들어있는 row에 대해선 True를 가지는 Series를 리턴한다.
df2['E'].isin(['two','four']) # two와 four가 포함된 모든 row

In [ ]:
# df2에서 column E에 two 또는 four를 가지고 있는 모든 데이터를 출력해주세요.
df2[df2['E'].isin(['two','four'])]

In [ ]:
# df2에 column E가 'one'인 모든 데이터의 column B, C를 출력해주세요.
df2.loc[df2.E == 'one', ["B", "C"]]

In [ ]:
# df2에 column E가 'on'을 포함하고 있는 모든 데이터를 찾아주세요.
#df2[df2.E.str.contains("on")]

# df2에 column E가 't'로 시작하는 모든 데이터를 찾아주세요.
df2.loc[df2.E.str.startswith("t"), :]

- 테이블 데이터에서 조건에 맞는 정보를 찾고 싶다 : `loc`

- 테이블 데이터에서 특정 위치(순서)에 있는 정보를 찾고 싶다 : `iloc`

## 5.5. 외부 데이터 읽고 쓰기

In [ ]:
# data 폴더에 있는 iris.csv를 불러오자.
iris = pd.read_csv("../input/iris/Iris.csv")
iris

In [ ]:
# pivot_table 만들기
## 종별로 Petal 정보에 대해서 평균을 계산.
pd.pivot_table(data=iris, index="Species", # 집계를 할 기준.
               values=["PetalLengthCm", "SepalWidthCm"], # 계산 결과를 보고 싶은 기준.
              aggfunc="mean") # "sum", "count", "mean", ... # 집계 함수.

In [ ]:
# Species column을 숫자로 바꿔보자.
iris.Species.unique() # 종류 확인
iris.Species.value_counts() # 종류별 개수 확인

# Iris-setosa     --> 0
# Iris-versicolor --> 1
# Iris-virginica   --> 2

iris.loc[iris.Species == "Iris-setosa", "Species"] = 0
iris.loc[iris.Species == "Iris-versicolor", "Species"] = 1
iris.loc[iris.Species == "Iris-virginica", "Species"] = 2
iris

In [ ]:
# 바꾼 Dataframe을 Iris_edited.csv 로 저장하자.
iris.to_csv("Iris_edited.csv", index=False)

** ML example **

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X = iris.drop(columns=["Id", "Species"])
y = iris.Species.astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                   random_state=0xC0FFEE)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

In [ ]:
clf = RandomForestClassifier()
clf.fit(X_train, y_train)
print("Accuracy : %.4f" % np.mean(clf.predict(X_test) == y_test))

** ML example **

In [ ]:
# 다른 파일도 불러오자.
survey = pd.read_csv("../input/kaggle-survey-2021/kaggle_survey_2021_responses.csv")
survey

In [ ]:
# 박사 학위 소지자들만 골라보자. --> Q4 column에 "Doctoral degree"
survey.loc[survey.Q4 == "Doctoral degree"]

In [ ]:
# 박사 학위 소지자들에 대한 정보만 kaggle_survey_2020_phd.csv로 다시 저장하자.

In [ ]:
# 대한민국 국적인 사람들을 찾아보자. --> "South Korea"
#survey.Q3.unique()
survey[survey.Q3.str.contains("Korea")]
survey.loc[survey.Q3 == "South Korea"]

In [ ]:
# (OPTIONAL) 박사 학위 소지자이면서, 대한민국 국적을 가진 사람들을 뽑아보자.
# 1) AND 조건
result = survey.loc[(survey.Q3 == "South Korea") & (survey.Q4 == "Doctoral degree")]

# 2) 박사 학위 소지자를 찾은 뒤에, 그 데이터에서 한국 국적 찾기.
result =

In [ ]:
result.to_csv("phd_skorea.csv", index=False)

### 결측치 처리

- 비어있는 정보가 있는 경우에 지우고 싶을 때!

In [ ]:
# 하나라도 결측치가 포함된 row가 있다면 모두 출력.
survey[survey.isnull().any(axis=1)]

In [ ]:
# 결측치가 포함된 row 모두 제거.
temp = survey.dropna()
temp