<img src="https://upload.wikimedia.org/wikipedia/commons/9/97/San_Francisco%E2%80%93Oakland_Bay_Bridge%2C_Partial_View_from_Embarcadero_20110804_1.jpg"/>
<center>[DXR, CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0) , via Wikimedia Commons</center>

# About Competition
From 1934 to 1963, San Francisco was infamous for housing some of the world's most notorious criminals on the inescapable island of Alcatraz.
 Today, the city is known more for its tech scene than its criminal past. With rising wealth inequality and housing shortages, there is no scarcity of crime in the city by the bay.Competition file is available [here](https://www.kaggle.com/c/sf-crime).

# Load Competition Dataset

Competition dataset located in "/kaggle/input"; This path defined by Kaggle to access the competition file. We will list two files from this path as input files.

In [14]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        path=os.path.join(dirname, filename)
        if 'train' in path:
            __training_path=path
        elif 'test' in path:
            __test_path=path

## Input Dataset

In [3]:
#loaded files
print(f'Training path:{__training_path}\nTest path:{__test_path}')

In [1]:
# Kaggle Environment Prepration
#update kaggle env
import sys
#you may update the environment that allow you to run the whole code
!{sys.executable} -m pip install --upgrade scikit-learn=="0.24.2"

In [2]:
#record this information if you need to run the Kernel internally
import sklearn; sklearn.show_versions()

# Exploratory Data Analysis (EDA)
## General Structure
San Francisco Crime dataset includes <b>9</b> columns and <b>878049</b> rows.
There are <b>2</b> different data types as follows: *object, float64*.

Let's review the dataset description:
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
      <th>mean</th>
      <th>std</th>
      <th>min</th>
      <th>25%</th>
      <th>50%</th>
      <th>75%</th>
      <th>max</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>X</th>
      <td>878049.0</td>
      <td>-122.422616</td>
      <td>0.030354</td>
      <td>-122.513642</td>
      <td>-122.432952</td>
      <td>-122.416420</td>
      <td>-122.406959</td>
      <td>-120.5</td>
    </tr>
    <tr>
      <th>Y</th>
      <td>878049.0</td>
      <td>37.771020</td>
      <td>0.456893</td>
      <td>37.707879</td>
      <td>37.752427</td>
      <td>37.775421</td>
      <td>37.784369</td>
      <td>90.0</td>
    </tr>
  </tbody>
</table>

# Finding Intresting Datapoints
Let's process each field by their histogram frequency and check if there is any intresting data point.

There are <b>52</b> number of intresting values in the following columns.
The below table shows each <b>Value</b> of each <b>Field</b>(column) with their total frequencies, <b>Lower</b> shows the lower frequency of normal distribution, <b>Upper</b> shows the upper bound frequency of normal distribution, and <b>Criteria</b> shows if the frequnecy passed <b>Upper bound</b> or <b>Lower bound</b>.
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Field</th>
      <th>Value</th>
      <th>Frequency</th>
      <th>Lower</th>
      <th>Upper</th>
      <th>Criteria</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Dates</td>
      <td>2013-12-01 00:01:00</td>
      <td>44</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Dates</td>
      <td>2013-11-01 00:01:00</td>
      <td>52</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Dates</td>
      <td>2013-06-01 12:00:00</td>
      <td>46</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Dates</td>
      <td>2013-05-01 00:01:00</td>
      <td>51</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Dates</td>
      <td>2012-06-01 00:01:00</td>
      <td>46</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Dates</td>
      <td>2012-01-01 00:01:00</td>
      <td>94</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Dates</td>
      <td>2011-06-01 00:01:00</td>
      <td>50</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Dates</td>
      <td>2011-01-01 00:01:00</td>
      <td>185</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Dates</td>
      <td>2010-12-01 00:01:00</td>
      <td>41</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Dates</td>
      <td>2010-11-01 00:01:00</td>
      <td>51</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Dates</td>
      <td>2010-08-01 00:01:00</td>
      <td>55</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Dates</td>
      <td>2010-06-01 00:01:00</td>
      <td>56</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Dates</td>
      <td>2009-11-01 00:01:00</td>
      <td>42</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Dates</td>
      <td>2009-10-01 00:01:00</td>
      <td>45</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>14</th>
      <td>Dates</td>
      <td>2009-09-01 00:01:00</td>
      <td>46</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>15</th>
      <td>Dates</td>
      <td>2009-05-01 00:01:00</td>
      <td>41</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Dates</td>
      <td>2009-04-01 00:01:00</td>
      <td>45</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>17</th>
      <td>Dates</td>
      <td>2008-11-01 00:01:00</td>
      <td>51</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>18</th>
      <td>Dates</td>
      <td>2008-10-01 00:01:00</td>
      <td>45</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>19</th>
      <td>Dates</td>
      <td>2008-06-01 00:01:00</td>
      <td>48</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>20</th>
      <td>Dates</td>
      <td>2008-05-01 00:01:00</td>
      <td>41</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>21</th>
      <td>Dates</td>
      <td>2008-04-01 00:01:00</td>
      <td>53</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>22</th>
      <td>Dates</td>
      <td>2007-07-01 00:01:00</td>
      <td>44</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>23</th>
      <td>Dates</td>
      <td>2007-06-01 00:01:00</td>
      <td>61</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>24</th>
      <td>Dates</td>
      <td>2006-12-01 00:01:00</td>
      <td>43</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>25</th>
      <td>Dates</td>
      <td>2006-11-01 00:01:00</td>
      <td>46</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>26</th>
      <td>Dates</td>
      <td>2006-07-01 00:01:00</td>
      <td>51</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>27</th>
      <td>Dates</td>
      <td>2006-06-01 00:01:00</td>
      <td>58</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>28</th>
      <td>Dates</td>
      <td>2006-05-01 00:01:00</td>
      <td>43</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>29</th>
      <td>Dates</td>
      <td>2006-01-01 12:00:00</td>
      <td>63</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>30</th>
      <td>Dates</td>
      <td>2006-01-01 00:01:00</td>
      <td>136</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>31</th>
      <td>Dates</td>
      <td>2005-07-01 00:01:00</td>
      <td>49</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>32</th>
      <td>Dates</td>
      <td>2005-06-01 00:01:00</td>
      <td>50</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>33</th>
      <td>Dates</td>
      <td>2004-10-01 00:01:00</td>
      <td>44</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>34</th>
      <td>Dates</td>
      <td>2003-11-01 00:01:00</td>
      <td>43</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>35</th>
      <td>Dates</td>
      <td>2003-10-01 00:01:00</td>
      <td>44</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>36</th>
      <td>Dates</td>
      <td>2003-06-01 00:01:00</td>
      <td>43</td>
      <td>1.0000</td>
      <td>40.0000</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>37</th>
      <td>Category</td>
      <td>LARCENY/THEFT</td>
      <td>174900</td>
      <td>6.0608</td>
      <td>174714.8716</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>38</th>
      <td>Descript</td>
      <td>GRAND THEFT FROM LOCKED AUTO</td>
      <td>60022</td>
      <td>1.0000</td>
      <td>57537.8746</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>39</th>
      <td>PdDistrict</td>
      <td>SOUTHERN</td>
      <td>157182</td>
      <td>45212.6936</td>
      <td>157148.4534</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>40</th>
      <td>Resolution</td>
      <td>NONE</td>
      <td>526790</td>
      <td>51.2656</td>
      <td>526277.3808</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>41</th>
      <td>Address</td>
      <td>800 Block of BRYANT ST</td>
      <td>26533</td>
      <td>1.0000</td>
      <td>4763.3282</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>42</th>
      <td>Address</td>
      <td>2000 Block of MISSION ST</td>
      <td>5097</td>
      <td>1.0000</td>
      <td>4763.3282</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>43</th>
      <td>Address</td>
      <td>800 Block of MARKET ST</td>
      <td>6581</td>
      <td>1.0000</td>
      <td>4763.3282</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>44</th>
      <td>X</td>
      <td>-122.403405</td>
      <td>26354</td>
      <td>1.0000</td>
      <td>3100.4312</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>45</th>
      <td>X</td>
      <td>-122.407634</td>
      <td>3170</td>
      <td>1.0000</td>
      <td>3100.4312</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>46</th>
      <td>X</td>
      <td>-122.419658</td>
      <td>4449</td>
      <td>1.0000</td>
      <td>3100.4312</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>47</th>
      <td>X</td>
      <td>-122.406539</td>
      <td>3891</td>
      <td>1.0000</td>
      <td>3100.4312</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>48</th>
      <td>Y</td>
      <td>37.775421</td>
      <td>26354</td>
      <td>1.0000</td>
      <td>3100.4312</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>49</th>
      <td>Y</td>
      <td>37.784189</td>
      <td>3170</td>
      <td>1.0000</td>
      <td>3100.4312</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>50</th>
      <td>Y</td>
      <td>37.764221</td>
      <td>4449</td>
      <td>1.0000</td>
      <td>3100.4312</td>
      <td>Upper</td>
    </tr>
    <tr>
      <th>51</th>
      <td>Y</td>
      <td>37.756486</td>
      <td>3891</td>
      <td>1.0000</td>
      <td>3100.4312</td>
      <td>Upper</td>
    </tr>
  </tbody>
</table>



For example, in the <b>Dates</b> column the value of <b>2013-12-01 00:01:00</b> has <b>44</b> repeatation but this number is not between Lower bound(1.0) and Upper bound(40.0).


Let     $C_0=2013-12-01 00:01:00$   and   $Freq(C_0)=44$     ,   $Upper(C_0)=40.0$     ,   $Lower(C_0)=1.0$

$Freq(C_0) > Upper(C_0)$.

# Input Dataset

In [ ]:
def __load__data(__training_path, __test_path, concat=False):
	"""load data as input dataset
	params: __training_path: the training path of input dataset
	params: __test_path: the path of test dataset
	params: if it is True, then it will concatinate the training and test dataset as output
	returns: generate final loaded dataset as dataset, input and test
	"""
	# LOAD DATA
	import pandas as pd
	__train_dataset = pd.read_csv(__training_path, delimiter=',')
	__test_dataset = pd.read_csv(__test_path, delimiter=',')
	return __train_dataset, __test_dataset
__train_dataset, __test_dataset = __load__data(__training_path, __test_path, concat=True)
__train_dataset.head()

In [ ]:
# STORE SUBMISSION RELEVANT COLUMNS
__test_dataset_submission_columns = __test_dataset['Id']

### Discard Irrelevant Columns
In the given input dataset there are <b>2</b> columns that can be removed as follows:* Descript,Resolution *.

In [ ]:
# DISCARD IRRELEVANT COLUMNS
__train_dataset.drop(['Descript', 'Resolution'], axis=1, inplace=True)

In [ ]:
# PREPROCESSING-1
_DATE_COLUMNS = ['Dates']
for _col in _DATE_COLUMNS:
    train_date_col = pd.to_datetime(__train_dataset[_col], errors='coerce')
    __train_dataset["year"] = train_date_col.dt.year
    __train_dataset["month"] = train_date_col.dt.month
    __train_dataset["day"] = train_date_col.dt.day
    __train_dataset.drop(_col, axis=1, inplace=True)
    test_date_col = pd.to_datetime(__test_dataset[_col], errors='coerce')
    __test_dataset["year"] = test_date_col.dt.year
    __test_dataset["month"] = test_date_col.dt.month
    __test_dataset["day"] = test_date_col.dt.day
    __test_dataset.drop(_col, axis=1, inplace=True)

### Target Column
The target column is the value which we need to predict.
Therefore, we need to detach the target columns in prediction.
Note that if we don't drop this fields, it will generate a model with high accuracy on training and worst accuracy on test (because the value in test dataset is Null).
Here is the list of *target column*: <b>Category</b>

In [ ]:
# DETACH TARGET
__feature_train = __train_dataset.drop(['Category'], axis=1)
__target_train =__train_dataset['Category']
__feature_test = __test_dataset.drop(['Id'], axis=1)
from sklearn.preprocessing import OneHotEncoder
_CATEGORICAL_COLS = ['Address', 'PdDistrict', 'DayOfWeek']
__col_indices = [__feature_train.columns.get_loc(col) for col in _CATEGORICAL_COLS]
_ohe = OneHotEncoder(handle_unknown='ignore')
from sklearn.compose import ColumnTransformer
__ct = ColumnTransformer([("ohe", _ohe, __col_indices)], remainder = 'passthrough')
__feature_train = __ct.fit_transform(__feature_train)
__feature_test = __ct.transform(__feature_test)

# Training Model and Prediction
First, we will train a model based on preprocessed values of training data set.
Second, let's predict test values based on the trained model.

## Cat Boost Classifier
We will use *CatBoostClassifier* which is Training and applying models for the classification problems. It provides compatibility with the scikit-learn tools.
More detail about *CatBoostClassifier* can be found [here](https://catboost.ai/en/docs/concepts/python-reference_catboostclassifier).

We need to predict the probabilities for each group, therefore we will use *_model.predict_proba()* features  that generates probability for each group.

In [ ]:
# MODEL
import numpy as np
from catboost import CatBoostClassifier
__model = CatBoostClassifier()
__model.fit(__feature_train, __target_train)
__y_pred = __model.predict_proba(__feature_test)

# Submission File
We have to maintain the target columns in "submission.csv" which will be submitted as our prediction results.

In [ ]:
# SUBMISSION
submission = pd.DataFrame(columns=['Id'], data=__test_dataset_submission_columns)
submission = pd.concat([submission, pd.DataFrame(__y_pred, columns=["ARSON", "ASSAULT", "BAD CHECKS", "BRIBERY", "BURGLARY", "DISORDERLY CONDUCT",
"DRIVING UNDER THE INFLUENCE", "DRUG/NARCOTIC", "DRUNKENNESS", "EMBEZZLEMENT", "EXTORTION",
"FAMILY OFFENSES", "FORGERY/COUNTERFEITING", "FRAUD", "GAMBLING", "KIDNAPPING", "LARCENY/THEFT",
"LIQUOR LAWS", "LOITERING", "MISSING PERSON", "NON-CRIMINAL", "OTHER OFFENSES", "PORNOGRAPHY/OBSCENE MAT",
"PROSTITUTION", "RECOVERED VEHICLE", "ROBBERY", "RUNAWAY", "SECONDARY CODES", "SEX OFFENSES FORCIBLE",
"SEX OFFENSES NON FORCIBLE", "STOLEN PROPERTY", "SUICIDE", "SUSPICIOUS OCC", "TREA", "TRESPASS",
"VANDALISM", "VEHICLE THEFT", "WARRANTS", "WEAPON LAWS"])], axis=1)
submission.head()

In [ ]:
# save submission file
submission.to_csv("kaggle_submission.csv", index=False)