In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['train.csv', 'sampleSubmission.csv', 'test.csv']

In [2]:
# Carregar os dados (parse_dates - transporma as datas pra mim no formato certo)
train = pd.read_csv('../input/train.csv', parse_dates=[0])

test = pd.read_csv('../input/test.csv')

In [3]:
train.shape, test.shape

((10886, 12), (6493, 9))

In [4]:
# Verificando quantidades e tipos
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
datetime      10886 non-null datetime64[ns]
season        10886 non-null int64
holiday       10886 non-null int64
workingday    10886 non-null int64
weather       10886 non-null int64
temp          10886 non-null float64
atemp         10886 non-null float64
humidity      10886 non-null int64
windspeed     10886 non-null float64
casual        10886 non-null int64
registered    10886 non-null int64
count         10886 non-null int64
dtypes: datetime64[ns](1), float64(3), int64(8)
memory usage: 1020.6 KB

In [5]:
#Os dados estão escondidos pelo Kaggle no arquivo de test. para depois a gente colocar
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6493 entries, 0 to 6492
Data columns (total 9 columns):
datetime      6493 non-null object
season        6493 non-null int64
holiday       6493 non-null int64
workingday    6493 non-null int64
weather       6493 non-null int64
temp          6493 non-null float64
atemp         6493 non-null float64
humidity      6493 non-null int64
windspeed     6493 non-null float64
dtypes: float64(3), int64(5), object(1)
memory usage: 456.6+ KB

In [6]:
# Verificar o dataframe
train.head().T

                              0         ...                             4
datetime    2011-01-01 00:00:00         ...           2011-01-01 04:00:00
season                        1         ...                             1
holiday                       0         ...                             0
workingday                    0         ...                             0
weather                       1         ...                             1
temp                       9.84         ...                          9.84
atemp                    14.395         ...                        14.395
humidity                     81         ...                            75
windspeed                     0         ...                             0
casual                        3         ...                             0
registered                   13         ...                             1
count                        16         ...                             1

[12 rows x 5 columns]

In [7]:
test.head().T

                              0         ...                             4
datetime    2011-01-20 00:00:00         ...           2011-01-20 04:00:00
season                        1         ...                             1
holiday                       0         ...                             0
workingday                    1         ...                             1
weather                       1         ...                             1
temp                      10.66         ...                         10.66
atemp                    11.365         ...                         12.88
humidity                     56         ...                            56
windspeed               26.0027         ...                       11.0014

[9 rows x 5 columns]

In [8]:
# Transformar a coluna datetime dos dados de teste - Outra forma. Se ele não fez tem algo errado, tem sujeira 
test['datetime']= pd.to_datetime(test['datetime'])

test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6493 entries, 0 to 6492
Data columns (total 9 columns):
datetime      6493 non-null datetime64[ns]
season        6493 non-null int64
holiday       6493 non-null int64
workingday    6493 non-null int64
weather       6493 non-null int64
temp          6493 non-null float64
atemp         6493 non-null float64
humidity      6493 non-null int64
windspeed     6493 non-null float64
dtypes: datetime64[ns](1), float64(3), int64(5)
memory usage: 456.6 KB

In [9]:
# converter a coluna 'count'
train['count'] = np.log(train['count'])

In [10]:
# vamos jubntar o dados de teste e treino para facilitar as transformações
df = train.append(test)

/opt/conda/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [11]:
df.tail().T

                           6488         ...                          6492
atemp                     12.88         ...                        13.635
casual                      NaN         ...                           NaN
count                       NaN         ...                           NaN
datetime    2012-12-31 19:00:00         ...           2012-12-31 23:00:00
holiday                       0         ...                             0
humidity                     60         ...                            65
registered                  NaN         ...                           NaN
season                        1         ...                             1
temp                      10.66         ...                         10.66
weather                       2         ...                             1
windspeed               11.0014         ...                        8.9981
workingday                    1         ...                             1

[12 rows x 5 columns]

In [13]:
# Ordenar os dataframe pelo datetime
df.sort_values('datetime', inplace=True)

## Feature Engineering

In [14]:
# Criando Colunas para data e hora
df['hour'] = df['datetime'].dt.hour
df['day'] = df['datetime'].dt.day
df['dayofweek'] = df['datetime'].dt.dayofweek
df['month'] = df['datetime'].dt.month
df['year'] = df['datetime'].dt.year

In [34]:
df

       atemp  casual     ...       diff_temp_shift_2 rolling_temp
0     14.395     3.0     ...                     NaN     9.840000
1     13.635     8.0     ...                     NaN     9.430000
2     13.635     5.0     ...                   4.555     9.293333
3     14.395     3.0     ...                   4.615     9.430000
4     14.395     0.0     ...                   4.615     9.430000
5     12.880     0.0     ...                   4.555     9.635000
6     13.635     2.0     ...                   4.555     9.635000
7     12.880     1.0     ...                   3.040     9.225000
8     14.395     1.0     ...                   4.615     9.225000
9     17.425     8.0     ...                   4.680    10.045000
10    19.695    12.0     ...                   4.555    11.685000
11    16.665    26.0     ...                   4.305    13.325000
12    21.210    29.0     ...                   4.115    15.170000
13    22.725    47.0     ...                   1.905    16.605000
14    22.725    35.0     ...                   3.990    17.425000
15    21.970    40.0     ...                   3.865    18.245000
16    21.210    41.0     ...                   3.865    18.245000
17    21.970    15.0     ...                   3.930    18.040000
18    21.210     9.0     ...                   3.990    17.630000
19    21.210     6.0     ...                   3.930    17.425000
20    20.455    11.0     ...                   3.990    17.220000
21    20.455     3.0     ...                   3.990    16.810000
22    20.455    11.0     ...                   4.055    16.605000
23    22.725    15.0     ...                   4.055    17.015000
24    22.725     4.0     ...                   4.055    17.630000
25    21.970     1.0     ...                   3.865    18.040000
26    21.210     1.0     ...                   3.865    18.245000
27    22.725     2.0     ...                   3.930    18.245000
28    22.725     2.0     ...                   3.990    18.245000
29    21.210     0.0     ...                   3.865    18.040000
...      ...     ...     ...                     ...          ...
6463  10.605     NaN     ...                   0.640    10.865000
6464  18.180     NaN     ...                   0.705    11.480000
6465   9.850     NaN     ...                   0.765    10.865000
6466  10.605     NaN     ...                   4.240    10.250000
6467   9.850     NaN     ...                   0.830     9.840000
6468   9.850     NaN     ...                   2.405     8.405000
6469   9.090     NaN     ...                   1.650     7.995000
6470   9.090     NaN     ...                   1.650     7.790000
6471   8.335     NaN     ...                   1.710     7.380000
6472   9.090     NaN     ...                   1.710     6.970000
6473   8.335     NaN     ...                   1.775     6.560000
6474   7.575     NaN     ...                   2.530     6.355000
6475   8.335     NaN     ...                   2.595     6.355000
6476   9.090     NaN     ...                   1.015     6.355000
6477   7.575     NaN     ...                   1.775     6.355000
6478  10.605     NaN     ...                   2.530     6.560000
6479  10.605     NaN     ...                   1.835     6.970000
6480  11.365     NaN     ...                   3.225     7.585000
6481  11.365     NaN     ...                   2.405     8.610000
6482  12.880     NaN     ...                   2.345     9.430000
6483  13.635     NaN     ...                   1.525    10.250000
6484  14.395     NaN     ...                   2.220    10.865000
6485  12.880     NaN     ...                   2.155    11.070000
6486  14.395     NaN     ...                   2.915    11.070000
6487  13.635     NaN     ...                   2.220    10.865000
6488  12.880     NaN     ...                   3.735    10.660000
6489  12.880     NaN     ...                   2.975    10.660000
6490  12.880     NaN     ...                   2.220    10.660000
6491  13.635     NaN     ...                   2.220    10.660000
6492  13.635     NaN     ...                   2.220    10.660000

[17379 rows x 25 columns]

In [15]:
# Coluna com a diferença de temperatura
df['diff_temp'] = df['atemp'] - df['temp']

In [16]:
# Coluna com a temperatura da hora anterior
df['temp_shift_1'] = df['temp'].shift(1)
df['temp_shift_2'] = df['temp'].shift(2)

# Para fazer outra forma

#for i in range(3):
#    df[f'temp_shift_{i}'] = df['temp'].shift(i)

In [17]:
# Coluna com a sensação térmica da hora anterior
df['atemp_shift_1'] = df['atemp'].shift(1)
df['atemp_shift_2'] = df['atemp'].shift(2)

In [18]:
# Coluna com a diferença de temperatura da hora anterior
df['diff_temp_shift_1'] = df['diff_temp'].shift(1)
df['diff_temp_shift_2'] = df['diff_temp'].shift(2)

In [19]:
df.head().T

                                     0         ...                             4
atemp                           14.395         ...                        14.395
casual                               3         ...                             0
count                          2.77259         ...                             0
datetime           2011-01-01 00:00:00         ...           2011-01-01 04:00:00
holiday                              0         ...                             0
humidity                            81         ...                            75
registered                          13         ...                             1
season                               1         ...                             1
temp                              9.84         ...                          9.84
weather                              1         ...                             1
windspeed                            0         ...                             0
workingday                           0         ...                             0
hour                                 0         ...                             4
day                                  1         ...                             1
dayofweek                            5         ...                             5
month                                1         ...                             1
year                              2011         ...                          2011
diff_temp                        4.555         ...                         4.555
temp_shift_1                       NaN         ...                          9.84
temp_shift_2                       NaN         ...                          9.02
atemp_shift_1                      NaN         ...                        14.395
atemp_shift_2                      NaN         ...                        13.635
diff_temp_shift_1                  NaN         ...                         4.555
diff_temp_shift_2                  NaN         ...                         4.615

[24 rows x 5 columns]

In [20]:
# Criando uma coluna com a media da temperatura das ultimas 4 horas
df['rolling_temp'] = df['temp'].rolling(4, min_periods=1).mean()

In [21]:
#Verificando o resultado
df[['temp','rolling_temp']].head(10)

    temp  rolling_temp
0   9.84      9.840000
1   9.02      9.430000
2   9.02      9.293333
3   9.84      9.430000
4   9.84      9.430000
5   9.84      9.635000
6   9.02      9.635000
7   8.20      9.225000
8   9.84      9.225000
9  13.12     10.045000

In [35]:
df

       atemp  casual     ...       diff_temp_shift_2 rolling_temp
0     14.395     3.0     ...                     NaN     9.840000
1     13.635     8.0     ...                     NaN     9.430000
2     13.635     5.0     ...                   4.555     9.293333
3     14.395     3.0     ...                   4.615     9.430000
4     14.395     0.0     ...                   4.615     9.430000
5     12.880     0.0     ...                   4.555     9.635000
6     13.635     2.0     ...                   4.555     9.635000
7     12.880     1.0     ...                   3.040     9.225000
8     14.395     1.0     ...                   4.615     9.225000
9     17.425     8.0     ...                   4.680    10.045000
10    19.695    12.0     ...                   4.555    11.685000
11    16.665    26.0     ...                   4.305    13.325000
12    21.210    29.0     ...                   4.115    15.170000
13    22.725    47.0     ...                   1.905    16.605000
14    22.725    35.0     ...                   3.990    17.425000
15    21.970    40.0     ...                   3.865    18.245000
16    21.210    41.0     ...                   3.865    18.245000
17    21.970    15.0     ...                   3.930    18.040000
18    21.210     9.0     ...                   3.990    17.630000
19    21.210     6.0     ...                   3.930    17.425000
20    20.455    11.0     ...                   3.990    17.220000
21    20.455     3.0     ...                   3.990    16.810000
22    20.455    11.0     ...                   4.055    16.605000
23    22.725    15.0     ...                   4.055    17.015000
24    22.725     4.0     ...                   4.055    17.630000
25    21.970     1.0     ...                   3.865    18.040000
26    21.210     1.0     ...                   3.865    18.245000
27    22.725     2.0     ...                   3.930    18.245000
28    22.725     2.0     ...                   3.990    18.245000
29    21.210     0.0     ...                   3.865    18.040000
...      ...     ...     ...                     ...          ...
6463  10.605     NaN     ...                   0.640    10.865000
6464  18.180     NaN     ...                   0.705    11.480000
6465   9.850     NaN     ...                   0.765    10.865000
6466  10.605     NaN     ...                   4.240    10.250000
6467   9.850     NaN     ...                   0.830     9.840000
6468   9.850     NaN     ...                   2.405     8.405000
6469   9.090     NaN     ...                   1.650     7.995000
6470   9.090     NaN     ...                   1.650     7.790000
6471   8.335     NaN     ...                   1.710     7.380000
6472   9.090     NaN     ...                   1.710     6.970000
6473   8.335     NaN     ...                   1.775     6.560000
6474   7.575     NaN     ...                   2.530     6.355000
6475   8.335     NaN     ...                   2.595     6.355000
6476   9.090     NaN     ...                   1.015     6.355000
6477   7.575     NaN     ...                   1.775     6.355000
6478  10.605     NaN     ...                   2.530     6.560000
6479  10.605     NaN     ...                   1.835     6.970000
6480  11.365     NaN     ...                   3.225     7.585000
6481  11.365     NaN     ...                   2.405     8.610000
6482  12.880     NaN     ...                   2.345     9.430000
6483  13.635     NaN     ...                   1.525    10.250000
6484  14.395     NaN     ...                   2.220    10.865000
6485  12.880     NaN     ...                   2.155    11.070000
6486  14.395     NaN     ...                   2.915    11.070000
6487  13.635     NaN     ...                   2.220    10.865000
6488  12.880     NaN     ...                   3.735    10.660000
6489  12.880     NaN     ...                   2.975    10.660000
6490  12.880     NaN     ...                   2.220    10.660000
6491  13.635     NaN     ...                   2.220    10.660000
6492  13.635     NaN     ...                   2.220    10.660000

[17379 rows x 25 columns]

## Treinado o modelo

In [36]:
# Separandop os dataframes
#train = df[~df['count'].isnull()]
#test = df[df['count'].isnull()]

#train.shape, test.shape

In [38]:
# usando outra coluna
train = df[~df['registered'].isnull()]
test = df[df['registered'].isnull()]

train.shape, test.shape

((10886, 25), (6493, 25))

In [23]:
# Salva os dados do dataframe de treino
train_raw = train.copy()

In [24]:
# Separa os dados de treino em treino e validação
from sklearn.model_selection import train_test_split

train, valid = train_test_split(train, random_state=42)

train.shape, valid.shape

((8164, 25), (2722, 25))

In [25]:
# Separando as features e o resultado
removed_cols = ['count', 'casual', 'registered', 'datetime']

In [26]:
# #Separando as colunas a srem usadas para treino
cols = []
for c in train.columns:
    if c not in removed_cols:
        cols.append(c)
        
cols

['atemp',
 'holiday',
 'humidity',
 'season',
 'temp',
 'weather',
 'windspeed',
 'workingday',
 'hour',
 'day',
 'dayofweek',
 'month',
 'year',
 'diff_temp',
 'temp_shift_1',
 'temp_shift_2',
 'atemp_shift_1',
 'atemp_shift_2',
 'diff_temp_shift_1',
 'diff_temp_shift_2',
 'rolling_temp']

In [27]:
#Separando as colunas a srem usadas para treino - a mesma coisa em cima 
feats = [c for c in train.columns if c not in removed_cols]

feats

['atemp',
 'holiday',
 'humidity',
 'season',
 'temp',
 'weather',
 'windspeed',
 'workingday',
 'hour',
 'day',
 'dayofweek',
 'month',
 'year',
 'diff_temp',
 'temp_shift_1',
 'temp_shift_2',
 'atemp_shift_1',
 'atemp_shift_2',
 'diff_temp_shift_1',
 'diff_temp_shift_2',
 'rolling_temp']

In [28]:
# Importar os modelos
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from sklearn.ensemble import AdaBoostRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [29]:
# Dicionario de modelos
models = {'RandomForest': RandomForestRegressor (random_state=42),
          'ExtraTrees': ExtraTreesRegressor (random_state=42),
          'GradientBoosting': GradientBoostingRegressor (random_state=42),
          'DecisionTree': DecisionTreeRegressor (random_state=42),
          'AdaBoost': AdaBoostRegressor (random_state=42),
          'KNM 11': KNeighborsRegressor (n_neighbors=11),
          'SVR': SVR(),
          'linear Regression': LinearRegression()}

In [30]:
#impotando metrica
# from sklearn.metrics import mean_squared_log_error Deu erro
from sklearn.metrics import mean_squared_error

In [31]:
# função para treino dos modelos
def run_model(model, train, valid, feats, y_name):
    model.fit(train[feats], train[y_name])
    preds = model.predict(valid[feats])
    return mean_squared_error(valid[y_name], preds) ** (1/2)

In [32]:
# Executando os modelos
scores = []
for name, model in models.items():
    score = run_model(model, train.fillna(-1), valid.fillna(-1), feats, 'count')
    scores.append(score)
    print(name, ':', score)

/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForest : 0.36396008597484003

/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

ExtraTrees : 0.354897829641594
GradientBoosting : 0.4022846995392303
DecisionTree : 0.49020964837718684
AdaBoost : 0.7145778729794876
KNM 11 : 0.9490422901433017

/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVR : 1.0060380575947392
linear Regression : 1.0124465490636503