In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import numpy as np
import plotly.express as px

In [ ]:
import pandas as pd
surveyXY = pd.read_csv("../input/kaggle-survey-2020/kaggle_survey_2020_responses.csv");

In [ ]:
surveyXY.head()

In [ ]:
surveyX = surveyXY[['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7_Part_1', 'Q7_Part_2', 'Q7_Part_3' ]]
surveyX.head()

In [ ]:
survey = surveyX.iloc[1:,0:]
survey.head()

In [ ]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt
text=("Kaggle Data Scientist Data Engineer Student Python SQL R Research Scientist Machine Learning Engineer Database Engineer Programming Language")
wordcloud = WordCloud(width=480, height=380, margin=0).generate(text)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.margins(x=0, y=0)
plt.show()

In [ ]:
survey["Q1"].value_counts().plot(kind="bar")
plt.title("AGE Groups");

In [ ]:
survey["Q2"].value_counts().plot(kind="barh")
plt.title("Gender");

In [ ]:
survey["Q4"].value_counts().plot(kind="bar")
plt.title("Level of Formal Education");

In [ ]:
survey["Q5"].value_counts().plot(kind="barh")
plt.title("Job Title");

In [ ]:
#Calculation of Python, R and SQL programming language users
col1 = "Q7_Part_1"
Python = survey[col1].value_counts()
col2 = "Q7_Part_2"
R = survey[col2].value_counts()
col3 = "Q7_Part_3"
SQL = survey[col3].value_counts()


labels = 'Python', 'R', 'SQL'
sections = [Python, R, SQL]
colors = ['c', 'g', 'y']

plt.pie(sections, labels=labels, colors=colors)
plt.title(" Programming language users")
plt.show();

In [ ]:
survey.tail()

In [ ]:
import seaborn as sns
sns.catplot(y="Q2", kind="count",
            palette="pastel", edgecolor=".9",
            data= survey);

In [ ]:

f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q5", data=survey, color="blue");
ax.set_title('Job titles', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q4", data=survey, color="g");
ax.set_title('Level of education', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(14, 20))
sns.countplot(y="Q3", data=survey, color="b");
ax.set_title('Country', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=survey, color="cyan");
ax.set_title('Age groups', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q6", data=survey, color="y");
ax.set_title('Work Experience', size = 14, weight='bold');

In [ ]:
survey.tail()

In [ ]:
#Classification of respndents based on programming language use. 
PythonSurvey = survey[survey['Q7_Part_1'] == 'Python']
PythonSurvey.head()

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q5", data=PythonSurvey, color="blue");
ax.set_title('Job titles of Python Users', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q4", data=PythonSurvey, color="g");
ax.set_title('Level of education of Python users', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=PythonSurvey, color="y");
ax.set_title('Age group of Python users', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q6", data=PythonSurvey, color="y");
ax.set_title('Work experience of Python users', size = 14, weight='bold');

In [ ]:
RSurvey = survey[survey['Q7_Part_2'] == 'R']
RSurvey.head()

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q5", data=RSurvey, color="blue");
ax.set_title('Job titles of R users', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q4", data=RSurvey, color="g");
ax.set_title('Education levels of R users', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=RSurvey, color="y");
ax.set_title('Age group of R users', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q6", data=RSurvey, color="y");
ax.set_title('Work experience  of R users', size = 14, weight='bold');

In [ ]:
SQLSurvey = survey[survey['Q7_Part_3'] == 'SQL']
SQLSurvey.head()

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q5", data=SQLSurvey, color="blue");
ax.set_title('Job titles of SQL users', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 6))
sns.countplot(y="Q4", data=SQLSurvey, color="g");
ax.set_title('Education levels of SQL users', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=SQLSurvey, color="y");
ax.set_title('Age group of SQL users', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q6", data=SQLSurvey, color="y");
ax.set_title('Work experience of SQL users', size = 14, weight='bold');

In [ ]:
#Students are the main users of Python, R and SQl however SQL and R programming language users have higher proportion of data scientists.

In [ ]:
#Users with Master's degree are main users of three programming languages.
#Python and SQL language users have higher proportion of users with Bachelor's degree.

In [ ]:
# Users within age group of 25-29 are the main users of R, SQL and Python programming languages followed by age group of 22-24.

In [ ]:
#Users with 3-5 years experience preferred R, SQL and Python programming languages followed by 1-2 years experienced users.

In [ ]:
#Classification based on gender and programming languages
Man_Python = PythonSurvey[PythonSurvey['Q2'] == 'Man']
Woman_Python = PythonSurvey[PythonSurvey['Q2'] == 'Woman']

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=Man_Python, color="blue");
ax.set_title('Age groups of Python users men', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=Woman_Python, color="blue");
ax.set_title('Age groups of Python users Women', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q4", data=Man_Python, color="cyan");
ax.set_title('Education levels of Python users Men', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q4", data=Woman_Python, color="cyan");
ax.set_title('Education levels of Python users Women', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q5", data=Man_Python, color="darkblue");
ax.set_title('Job titles of Python users men', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q5", data=Woman_Python, color="darkblue");
ax.set_title('Job titles of Python users women', size = 14, weight='bold');

In [ ]:
Man_R = RSurvey[RSurvey['Q2'] == 'Man']
Woman_R = RSurvey[RSurvey['Q2'] == 'Woman']

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=Man_R, color="blue");
ax.set_title('Age groups of R users men', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=Woman_R, color="blue");
ax.set_title('Age groups of R users women', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q4", data=Man_R, color="cyan");
ax.set_title('Education levels of R users Men', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q4", data=Woman_R, color="cyan");
ax.set_title('Education levels of R users women', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q5", data=Man_R, color="orange");
ax.set_title('Job titles of R users Men', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q5", data=Woman_R, color="orange");
ax.set_title('Job titles of R users women', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q6", data=Man_R, color="darkblue");
ax.set_title('Work experience of R users Men', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q6", data=Woman_R, color="darkblue");
ax.set_title('Work experience of R users women', size = 14, weight='bold');

In [ ]:
Man_SQL = SQLSurvey[SQLSurvey['Q2'] == 'Man']
Woman_SQL = SQLSurvey[SQLSurvey['Q2'] == 'Woman']

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=Man_SQL, color="cyan");
ax.set_title('Age groups of SQL users men', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=Woman_SQL, color="cyan");
ax.set_title('Age groups of SQL users women', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q4", data=Man_SQL, color="darkblue");
ax.set_title('Education level of SQL users men', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q4", data=Woman_SQL, color="darkblue");
ax.set_title('Education level of SQL users women', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q5", data=Man_SQL, color="green");
ax.set_title('Job titles of SQL users men', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q5", data=Woman_SQL, color="green");
ax.set_title('Job titles of SQL users women', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q6", data=Man_SQL, color="darkblue");
ax.set_title('Work experience of SQL users Men', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q6", data=Woman_SQL, color="darkblue");
ax.set_title('Work experience of SQL users women', size = 14, weight='bold');

In [ ]:
# R, SQL and Python users men have the highest propotion of 25-29 years age group.
# R, SQL and Python users women have the higherst proportion of 22-24 years age group.
# Men and women using all the three programming languages have the highest proportional share of Master's degree holders.
# Data scientists job title have dominance within R, Python, and SQL users men and women.
# Software Engineering job titlte has second highest frequency within Python and Sql users men.
# Data Analysts has second highest frequency within R, Python and Sql users women.

In [ ]:
DataScientists = survey[survey['Q5'] == 'Data Scientist']
ResearchScientist = survey[survey['Q5'] == 'Research Scientist']
SoftwareEngineer = survey[survey['Q5'] == 'Software Engineer']
DataAnalyst = survey[survey['Q5'] == 'Data Analyst']

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q4", data=DataScientists, color="g");
ax.set_title('Education levels of data scientists', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q4", data=SoftwareEngineer, color="b");
ax.set_title('Education levels of data engineers', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q4", data=DataAnalyst, color="y");
ax.set_title('Education levels of data analysts', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q4", data=ResearchScientist, color="cyan");
ax.set_title('Education levels of research scientists', size = 14, weight='bold');

In [ ]:
# Data reveals Research Scientists with the highest proportion of Doctoral degree holders however Data Scientists with highest proportion of Master's degree holder users. 
# Most of the Data Analysts have Master's degree followed by Bachelor's degree.
# Bachelor's degree holder users have dominance in Software Engineering followed by users with Master's degree.

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=DataScientists, color="y");
ax.set_title('Age groups of data scientists', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=ResearchScientist, color="darkblue");
ax.set_title('Age groups of research scientists', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data=DataAnalyst, color="g");
ax.set_title('Age groups of data analysts', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(8, 6))
sns.countplot(y="Q1", data= SoftwareEngineer, color="cyan");
ax.set_title('Age groups of software engineer', size = 14, weight='bold');

In [ ]:
# Age group (25-29) have dominance in Data Analysts and Software Engineer job title followed by age group of 22-24.
# The highest proportion of Data Scientists have age group of 25-29 followed by 30-34.
# The highest proportion of Research Scientists have age group of 30-34 followed by 25-29.

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q6", data=DataScientists, color="y");
ax.set_title('Work experience of data scientists', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q6", data=ResearchScientist, color="g");
ax.set_title('Work experience of research scientists', size = 12, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q6", data=DataAnalyst, color="cyan");
ax.set_title('Work experience of data analysts', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q6", data=SoftwareEngineer, color="y");
ax.set_title('Work experience of software engineers', size = 14, weight='bold');

In [ ]:
# Data reveals the highest proportion of Software Engineer and Data Scientists are 3-5 years experienced. 
# Research scientists users have the highest proportion of 5-10 years of experienced users followed by 10-20 years experiences.
# Data Analysts have users of 1-2 years of experience followed by 3-5 years of experiences.

In [ ]:
#United Kingdom and Northern Ireland Data

UKusers = survey[survey['Q3'] == 'United Kingdom of Great Britain and Northern Ireland']
UKPythonUsers = UKusers[UKusers['Q7_Part_1'] == 'Python']
UKPythonUsersMen = UKPythonUsers[UKPythonUsers['Q2'] == 'Man']
UKPythonUsersWomen = UKPythonUsers[UKPythonUsers['Q2'] == 'Woman']

UKRUsers = UKusers[UKusers['Q7_Part_2'] == 'R']
UKRUsersMen = UKRUsers[UKRUsers['Q2'] == 'Man']
UKRUsersWomen = UKRUsers[UKRUsers['Q2'] == 'Woman']

UKSQLUsers = UKusers[UKusers['Q7_Part_3'] == 'SQL']
UKSQLUsersMen = UKSQLUsers[UKSQLUsers['Q2'] == 'Man']
UKSQLUsersWomen = UKSQLUsers[UKSQLUsers['Q2'] == 'Woman']

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q4", data=UKPythonUsersMen, color="y");
ax.set_title('Education level of Python Users Men in UK', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q4", data=UKPythonUsersWomen, color="y");
ax.set_title('Education level of Python Users Women in UK', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q5", data=UKPythonUsersMen, color="cyan");
ax.set_title('Job title of Python Users Men in UK', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q5", data=UKPythonUsersWomen, color="cyan");
ax.set_title('Job title of Python Users Women in UK', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q5", data=UKRUsersWomen, color="g");
ax.set_title('Job title of R Users women in UK', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q5", data=UKRUsersMen, color="g");
ax.set_title('Job title of R Users Men in UK', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q4", data=UKRUsersMen, color="orange");
ax.set_title('Education level of R Users Men in UK', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q4", data=UKRUsersWomen, color="orange");
ax.set_title('Education level of R Users Women in UK', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q4", data=UKSQLUsersMen, color="darkblue");
ax.set_title('Education level of SQLUsers Men in UK', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q4", data=UKSQLUsersWomen, color="darkblue");
ax.set_title('Education level of SQLUsers Women in UK', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q5", data=UKSQLUsersMen, color="yellow");
ax.set_title('Job title of SQLUsers men in UK', size = 14, weight='bold');

In [ ]:
f, ax = plt.subplots(figsize=(7, 5))
sns.countplot(y="Q5", data=UKSQLUsersWomen, color="yellow");
ax.set_title('Job title of SQLUsers women in UK', size = 14, weight='bold');

In [ ]:
# Data reveals the higher proportion of Master's degree level educated programming language users in the UK and Northern Ireland. 
# R and Python men users have the highest proportion of data scientists followed by Research Scientists.
# R and Python women users have the highest proportion of data scientists followed by data analysts. 
# Men SQL users in the UK and Northern Ireland have the highest proportion of data scientists whereas data analysts are predominant among women SQL users.

In [ ]:
#References
#https://seaborn.pydata.org/introduction.html
#https://plotly.com/python/
#Kaggle.com