In [ ]:
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm

In [ ]:
data = pd.read_csv('../input/tabular-playground-series-jun-2022/data.csv', index_col='row_id')
sub = pd.read_csv('../input/tabular-playground-series-jun-2022/sample_submission.csv', index_col='row-col')

In [ ]:
data.loc[0, 'F_1_14'] = 0
data.loc[0, 'F_3_23'] = 1
data.loc[1, 'F_3_24'] = 2
data.loc[999993, 'F_4_2'] = 3

In [ ]:
%%time

ind_list = []
val_list = []
for i in tqdm(sub.index):
    row = int(i.split('-')[0])
    col = i.split('-')[1]
    val = data[col][row]
    ind_list.append(i)
    val_list.append(val)

sub['value'].loc[ind_list] = val_list
sub

In [ ]:
sub.to_csv("submission.csv", index=True)