In [ ]:
from IPython.display import Image
import os
Image('../input/kggggg/kagg.png')

# Hello Taiwan
https://public.tableau.com/app/profile/.17342172/viz/3_16348160658740/1_2?publish=yes
## About This Notebook:

### Taiwan：

* Age trend
* Salary trend
* About Position
* Industry

### Between Taiwan and World:

* Salary Difference
* Company ML situation
* Learning Online

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.express as px
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
ALLsurvey=pd.read_csv('../input/kaggle-survey-2021/kaggle_survey_2021_responses.csv')
ALLsurvey.drop(0,inplace=True)
ALLsurvey.head()

In [ ]:
import warnings
warnings.filterwarnings("ignore")
if not os.path.exists('/kaggle/working/individual_charts/'):
    os.mkdir('/kaggle/working/individual_charts/')

def load_csv(base_dir,file_name):
    file_path = os.path.join(base_dir,file_name)
    df = pd.read_csv(file_path,low_memory=False,encoding='ISO-8859-1')
    return df    

base_dir_2017 = '/kaggle/input/kaggle-survey-2017/'
file_name_2017 = 'multipleChoiceResponses.csv'
survey_df_2017 = load_csv(base_dir_2017,file_name_2017)
survey_df_2017 = survey_df_2017[survey_df_2017['Country']=='Taiwan'] 
responses_df_2017 = survey_df_2017[1:]
survey_df_2017.to_csv('2017_kaggle_ds_and_ml_survey_data_scientists_in_india_responses_only.csv',index=False)


base_dir_2019 = '/kaggle/input/kaggle-survey-2019/'
file_name_2019 = 'multiple_choice_responses.csv'
survey_df_2019 = load_csv(base_dir_2019,file_name_2019)
survey_df_2019 = survey_df_2019[survey_df_2019['Q3']=='Taiwan']
responses_df_2019 = survey_df_2019[1:]
survey_df_2019.to_csv('2019_kaggle_ds_and_ml_survey_data_scientists_in_india_responses_only.csv',index=False)

base_dir_2020 = '/kaggle/input/kaggle-survey-2020'
file_name_2020 = 'kaggle_survey_2020_responses.csv'
survey_df_2020 = load_csv(base_dir_2020,file_name_2020)
survey_df_2020 = survey_df_2020[survey_df_2020['Q3']=='Taiwan'] 
responses_df_2020 = survey_df_2020[1:]
survey_df_2020.to_csv('2020_kaggle_ds_and_ml_survey_data_scientists_in_india_responses_only.csv',index=False)

base_dir_2021 = '../input/kaggle-survey-2021/'
file_name_2021 = 'kaggle_survey_2021_responses.csv'
survey_df_2021 = load_csv(base_dir_2021,file_name_2021)
survey_df_2021 = survey_df_2021[survey_df_2021['Q3']=='Taiwan'] 
responses_df_2021 = survey_df_2021[1:]
survey_df_2021.to_csv('2021_kaggle_ds_and_ml_survey_data_scientists_in_india_responses_only.csv',index=False)

# Age

In [ ]:
fig=px.pie(responses_df_2019,'Q1',hole=0.6,title='2019 Age Distribution')
fig.update_traces(textinfo='percent+label')
fig.update_layout(uniformtext_minsize=10, uniformtext_mode='hide')
fig.show()

In [ ]:
fig=px.pie(responses_df_2020,'Q1',hole=0.6,title='2020 Age Distribution')
fig.update_traces(textinfo='percent+label')
fig.update_layout(uniformtext_minsize=10, uniformtext_mode='hide')
fig.show()

In [ ]:
fig=px.pie(responses_df_2021,'Q1',hole=0.6,title='2021 Age Distribution')
fig.update_traces(textinfo='percent+label')
fig.update_layout(uniformtext_minsize=10, uniformtext_mode='hide')
fig.show()

* 在30歲以下的人數逐漸上升當中，從2019年42% -> 2020年45.5%->2021年46.5%
* Data領域在台灣越來越火熱，越來越多人想踏入這個朝陽領域
* The number of people under the age of 30 are getting more and more,42% in 2019 -> 45.5% in 2020 -> 46.5% in 2021
* The Data field is becoming more and more HOT!!! in Taiwan, and more and more people want to step into this HOT field

# Salary

In [ ]:
salary2021={# '$0-999':500,
     '25,000-29,999':27500,
 '60,000-69,999':65000,
#  '$0-999':500,
 '30,000-39,999':35000,
 '15,000-19,999':17500,
 '70,000-79,999':75000,
#  '2,000-2,999':2500,
 '10,000-14,999':12500,
 '5,000-7,499':62500,
 '20,000-24,999':22500,
#  '1,000-1,999':1500,
 '100,000-124,999':112500,
 '7,500-9,999':87500,
#  '4,000-4,999':4500,
 '40,000-49,999':45000,
 '50,000-59,999':55000,
#  '3,000-3,999':3500,
 '300,000-499,999':400000,
 '200,000-249,999':225000,
 '125,000-149,999':137500,
 '250,000-299,999':275000,
 '80,000-89,999':85000,
 '90,000-99,999':95000,
 '150,000-199,999':175000,
 '>$1,000,000':1000000,
 '$500,000-999,999':750000}
salary2020={'25,000-29,999':27500, 
#             '2,000-2,999':2500, 
#             '3,000-3,999':3500,
            '50,000-59,999':55000, 
            '30,000-39,999':35000, 
#             '1,000-1,999':1500, 
            '15,000-19,999':17500,
            '10,000-14,999':12500, 
            '40,000-49,999':45000, 
#             '$0-999':500, 
            '20,000-24,999':22500,
            '5,000-7,499':62500, 
            '60,000-69,999':65000, 
#             '4,000-4,999':4500, 
            '70,000-79,999':75000,
#             '7,500-9,999':8750, 
            '100,000-124,999':112500, 
            '80,000-89,999':85000}
salary2019={'80,000-89,999':85000,
#            '2,000-2,999':2500, 
           '30,000-39,999':35000, 
#            '$0-999':500,
           '40,000-49,999':45000, 
           '> $500,000':500000, 
           '20,000-24,999':22500, 
           '25,000-29,999':27500,
           '10,000-14,999':12500, 
#            '7,500-9,999':8750, 
           '60,000-69,999':62500, 
#            '1,000-1,999':1500,
           '15,000-19,999':17500, 
           '100,000-124,999':112500, 
           '70,000-79,999':75000, 
#            '3,000-3,999':3500,
#            '5,000-7,499':6250, 
            '50,000-59,999':55000, 
            '300,000-500,000':450000,
            '125,000-149,999':137500} 
#             '4,000-4,999':4500
responses_df_2019['Q10']=responses_df_2019['Q10'].map(salary2019)
responses_df_2020['Q24']=responses_df_2020['Q24'].map(salary2020)
responses_df_2021['Q25']=responses_df_2021['Q25'].map(salary2021)
money2019=responses_df_2019['Q10'].dropna()
money2020=responses_df_2020['Q24'].dropna()
money2021=responses_df_2021['Q25'].dropna()

In [ ]:
fig=px.pie(money2019,money2019.values,hole=0.6,title='2019 Salary Distribution in data field in Taiwan')
fig.update_traces(textinfo='percent+label')
fig.update_layout(uniformtext_minsize=10, uniformtext_mode='hide')
fig.show()

In [ ]:
fig=px.pie(money2020,money2020.values,hole=0.6,title='2020 Salary Distribution in data field in Taiwan')
fig.update_traces(textinfo='percent+label')
fig.update_layout(uniformtext_minsize=10, uniformtext_mode='hide')
fig.show()

In [ ]:
fig=px.pie(money2021,money2021.values,hole=0.6,title='2021 Salary Distribution in data field in Taiwan')
fig.update_traces(textinfo='percent+label')
fig.update_layout(uniformtext_minsize=10, uniformtext_mode='hide')
fig.show()

* 在台灣，一份正職工作年薪10000美元以下的不合常理，所以我將他們去除了。
* 將年薪10000美元以下的人去除後，2019年到2021年薪資在30,000-39,999區間的都是眾數
* In Taiwan, a full-time job with an annual salary of less than US10,000 is unreasonable, so I removed them.
* After removing people with an annual salary of less than US10,000, the salary range of 30,000-39,999 from 2019 to 2021 is the majority

In [ ]:
print('2019年',money2019.shape[0],'人中平均薪資為：',money2019.mean())
print('2020年',money2020.shape[0],'人中平均薪資為：',money2020.mean())
print('2021年',money2021.shape[0],'人中平均薪資為：',money2021.mean())

# Position

In [ ]:
Role=pd.DataFrame()
Role['2021']=pd.DataFrame(survey_df_2021['Q5'].value_counts())
Role['2020']=pd.DataFrame(survey_df_2020['Q5'].value_counts())
Role['2019']=pd.DataFrame(survey_df_2019['Q5'].value_counts())
Role=Role.stack().reset_index()

In [ ]:
plt.figure(figsize=(10,10))
plt.title('2019-2021 Position Changes',fontsize=30)
sns.barplot(data=Role,y='level_0',x=0,hue='level_1',palette='Blues_r')

* Students and Data Analysts are getting more and more.

# Industry

In [ ]:
IndustryALL=ALLsurvey['Q20'].dropna()
IndustryTW=responses_df_2021['Q20'].dropna()

In [ ]:
fig=px.pie(IndustryALL,IndustryALL.values,color=IndustryALL.values,hole=0.4,title='Global Industry Distribution in data field')
fig.update_traces(textinfo='percent+label')
fig.update_layout(uniformtext_minsize=10, uniformtext_mode='hide')
fig.show()

In [ ]:
fig=px.pie(IndustryTW,IndustryTW.values,hole=0.4,title='Taiwan Industry Distribution in data field')
fig.update_traces(textinfo='percent+label')
fig.update_layout(uniformtext_minsize=7, uniformtext_mode='hide')
fig.show()

* 在全球和台灣的產業比較當中，前兩名都是科技業與教育業，而台灣的第三名為製造業，這可以依據台灣是以代工出口為主的關係，而金融方面台灣只有5.5%，我相信這個數字會逐漸上升，金融領域與數據分析領域碰撞，相信會蹦出新火花來！
* In the comparison of global and Taiwan’s industries, the top two are technology and education industries.
* The third in Taiwan is manufacturing. Because it relies on OEM export so much in Taiwan.
* Financial industry in Taiwan is only 5.5% now, I believe this number will gradually rise, data and finance will combine perfectly.

# Between Taiwan and All World

In [ ]:
ALLsurvey['Q25']=ALLsurvey['Q25'].map(salary2021)

TWQ5=responses_df_2021.groupby('Q5')['Q25'].mean().sort_values(ascending=False).dropna()
GBQ5=ALLsurvey.groupby('Q5')['Q25'].mean().sort_values(ascending=False).dropna()

px.bar(TWQ5,title='Salary each Position in Taiwan')

In [ ]:
px.bar(GBQ5,title='Salary each Position ALL WORLD')

In [ ]:
diff=(GBQ5/TWQ5).dropna().sort_values()
px.bar(diff,title='Salary Proportion Each Position between Taiwan and ALL WORLD')

In [ ]:
TWQ20=responses_df_2021.groupby('Q20')['Q25'].mean().sort_values(ascending=False)
GBQ20=ALLsurvey.groupby('Q20')['Q25'].mean().sort_values(ascending=False)
px.bar(x=TWQ20.index,y=TWQ20.values,title='Salary each industry in Taiwan')

In [ ]:
px.bar(x=GBQ20.index,y=GBQ20.values,title='Salary each industry ALL WORLD')

In [ ]:
Q20diff=(GBQ20/TWQ20).sort_values()
px.bar(Q20diff,title='Salary Proportion Each Industry between Taiwan and ALL WORLD')

# Salary Difference
* 我們可以發現不管是從職位或者是產業的角度下去觀察，薪水大部分都會落差有1.4~2.9倍之多，令人感到難過...
* We can find that whether it is from the perspective of position or industry, most of the salary gap will be 1.4~2.9 times, which makes me feel sad...

In [ ]:
px.pie(responses_df_2021,'Q23',hole=0.5,title='In Taiwan,how is your company ML situation?')

In [ ]:
px.pie(ALLsurvey,'Q23',hole=0.5,title='ALL WORLD,how is your company ML situation?')

# Company ML situation
* 我們可以發現有部署機器模型的公司是佔10.7與12.2，差距並不大
* 在使用機器學習產生見解方面就有明顯差異，分別為21.3%與16.8%，台灣明顯有了落後，我認為很多產業不一定需要部署機器學習模型，但是藉由機器學習影響公司營運方向是未來趨勢，也就是我們說的Data-Driven。
* We can find that companies that have deployed machine models account for 10.7 and 12.2, and the gap is not large
* There is a significant difference in the use of machine learning to generate insights, 21.3% and 16.8% respectively. Taiwan is clearly lagging behind. I think that many industries do not necessarily need to deploy machine learning models, but it is the future to use machine learning to influence company operations.Which is what we call Data-Driven

In [ ]:
columns=['Q40_Part_1','Q40_Part_2','Q40_Part_3','Q40_Part_4','Q40_Part_5','Q40_Part_6','Q40_Part_7',
        'Q40_Part_8','Q40_Part_9','Q40_Part_10','Q40_Part_11','Q40_OTHER']

Q40=ALLsurvey[columns]
x=pd.DataFrame()
for i in columns:
    y=Q40[i].value_counts()
    x=x.append(y)

Q40=x.stack().reset_index().iloc[:,1:]
recols={'level_1':'Course',0:'Counts'}
Q40=Q40.rename(columns=(recols))
Q40=Q40.set_index('Course')

In [ ]:
plt.figure(figsize=(10,10))
plt.title('(ALL WORLD)On which platforms have you begun or completed data science courses?',fontsize=20)
sns.barplot(y=Q40.index,x=Q40['Counts'],palette='Greens_r',order=Q40['Counts'].sort_values(ascending=False).index)

In [ ]:
TWQ40=responses_df_2021[columns]

x=pd.DataFrame()
for i in columns:
    y=TWQ40[i].value_counts()
    x=x.append(y)

TWQ40=x.stack().reset_index().iloc[:,1:]
recols={'level_1':'Course',0:'Counts'}
TWQ40=TWQ40.rename(columns=(recols))
TWQ40=TWQ40.set_index('Course')

plt.figure(figsize=(10,10))
plt.title('(In Taiwan),On which platforms have you begun or completed data science courses?')
sns.barplot(y=TWQ40.index,x=TWQ40['Counts'],palette='Greens_r',order=TWQ40['Counts'].sort_values(ascending=False).index)

In [ ]:
learn=pd.DataFrame()
learn['Course']=Q40.index
learn['Taiwan']=(TWQ40['Counts']/333).values
learn['AllWorld']=(Q40['Counts']/25973).values
px.line(learn,x='Course',y=['Taiwan','AllWorld'],title='Percentage of people learning from which platform')

# Learning Online
* 透過學校學習數據科學的人只有約20%，代表著越來越多人使用線上課程來學習，線上學習因為疫情影響，已經加速了她的發展趨勢，相信會有越來越多領域能夠透過線上課程來進行學習。
* Only about 20% of the people who learn data science through school means that more and more people use online courses to learn. Because of the impact of the epidemic, online learning has accelerated her development trend. I believe there will be more and more fields through Online courses to learn.

# Another version for salary comparision and dashboard
https://www.kaggle.com/k589k589/salary-comparision-mandarin-english