In [22]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['train_V2.csv', 'test_V2.csv', 'sample_submission_V2.csv']

In [23]:
data = pd.read_csv('../input/train_V2.csv')

In [24]:
data = data.loc[:,'assists':]
data.head()

   assists  boosts      ...       winPoints  winPlacePerc
0        0       0      ...            1466        0.4444
1        0       0      ...               0        0.6400
2        1       0      ...               0        0.7755
3        0       0      ...               0        0.1667
4        0       0      ...               0        0.1875

[5 rows x 26 columns]

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data.loc[:,'matchType'] = le.fit_transform(data.loc[:,'matchType'])

In [26]:
data.head()

   assists  boosts      ...       winPoints  winPlacePerc
0        0       0      ...            1466        0.4444
1        0       0      ...               0        0.6400
2        1       0      ...               0        0.7755
3        0       0      ...               0        0.1667
4        0       0      ...               0        0.1875

[5 rows x 26 columns]

In [27]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features = [12])

In [28]:
data = data.dropna()
data = ohe.fit_transform(data).toarray()

/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

In [29]:
data

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 1.466e+03,
        4.444e-01],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 5.000e+00, 0.000e+00,
        6.400e-01],
       [0.000e+00, 0.000e+00, 1.000e+00, ..., 2.000e+00, 0.000e+00,
        7.755e-01],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 4.000e+00, 0.000e+00,
        4.815e-01],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 8.000e+00, 0.000e+00,
        8.000e-01],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 5.000e+00, 0.000e+00,
        5.464e-01]])

In [30]:
data = pd.DataFrame(data)
data.head()

    0    1    2    3    4    5    ...     35   36       37   38      39      40
0  0.0  0.0  0.0  0.0  0.0  0.0   ...    0.0  0.0   244.80  1.0  1466.0  0.4444
1  0.0  0.0  0.0  0.0  0.0  0.0   ...    0.0  0.0  1434.00  5.0     0.0  0.6400
2  0.0  0.0  1.0  0.0  0.0  0.0   ...    0.0  0.0   161.80  2.0     0.0  0.7755
3  0.0  0.0  0.0  0.0  0.0  0.0   ...    0.0  0.0   202.70  3.0     0.0  0.1667
4  0.0  0.0  0.0  0.0  0.0  0.0   ...    0.0  0.0    49.75  2.0     0.0  0.1875

[5 rows x 41 columns]

In [31]:
data = data.iloc[:,1:]
data = data.iloc[:500000,:] #Try iterating here, check for different number of training examples 
data.head()

    1    2    3    4    5    6    ...     35   36       37   38      39      40
0  0.0  0.0  0.0  0.0  0.0  0.0   ...    0.0  0.0   244.80  1.0  1466.0  0.4444
1  0.0  0.0  0.0  0.0  0.0  0.0   ...    0.0  0.0  1434.00  5.0     0.0  0.6400
2  0.0  1.0  0.0  0.0  0.0  0.0   ...    0.0  0.0   161.80  2.0     0.0  0.7755
3  0.0  0.0  0.0  0.0  0.0  0.0   ...    0.0  0.0   202.70  3.0     0.0  0.1667
4  0.0  0.0  0.0  0.0  0.0  0.0   ...    0.0  0.0    49.75  2.0     0.0  0.1875

[5 rows x 40 columns]

In [32]:
X_train  = data.iloc[:,:-1]
y_train = data.iloc[:,-1]

In [33]:
X_train.head()

    1    2    3    4    5    6    ...       34   35   36       37   38      39
0  0.0  0.0  0.0  0.0  0.0  0.0   ...     0.00  0.0  0.0   244.80  1.0  1466.0
1  0.0  0.0  0.0  0.0  0.0  0.0   ...    11.04  0.0  0.0  1434.00  5.0     0.0
2  0.0  1.0  0.0  0.0  0.0  0.0   ...     0.00  0.0  0.0   161.80  2.0     0.0
3  0.0  0.0  0.0  0.0  0.0  0.0   ...     0.00  0.0  0.0   202.70  3.0     0.0
4  0.0  0.0  0.0  0.0  0.0  0.0   ...     0.00  0.0  0.0    49.75  2.0     0.0

[5 rows x 39 columns]

In [34]:
y_train

0         0.4444
1         0.6400
2         0.7755
3         0.1667
4         0.1875
5         0.0370
6         0.0000
7         0.7368
8         0.3704
9         0.2143
10        0.3929
11        0.4043
12        0.9286
13        0.8750
14        0.9000
15        0.2766
16        0.7308
17        0.8211
18        0.1923
19        0.9310
20        0.6383
21        0.2143
22        0.7500
23        0.9592
24        0.9231
25        0.8696
26        0.1154
27        0.7234
28        0.9630
29        0.0000
           ...
499970    0.9583
499971    0.8222
499972    0.1786
499973    0.5385
499974    0.3804
499975    0.8723
499976    0.2340
499977    0.1443
499978    0.9787
499979    0.5806
499980    0.0357
499981    0.8519
499982    0.9333
499983    0.1333
499984    0.1224
499985    0.2340
499986    0.0385
499987    0.8864
499988    0.8148
499989    0.3571
499990    0.3077
499991    0.9130
499992    0.1429
499993    0.2143
499994    0.4231
499995    0.0370
499996    0.8929
499997    0.8148
499998    0.2174
499999    0.6154
Name: 40, Length: 500000, dtype: float64

In [35]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=70)  
regressor.fit(X_train, y_train)  
regressor.score(X_train, y_train)

0.9892293403867108

In [36]:
#from xgboost import XGBRegressor

#XGBModel = XGBRegressor()
#XGBModel.fit(X_train, y_train, verbose=False)
#XGBModel.score(X_train, y_train)
# Gives 89.95% score

In [37]:
X_test = pd.read_csv('../input/test_V2.csv')

In [38]:
X_test1 = pd.read_csv('../input/test_V2.csv')
X_test1.dropna()
X_test1.head()

               Id         groupId    ...     weaponsAcquired  winPoints
0  9329eb41e215eb  676b23c24e70d6    ...                   1          0
1  639bd0dcd7bda8  430933124148dd    ...                   6          0
2  63d5c8ef8dfe91  0b45f5db20ba99    ...                   4          0
3  cf5b81422591d1  b7497dbdc77f4a    ...                   3          0
4  ee6a295187ba21  6604ce20a1d230    ...                   4          0

[5 rows x 28 columns]

In [39]:
def make_submission(prediction, subject_name):
    my_submission = pd.DataFrame({'Id':X_test1.Id,'winPlacePerc':prediction})
    my_submission.to_csv('{}'.format(subject_name),index=False)
    print('Submission file has been made')
    
X_test.head()

               Id         groupId    ...     weaponsAcquired  winPoints
0  9329eb41e215eb  676b23c24e70d6    ...                   1          0
1  639bd0dcd7bda8  430933124148dd    ...                   6          0
2  63d5c8ef8dfe91  0b45f5db20ba99    ...                   4          0
3  cf5b81422591d1  b7497dbdc77f4a    ...                   3          0
4  ee6a295187ba21  6604ce20a1d230    ...                   4          0

[5 rows x 28 columns]

In [40]:
X_test = X_test.loc[:,'assists':]
le2 = LabelEncoder()
X_test.loc[:,'matchType'] = le2.fit_transform(X_test.loc[:,'matchType'])
ohe2 = OneHotEncoder(categorical_features = [12])
X_test = X_test.dropna()
X_test = ohe2.fit_transform(X_test).toarray()
X_test = pd.DataFrame(X_test)
X_test = X_test.iloc[:,1:]
X_test.head()

/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

    1    2    3    4    5    6    7  ...    33   34   35   36      37   38   39
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   588.0  1.0  0.0
1  0.0  0.0  1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0  2017.0  6.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   787.8  4.0  0.0
3  0.0  0.0  1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0  1812.0  3.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0  2963.0  4.0  0.0

[5 rows x 39 columns]

In [41]:
predictions = regressor.predict(X_test)
predictions

array([0.21472286, 0.89870762, 0.73260571, ..., 0.88583429, 0.84004857,
       0.06355   ])

In [42]:
make_submission(predictions,'SiddharthSRandomForest2.csv')

Submission file has been made