In [ ]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import random
import matplotlib.pyplot as plt
%matplotlib inline
import plotly.graph_objs as go
import plotly.offline as pyo
import plotly.figure_factory as ff
import plotly.express as px
from plotly import tools
from plotly.subplots import make_subplots
from plotly.offline import iplot
from IPython import display

In [ ]:
from IPython.core.display import HTML
def multi_table(table_list):
    ''' Acceps a list of IpyTable objects and returns a table which contains each IpyTable in a cell
    '''
    return HTML(
        '<table><tr style="background-color:white;">' + 
        ''.join(['<td>' + table._repr_html_() + '</td>' for table in table_list]) +
        '</tr></table>')

<h1 style="color:#fce444;font-size:45px;font-family:Georgia;text-align:center;"><strong>Analysis <strong style="color:black;font-size:40px;font-family:Georgia;">Of <strong style="color:#fce444;font-size:40px;font-family:Georgia;">"Kaggle Survey 2021" <strong style="color:black;font-size:45px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Description of <strong style="color:black;font-size:25px;font-family:Georgia;">The <strong style="color:#fce444;font-size:25px;font-family:Georgia;">"Challenge" <strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

> Welcome to Kaggle's annual Machine Learning and Data Science Survey competition!

>The challenge objective: tell a data story about a subset of the data science community represented in this survey, through a combination of both narrative text and data exploration. A “story” could be defined any number of ways, and that’s deliberate. The challenge is to deeply explore (through data) the impact, priorities, or concerns of a specific group of data science and machine learning practitioners. That group can be defined in the macro (for example: anyone who does most of their coding in Python) or the micro (for example: female data science students studying machine learning in masters programs). This is an opportunity to be creative and tell the story of a community you identify with or are passionate about!

<img src="https://d.newsweek.com/en/full/1868100/what-if-watcher.png" width="800px">

<h6 style="color:#fce444;font-size:26px;font-family:Georgia;text-align:center;"><strong>"I am The Watcher. I am your guide through these vast new realities. <strong style="color:black;font-size:21px;font-family:Georgia;">Follow me and dare to face the unknown,and ponder the question... What if? <strong style="color:#fce444;font-size:21px;font-family:Georgia;">"I observe all that transpires here. And I do not, can not, will not interfere." <strong style="color:black;font-size:26px;font-family:Georgia;"> </strong></strong></strong></strong></h6>

<h6 style="color:#fce444;font-size:26px;font-family:Georgia;text-align:center;"><strong> <strong style="color:black;font-size:21px;font-family:Georgia;">I am the Watcher. I can see all situations and the lives of all people in every universe. Today I will share with you the story of the students who are pursuing their Senior Secondary education in AVENGERS high school in India. The headmaster of the school  NICK FURY, gave a task to his students to analyze Kaggle survey 2021, most of the students are new to all these data analysis, data exploration, etc. So, NICK FURY decided to help them out in this task, he decided to give them a start by explaining all 42 questions asked in the survey <strong style="color:#fce444;font-size:21px;font-family:Georgia;"> <strong style="color:black;font-size:26px;font-family:Georgia;"> </strong></strong></strong></strong></h6>

<h6 style="color:#fce444;font-size:13px;font-family:Georgia;text-align:center;"><strong> <strong style="color:black;font-size:13px;font-family:Georgia;">Names of students in the class are: Captain America, Iron Man, Thor, Black Panther, Loki, Hulk,Spider Man, Hawk Eye, Ant Man, Doctor Strange,Star-Lord, Sam, Bucky, Black widow, Wanda, Pepper Potts, Gamora, Peggy Carter, Nebula,All the students are from different countries<strong style="color:#fce444;font-size:13px;font-family:Georgia;"> <strong style="color:black;font-size:13px;font-family:Georgia;"> </strong></strong></strong></strong></h6>

<img src="https://static0.srcdn.com/wordpress/wp-content/uploads/2019/07/Spider-Man-Far-From-Home-Nick-Fury-Maria-Hill.jpg" width="800px">

<h6 style="color:#fce444;font-size:26px;font-family:Georgia;text-align:center;"><strong> <strong style="color:black;font-size:21px;font-family:Georgia;">NICK FURY started explaining all questions asked in the survey and students started to write their observation from his explanation<strong style="color:#fce444;font-size:21px;font-family:Georgia;"> <strong style="color:black;font-size:26px;font-family:Georgia;"> </strong></strong></strong></strong></h6>

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Loading <strong style="color:black;font-size:25px;font-family:Georgia;">Dataset <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

In [ ]:
df_2018 = pd.read_csv('../input/kaggle-survey-2018/multipleChoiceResponses.csv')
df_2018 = df_2018[1:]
df_2019 = pd.read_csv('../input/kaggle-survey-2019/multiple_choice_responses.csv')
df_2019 = df_2019[1:]
df_2020 = pd.read_csv('../input/kaggle-survey-2020/kaggle_survey_2020_responses.csv')
df_2020 = df_2020[1:]

In [ ]:
df1 = pd.read_csv('../input/kaggle-survey-2021/kaggle_survey_2021_responses.csv')
df1

In [ ]:
df = df1[1:]

In [ ]:
print('Number of responses given to survey/rows in dataframe:', df.shape[0])
print('Number of columns of dataframe',df.shape[1])

<strong> In the survey a total of 42 questions have been asked lets look into them </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 1: <strong style="color:black;font-size:25px;font-family:Georgia;">What is your age (# years)? <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q1'].value_counts().values.tolist(), 
                      x = df['Q1'].value_counts().index, 
                      text=df['Q1'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      name = 'Age of People',
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'cornflowerblue',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q1'].value_counts().keys(),
                             values=df['Q1'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,
                     name = 'Age of People')), row = 1, col = 2)
fig.update_layout(title={'text': 'Age of People',
                         'y':0.9,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},
                  template='plotly_white')
fig.update_yaxes(range=[0,6000])
iplot(fig)

#### observation:
1. Well..!!! I can see <strong> 14526 </strong> people out of <strong> 25973 </strong> people are in <strong> age group 18-29 </strong>, This shows that more younge are involved in this kaggle survey. Most of the people involved in the survey are of age group <strong> 25-29(4931) </strong>, followed by age group <strong> 18-21(4901) only 30 lessthan people of age group 25-29</strong>,followed by age group <strong> 22-24(4901) </strong>.

2. Except for top 3 age groups, as age increasing number of people decreasing.

3. There are a total of <strong> 2237 </strong> of age group 50-70+. This shows that a good number of old people are also invloved in the survey.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 2: <strong style="color:black;font-size:25px;font-family:Georgia;">What is your gender? <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q2'].value_counts().values.tolist(), 
                      x = df['Q2'].value_counts().index, 
                      text=df['Q2'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'deeppink',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q2'].value_counts().keys(),
                             values=df['Q2'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,
                     )), row = 1, col = 2)
fig.update_layout(title={'text': 'Gender of People',
                         'y':0.9,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},
                  template='plotly_white')
fig.update_yaxes(range=[0,22000])
iplot(fig)

### observation:

1. UFFFFFF...!!! Morethan <strong> 79%(20598)</strong> people invloved in the survey are <strong> Man </strong>. It is very baised because it is like unbalanced data and it will not help the community if the same trend is followed in the long run, next most populated gender is <strong> woman(4890) </strong> but they are only <strong> 18.8% </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 3: <strong style="color:black;font-size:25px;font-family:Georgia;">In which country do you currently reside? <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
import plotly.offline as py
py.offline.init_notebook_mode()

def plot_in_map(locations,counts,title):
    data = [ dict(
            type = 'choropleth',
            locations = locations,
            z = counts,
            locationmode = 'country names',
            autocolorscale = True,
            marker = dict(
                line = dict(color = 'rgb(58,100,69)', width = 0.6)),
                colorbar = dict(autotick = True, tickprefix = '', title = '# of Kagglers')
                )
           ]
    layout = dict(
        title = title,
        geo = dict(
            showframe = True,
            showcoastlines = True,
            projection = dict(
            type = 'equirectangular'
            ),
        margin = dict(b = 0, t = 0, l = 0, r = 0)
                ),
        )

    fig = dict(data=data, layout=layout)
    
    py.iplot(fig, validate=False, filename='world-map')
z = df['Q3'].value_counts()
plot_in_map(locations=z.index,
            counts=z.values,
            title='Participants by Country')

#### Observation:
1. Wowwww..!! more than people from 60 different countries are the part of kaggle community, It shows how big is this platform and we can also say this is a data ocean where different rivers(people from different countries) comes inside it. It will also increase the communication of people from different countries.

2. Indians involved most in this survey with <strong> 7434 </strong> people and they are very actively giving their contribution to the kaggle community.

3. People from USA are more next to Indians with 2650 in number.

4. In top 5 countries there are 3 countries from asia: <strong> India, china, Japan.</strong> This shows asians are contributing more to the kaggle.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 4: <strong style="color:black;font-size:25px;font-family:Georgia;">What is the highest level of formal education that you have attained or plan to attain within the next 2 years? <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q4'].value_counts().values.tolist(), 
                      x = df['Q4'].value_counts().index, 
                      text=df['Q4'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'yellow',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q4'].value_counts().keys(),
                             values=df['Q4'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Degree of People',
                         'y':1.0,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width=1000,
    height=1000,
                  template='plotly_white')
fig.update_yaxes(range=[0,22000])
iplot(fig)

#### Observation:

1. Most of the people did masters's degree or willing to do masters's degree in next two years and also many students did bachelor's degree.

2. We already know the fact that people between age <strong> 18-29 </strong> are more, so it is very often that maximum people in that age will do bachelor's or master's degree and there are people without bachelor's degree but less in number.

3. One intresting thing is that some people with no formal education are on Kaggle.. Thats pretty good..!!!!

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 5: <strong style="color:black;font-size:25px;font-family:Georgia;">Select the title most similar to your current role (or most recent title if retired)? <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q5'].value_counts().values.tolist(), 
                      x = df['Q5'].value_counts().index, 
                      text=df['Q5'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = '#FFE399',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q5'].value_counts().keys(),
                             values=df['Q5'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Profession of People',
                         'y':0.9,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1300,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,7200])
iplot(fig)

#### Observation:
1. WAAAHH...!!! Most of the People in kaggle are Students(includig me). It is pretty obvious that students have more time to do this stuff.

2. Data scientists stood at 2nd place

3. One intresting fact is that Software Engineers are more than Data analysts, machine learning engineers, data engineers

4. Developers are very less as we know both the domains are quite different but some are doing Kaggle as their daily hobby..!! That's good..!!

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 6: <strong style="color:black;font-size:25px;font-family:Georgia;">For how many years have you been writing code and/or programming? <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q6'].value_counts().values.tolist(), 
                      x = df['Q6'].value_counts().index, 
                      text=df['Q6'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      name = 'Coding Experience of People',
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = '#0891EF',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q6'].value_counts().keys(),
                             values=df['Q6'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,
                     name = 'Coding Experience of People')), row = 1, col = 2)
fig.update_layout(title={'text': 'Coding Experience of People',
                         'y':1,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,8200])
iplot(fig)

#### Observation:

1. <strong> 30.3% (7874) </strong> of people have coding experience <strong> 1-3 years </strong> followed by <strong> 22.6% (5881) </strong> having coding experience <strong> less than 1 year </strong> while there are <strong> 15.6% (4061) </strong> of people have coding experience <strong> 3-5 years </strong>.

2. There are good number of people who has coding experience <strong> greather than 5 years </strong>
    
3. OHHHH..!!! There are few people who are never been into coding, It signifies that people who have no experience can also survive in this field.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 7: <strong style="color:black;font-size:25px;font-family:Georgia;">What programming languages do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q7_Part_1', 'Q7_Part_2', 'Q7_Part_3','Q7_Part_4',
                       'Q7_Part_5', 'Q7_Part_6', 'Q7_Part_7', 'Q7_Part_8', 'Q7_Part_9',
                       'Q7_Part_10', 'Q7_Part_11', 'Q7_Part_12', 'Q7_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = b, 
                      x = a, 
                      text=b,
              textfont=dict(size=15),
                      name = 'Programming Language used on Regular Basis',
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = '#FF00E0',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=a,
                             values=b,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,
                     name = 'Programming Language used on Regular Basis')), row = 1, col = 2)
fig.update_layout(title={'text': 'Programming Language used on Regular Basis',
                         'y':1,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1200,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,22500])
iplot(fig)

#### Observation:

1. It is pretty known that people will use python more and followed by SQL(since we can do queries with sql which is very important..!!!)
2. C++ and R is also used by many people
3. R can explain statistics of the data deeper than python...!!
4. Swift is used by less people..!!
5. I'm pretty confused that some people not using any language may be they have a habit of reading the notebooks and learn..!!!

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 8: <strong style="color:black;font-size:25px;font-family:Georgia;">What programming language would you recommend an aspiring data scientist to learn first?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q8'].value_counts().values.tolist(), 
                      x = df['Q8'].value_counts().index, 
                      text=df['Q8'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'yellowgreen',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q8'].value_counts().keys(),
                             values=df['Q8'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Mostly Recommended Language For Aspiring Data Scientist',
                         'y':0.9,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,21000])
iplot(fig)

#### Observation:

1. Many of them suggested to learn python first and yes it was a very good opinion by most of them.
2. In my opnion python and sql are most important languages to learn first for an aspiring data scientist.
3. After python R is choosed mostly next and yes it is a powerful language.
4. Swift is recommended by less number of people

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 9: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following integrated development environments (IDE's) do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q9_Part_1', 'Q9_Part_2', 'Q9_Part_3', 'Q9_Part_4', 'Q9_Part_5',
       'Q9_Part_6', 'Q9_Part_7', 'Q9_Part_8', 'Q9_Part_9', 'Q9_Part_10',
       'Q9_Part_11', 'Q9_Part_12', 'Q9_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'orange',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='IDEs used on regular basis',
                   xaxis = dict(title='IDEs name'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,17200])
iplot(fig)

#### Observation:

1. Most of the people are using Jupyter Notebook mainly because it is has cells so we can execute our codes line by line.
2. Visual Studio code is at second, Pycharm at third
3. People who use R language are pretty good in number so they are using RStudio.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 10: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following hosted notebook products do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q10_Part_1', 'Q10_Part_2',
       'Q10_Part_3', 'Q10_Part_4', 'Q10_Part_5', 'Q10_Part_6',
       'Q10_Part_7', 'Q10_Part_8', 'Q10_Part_9', 'Q10_Part_10',
       'Q10_Part_11', 'Q10_Part_12', 'Q10_Part_13', 'Q10_Part_14',
       'Q10_Part_15', 'Q10_Part_16', 'Q10_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'red',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Notebooks used on regular basis',
                   xaxis = dict(title='Notebbok name'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,11000])
iplot(fig)

#### Observation:

1. OHHHHH..!!! there are only 3 Notebooks above 2000 votes and their votes are greather than 9500.
2. Most of the people are using Colab Notebooks on regular basis.
3. Kaggle Notebook stands is second place but not much difference
4. Suprisingly the 3rd most opted option is None may be they are using jupyter notebook I think since it is not mentioned in the options
5. Observable Notebooks stands in last place

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 11: <strong style="color:black;font-size:25px;font-family:Georgia;">What type of computing platform do you use most often for your data science projects?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q11'].value_counts().values.tolist(), 
                      x = df['Q11'].value_counts().index, 
                      text=df['Q11'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = '#0891EF',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q11'].value_counts().keys(),
                             values=df['Q11'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Most used Computing Platform',
                         'y':0.9,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,17000])
iplot(fig)

#### Observation:

1. OHHH..!!! Most of the people are doing their projects in their laptop and a good number of people are using personal computer/ Desktop
2. Very less number of people are using A deep learning workstation
3. One thing I got here is that many people are beginners or started their learning recently. So, a laptop is enough to finish their work and since it was a kaggale survey every one who does work on kaggle at most use laptop..!!

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 12: <strong style="color:black;font-size:25px;font-family:Georgia;">Which types of specialized hardware do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q12_Part_1',
       'Q12_Part_2', 'Q12_Part_3', 'Q12_Part_4', 'Q12_Part_5',
       'Q12_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = b, 
                      x = a, 
                      text=b,
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'gold',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=a,
                             values=b,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True)), row = 1, col = 2)
fig.update_layout(title={'text': 'Specialized Hardware used on Regular Basis',
                         'y':1,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,15000])
iplot(fig)

#### Observation:
1. OHHH..!!!! we can see that many people are not using any specialized hardwares, as above we saw that many people are having a laptop and many laptops wont have any GPUs.
2. NIVIDIA GPUs is used most among all GPUs.
3. Out Of all Hardwares mentioned above,AWS Trainium Chips and AWS Inferentia Chips are used by less people

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 13: <strong style="color:black;font-size:25px;font-family:Georgia;">Approximately how many times have you used a TPU (tensor processing unit)?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q13'].value_counts().values.tolist(), 
                      x = df['Q13'].value_counts().index, 
                      text=df['Q13'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'darkcyan',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q13'].value_counts().keys(),
                             values=df['Q13'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'TPU Usage Count',
                         'y':0.9,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,17500])
iplot(fig)

#### Observation:
1. We can see that many have never used TPU till now, It seems that many of them not aware of this and dont know what a TPU does..
2. There are only 612 people out of 23k people who have used TPU morethan 25 times

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 14: <strong style="color:black;font-size:25px;font-family:Georgia;"> What data visualization libraries or tools do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q14_Part_1', 'Q14_Part_2', 'Q14_Part_3',
       'Q14_Part_4', 'Q14_Part_5', 'Q14_Part_6', 'Q14_Part_7',
       'Q14_Part_8', 'Q14_Part_9', 'Q14_Part_10', 'Q14_Part_11',
       'Q14_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'lavender',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Data Visulaisation Libraries used on regular basis',
                   xaxis = dict(title='Libraries Name'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,19000])
iplot(fig)

#### Observation:

1. It seems that this question is a multiple option choosable question..!!
2. Matplotlib library is using by many people. It is pretty obivous that for plotting matplotlib is very necessary and it is the first visualisation library that is introduced to everyone..!!
3. The next 3 popular libraries used are Seaborn,plotly/plotly express and Ggplot/ ggplot2
4. Among the options less opted option/library is Altair..!

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 15: <strong style="color:black;font-size:25px;font-family:Georgia;">  For how many years have you used machine learning methods?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q15'].value_counts().values.tolist(), 
                      x = df['Q15'].value_counts().index, 
                      text=df['Q15'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'cyan',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q15'].value_counts().keys(),
                             values=df['Q15'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Machine Learning Methods',
                         'y':0.9,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,10000])
iplot(fig)

#### Observation:
1. Many people are using ML methods since less than a year, this means many are new to this subject and interest of people towards this subject is increasing these days(from less than a year)
2. Only 2% people are using these methods from 10-20 or morethan 20+ years..
3. Pretty surprisingly 3rd most opted option/choicee is "I do not use machine learning methods". May be they are intrested only in reading the notebooks..!!

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 16: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following machine learning frameworks do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q16_Part_1', 'Q16_Part_2', 'Q16_Part_3',
       'Q16_Part_4', 'Q16_Part_5', 'Q16_Part_6', 'Q16_Part_7',
       'Q16_Part_8', 'Q16_Part_9', 'Q16_Part_10', 'Q16_Part_11',
       'Q16_Part_12', 'Q16_Part_13', 'Q16_Part_14', 'Q16_Part_15',
       'Q16_Part_16', 'Q16_Part_17', 'Q16_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'coral',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Machine Learning Frameworks used on regular basis',
                   xaxis = dict(title='Machine Learning Frameworks'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,15000])
iplot(fig)

#### Observation:

1. This question is multi option choosing one.
2. Most of the people opted Scikit-learn and it is pretty obivious that we saw above most of them are beginners, beginners mainly work on ML alogorithms and all basic ML algos will available in Sikit-learn, not only beginners even experts use atleast once in their projects.
3. TensorFlow, Keras and PyTorch stands in 2,3,4 places respectively..!!!
4. Least used Framework is Caret

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 17: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following machine learning Algorithms do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q17_Part_1',
       'Q17_Part_2', 'Q17_Part_3', 'Q17_Part_4', 'Q17_Part_5',
       'Q17_Part_6', 'Q17_Part_7', 'Q17_Part_8', 'Q17_Part_9',
       'Q17_Part_10', 'Q17_Part_11', 'Q17_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'darksalmon',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Machine Learning Algorithms used on regular basis',
                   xaxis = dict(title='Machine Learning Algorithms'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,15000])
iplot(fig)

#### Observation:

1. This is a multi option choosable question
2. Most of the people are using Linear or Logistic Regression on regular basis, yes everyone of us will try linear regression algorithm first if the problem is regression one.
3. Decision Trees or Random Forests stands in second place
4. Option choosed my least number of people is "other".
5. In the given options least number of people choosed Evolutionary Approaches Algorithms(only 963 people)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 18: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following computer vision methods do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q18_Part_1',
       'Q18_Part_2', 'Q18_Part_3', 'Q18_Part_4', 'Q18_Part_5',
       'Q18_Part_6', 'Q18_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'cornsilk',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Computer Vision Methods used on regular basis',
                   xaxis = dict(title='Computer Vision Methods'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,6000])
iplot(fig)

# Observation:

1. Most of the people are using Image classification and other general purpose networks (VGG, Inception, ResNet, ResNeXt, NASNet, EfficientNet, etc this computer vision method on regular basis.
2. Good thing is every option is almost balanced here no bias that means all methods which are available in computer methods are using regularly by people who want to use..!!!

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 19: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following natural language processing (NLP) methods do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q19_Part_1', 'Q19_Part_2',
       'Q19_Part_3', 'Q19_Part_4', 'Q19_Part_5', 'Q19_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = b, 
                      x = a, 
                      text=b,
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'burlywood',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=a,
                             values=b,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True)), row = 1, col = 2)
fig.update_layout(title={'text': 'NLP Methods used on Regular Basis',
                         'y':1,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,3500])
iplot(fig)

#### Observation:

1. Most of the people are using Word embeddings/vectors (GLoVe, fastText, word2vec) NLP method on regular basis..!! and if you want to know word embeddings library/method used to find which categorical value repeated most in that particular column..!!!
2. Transformer language models (GPT-3, BERT, XLnet, etc) NLP model stands in second place
3. Least number of people are using Contextualized embeddings (ELMo, CoVe) NLP method..!!

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 20: <strong style="color:black;font-size:25px;font-family:Georgia;">In what industry is your current employer/contract (or your most recent employer if retired)?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q20'].value_counts().values.tolist(), 
                      x = df['Q20'].value_counts().index, 
                      text=df['Q20'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'grey',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q20'].value_counts().keys(),
                             values=df['Q20'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Current Employement',
                         'y':1,
                         'x':0.4,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1400,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,4600])
iplot(fig)

#### Observation:

1. 25% of the people are from computers/Technology contract
2. 19.7% of people are from Academics/Education, so all the students comes into this category
3. 9% of people are from Accounting/Finance
4. Very less number of people are from Hospitality/Entertainment/Sports, Military/Security/Defense only 1%

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 21: <strong style="color:black;font-size:25px;font-family:Georgia;"> What is the size of the company where you are employed?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q21'].value_counts().values.tolist(), 
                      x = df['Q21'].value_counts().index, 
                      text=df['Q21'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'lime',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q21'].value_counts().keys(),
                             values=df['Q21'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Number of People',
                         'y':1,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,5500])
iplot(fig)

#### Observation:

1. 31.1% of people are working in company of size 0-50 employees which is highest among all
2. 21% of the people are working in company of size 10,000+ employees
3. 18.8% of the people are working in company of size 1000-9999 employees
4. 15.8% of the people are working in company of size 50-249 employees
5. 13.3% of thr people are working in company of size 250-999 employees which is least among all

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 22: <strong style="color:black;font-size:25px;font-family:Georgia;"> Approximately how many individuals are responsible for data science workloads at your place of business?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q22'].value_counts().values.tolist(), 
                      x = df['Q22'].value_counts().index, 
                      text=df['Q22'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'mediumpurple',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q22'].value_counts().keys(),
                             values=df['Q22'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Employees Responsible for Data Science Role',
                         'y':1,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,4000])
iplot(fig)

#### Observation:

1. 22.6% of people are working in a company where 1-2 people are responsible for data science workloads which is highest
2. 22.3% of people are working in a company where 20+ people are responsible for data science workloads
3. 2.61% of people are working in a company where 15-19 people are responsible for data science workloads which is lowest
4. 19% of people are working in a company where no employee is responsible for data science workload this is intresting as many companies are not using data science
5. Another Interesting fact is, If we observe top 2 percentages of employees having data science workloads we can see that either the company has only 1 or 2 employees responsible for data science workload oe they are having morethan 20+ employees responsible for data science workload

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 23: <strong style="color:black;font-size:25px;font-family:Georgia;"> Does your current employer incorporate machine learning methods into their business?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q23'].value_counts().values.tolist(), 
                      x = df['Q23'].value_counts().index, 
                      text=df['Q23'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'navy',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q23'].value_counts().keys(),
                             values=df['Q23'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Machine Learning Methods into their Business',
                         'y':1,
                         'x':0.4,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1200,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,4000])
iplot(fig)

#### Observation:

1. 21.3% of employees stated that they are exploring to use ML methods and may put into production in their business which is highest among all
2. 20.5% of employees stated that they are not using any ML methods in their business.
3. 17% of employees stated that they don't know whether they use or not
4. 10.7% of employees stated that they only used ML methods to generate insights but not put working models into production which is lowest among all
5. Combinely 30.6% of employees stated that they are using ML methods frrom 0-4 years in their business production

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 24: <strong style="color:black;font-size:25px;font-family:Georgia;"> Select any activities that make up an important part of your role at work<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q24_Part_1', 'Q24_Part_2', 'Q24_Part_3',
       'Q24_Part_4', 'Q24_Part_5', 'Q24_Part_6', 'Q24_Part_7',
       'Q24_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'chocolate',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Activities that make important role at work',
                   xaxis = dict(title='Activities'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,11000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 25: <strong style="color:black;font-size:25px;font-family:Georgia;"> What is your current yearly compensation (approximate USD)?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q25'].value_counts().values.tolist(), 
                      x = df['Q25'].value_counts().index, 
                      text=df['Q25'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'mediumpurple',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q25'].value_counts().keys(),
                             values=df['Q25'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Yearly Compensation of Employees',
                         'y':1,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1600,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,3800])
iplot(fig)

#### Observation:

1. 21.9% of people are earning 0-999 USD per year highest among all
2. 6.3% people are earning 1,000-1999 USD per year
3. Only 0.208% people are earning 500,000-999,999 USD per year which is lowest among all

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 26: <strong style="color:black;font-size:25px;font-family:Georgia;">  Approximately how much money have you (or your team) spent on machine learning and/or cloud computing services at home (or at work) in the past 5 years (approximate USD)..?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q26'].value_counts().values.tolist(), 
                      x = df['Q26'].value_counts().index, 
                      text=df['Q26'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'wheat',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q26'].value_counts().keys(),
                             values=df['Q26'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Money Spent on ML or Cloud Computing Services',
                         'y':1,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,6600])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 27 Part A: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following cloud computing platforms do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q27_A_Part_1', 'Q27_A_Part_2',
       'Q27_A_Part_3', 'Q27_A_Part_4', 'Q27_A_Part_5', 'Q27_A_Part_6',
       'Q27_A_Part_7', 'Q27_A_Part_8', 'Q27_A_Part_9', 'Q27_A_Part_10',
       'Q27_A_Part_11', 'Q27_A_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'cyan',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Cloud Computing Platforms used on regular basis',
                   xaxis = dict(title='Cloud Computing Platforms'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,5000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 27 Part B: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following cloud computing platforms do you hope to become more familiar with in the next 2 years?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q27_B_Part_1', 'Q27_B_Part_2',
       'Q27_B_Part_3', 'Q27_B_Part_4', 'Q27_B_Part_5', 'Q27_B_Part_6',
       'Q27_B_Part_7', 'Q27_B_Part_8', 'Q27_B_Part_9', 'Q27_B_Part_10',
       'Q27_B_Part_11', 'Q27_B_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'khaki',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Cloud Computing Platforms do you hope to familiar within next two years',
                   xaxis = dict(title='Cloud Computing Platforms'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,8500])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 28: <strong style="color:black;font-size:25px;font-family:Georgia;">Of the cloud platforms that you are familiar with, which has the best developer experience (most enjoyable to use)?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q28'].value_counts().values.tolist(), 
                      x = df['Q28'].value_counts().index, 
                      text=df['Q28'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'snow',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q28'].value_counts().keys(),
                             values=df['Q28'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Cloud Platforms With Best Developer Experience',
                         'y':1,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1400,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,1000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 29 Part A: <strong style="color:black;font-size:25px;font-family:Georgia;">Do you use any of the following cloud computing products on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q29_A_Part_1',
       'Q29_A_Part_2', 'Q29_A_Part_3', 'Q29_A_Part_4', 'Q29_A_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = b, 
                      x = a, 
                      text=b,
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'lightblue',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=a,
                             values=b,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True)), row = 1, col = 2)
fig.update_layout(title={'text': 'Cloud Computing Products used on Regular Basis',
                         'y':1,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,2700])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 29 Part B: <strong style="color:black;font-size:25px;font-family:Georgia;">In the next 2 years, do you hope to become more familiar with any of these specific cloud computing products?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q29_B_Part_1',
       'Q29_B_Part_2', 'Q29_B_Part_3', 'Q29_B_Part_4', 'Q29_B_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = b, 
                      x = a, 
                      text=b,
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'mintcream',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=a,
                             values=b,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True)), row = 1, col = 2)
fig.update_layout(title={'text': 'Cloud Computing Products used on Regular Basis',
                         'y':1,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,8000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 30 Part A: <strong style="color:black;font-size:25px;font-family:Georgia;">In the next 2 years, do you hope to become more familiar with any of these specific cloud computing products?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q30_A_Part_1', 'Q30_A_Part_2', 'Q30_A_Part_3', 'Q30_A_Part_4',
       'Q30_A_Part_5', 'Q30_A_Part_6', 'Q30_A_Part_7', 'Q30_A_OTHER',]
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'red',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Storage Products used on regular basis',
                   xaxis = dict(title='Storage Products'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,3000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 31 Part A: <strong style="color:black;font-size:25px;font-family:Georgia;">Do you use any of the following managed machine learning products on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q31_A_Part_1', 'Q31_A_Part_2', 'Q31_A_Part_3', 'Q31_A_Part_4',
       'Q31_A_Part_5', 'Q31_A_Part_6', 'Q31_A_Part_7', 'Q31_A_Part_8',
       'Q31_A_Part_9', 'Q31_A_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'green',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Machine Learning Products used on regular basis',
                   xaxis = dict(title='Machine Learning Products'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,7000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 31 Part B: <strong style="color:black;font-size:25px;font-family:Georgia;"> In the next 2 years, do you hope to become more familiar with any of these managed machine learning products?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q31_B_Part_1', 'Q31_B_Part_2', 'Q31_B_Part_3', 'Q31_B_Part_4',
       'Q31_B_Part_5', 'Q31_B_Part_6', 'Q31_B_Part_7', 'Q31_B_Part_8',
       'Q31_B_Part_9', 'Q31_B_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'lightcyan',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Machine Learning Products hope to familiar with them in next 2 years',
                   xaxis = dict(title='Machine Learning Products'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,6800])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 32 Part A: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following big data products (relational databases, data warehouses, data lakes, or similar) do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q32_A_Part_1', 'Q32_A_Part_2',
       'Q32_A_Part_3', 'Q32_A_Part_4', 'Q32_A_Part_5', 'Q32_A_Part_6',
       'Q32_A_Part_7', 'Q32_A_Part_8', 'Q32_A_Part_9', 'Q32_A_Part_10',
       'Q32_A_Part_11', 'Q32_A_Part_12', 'Q32_A_Part_13', 'Q32_A_Part_14',
       'Q32_A_Part_15', 'Q32_A_Part_16', 'Q32_A_Part_17', 'Q32_A_Part_18',
       'Q32_A_Part_19', 'Q32_A_Part_20', 'Q32_A_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'gold',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Big data Products used on regular basis',
                   xaxis = dict(title='Big data Products'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,4000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 32 Part B: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following big data products (relational databases, data warehouses, data lakes, or similar) do you hope to become more familiar with in the next 2 years?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q32_B_Part_1', 'Q32_B_Part_2',
       'Q32_B_Part_3', 'Q32_B_Part_4', 'Q32_B_Part_5', 'Q32_B_Part_6',
       'Q32_B_Part_7', 'Q32_B_Part_8', 'Q32_B_Part_9', 'Q32_B_Part_10',
       'Q32_B_Part_11', 'Q32_B_Part_12', 'Q32_B_Part_13', 'Q32_B_Part_14',
       'Q32_B_Part_15', 'Q32_B_Part_16', 'Q32_B_Part_17', 'Q32_B_Part_18',
       'Q32_B_Part_19', 'Q32_B_Part_20', 'Q32_B_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'violet',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Big data Products hope to familiar with them in next 2 years',
                   xaxis = dict(title='Big data Products'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,6700])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 33: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following big data products (relational databases, data warehouses, data lakes, or similar) do you hope to become more familiar with in the next 2 years?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
data = [go.Bar(x=df['Q33'].value_counts().keys(),
               y=df['Q33'].value_counts(),
               text =round(df['Q33'].value_counts(),2),
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'tan',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Data Products Used most Often',
                   xaxis = dict(title='Data Products Name'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,1500])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 34 Part A: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following business intelligence tools do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q34_A_Part_1', 'Q34_A_Part_2', 'Q34_A_Part_3', 'Q34_A_Part_4',
       'Q34_A_Part_5', 'Q34_A_Part_6', 'Q34_A_Part_7', 'Q34_A_Part_8',
       'Q34_A_Part_9', 'Q34_A_Part_10', 'Q34_A_Part_11', 'Q34_A_Part_12',
       'Q34_A_Part_13', 'Q34_A_Part_14', 'Q34_A_Part_15', 'Q34_A_Part_16',
       'Q34_A_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'moccasin',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Business Intelligence tools used on regular basis',
                   xaxis = dict(title='Businees Intelligence Tools'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,4500])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 34 Part B: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following business intelligence tools do you hope to become more familiar with in the next 2 years?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q34_B_Part_1', 'Q34_B_Part_2', 'Q34_B_Part_3', 'Q34_B_Part_4',
       'Q34_B_Part_5', 'Q34_B_Part_6', 'Q34_B_Part_7', 'Q34_B_Part_8',
       'Q34_B_Part_9', 'Q34_B_Part_10', 'Q34_B_Part_11', 'Q34_B_Part_12',
       'Q34_B_Part_13', 'Q34_B_Part_14', 'Q34_B_Part_15', 'Q34_B_Part_16',
       'Q34_B_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'firebrick',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Business Intelligence tools hope to familiar within next 2 years',
                   xaxis = dict(title='Businees Intelligence Tools'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,6000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 35: <strong style="color:black;font-size:25px;font-family:Georgia;">Which of the following business intelligence tools do you use most often?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
data = [go.Bar(x=df['Q35'].value_counts().keys(),
               y=df['Q35'].value_counts(),
               text =round(df['Q35'].value_counts(),2),
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'teal',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Business Intelligent Tools used Most',
                   xaxis = dict(title='Businees Tools Names'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,1000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 36 Part A: <strong style="color:black;font-size:25px;font-family:Georgia;"> Do you use any automated machine learning tools (or partial AutoML tools) on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q36_A_Part_1', 'Q36_A_Part_2',
       'Q36_A_Part_3', 'Q36_A_Part_4', 'Q36_A_Part_5', 'Q36_A_Part_6',
       'Q36_A_Part_7', 'Q36_A_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'yellow',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Machine Learning tools used on regular basis',
                   xaxis = dict(title='Machine Learning Tools'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,7000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 36 Part B: <strong style="color:black;font-size:25px;font-family:Georgia;"> Which categories of automated machine learning tools (or partial AutoML tools) do you hope to become more familiar with in the next 2 years?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q36_B_Part_1', 'Q36_B_Part_2',
       'Q36_B_Part_3', 'Q36_B_Part_4', 'Q36_B_Part_5', 'Q36_B_Part_6',
       'Q36_B_Part_7', 'Q36_B_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'indianred',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Machine Learning tools hope to familiar with them within next 2 years',
                   xaxis = dict(title='Machine Learning Tools'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,7000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 37 Part A: <strong style="color:black;font-size:25px;font-family:Georgia;"> Which of the following automated machine learning tools (or partial AutoML tools) do you use on a regular basis?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q37_A_Part_1', 'Q37_A_Part_2',
       'Q37_A_Part_3', 'Q37_A_Part_4', 'Q37_A_Part_5', 'Q37_A_Part_6',
       'Q37_A_Part_7', 'Q37_A_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'darkcyan',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Auto Machine Learning tools used on regular basis',
                   xaxis = dict(title='Auto Machine Learning Tools'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,1500])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 37 Part B: <strong style="color:black;font-size:25px;font-family:Georgia;"> Which specific automated machine learning tools (or partial AutoML tools) do you hope to become more familiar with in the next 2 years?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q37_B_Part_1', 'Q37_B_Part_2',
       'Q37_B_Part_3', 'Q37_B_Part_4', 'Q37_B_Part_5', 'Q37_B_Part_6',
       'Q37_B_Part_7', 'Q37_B_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'indianred',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Auto Machine Learning tools hope to familiar with them within next 2 years',
                   xaxis = dict(title='Auto Machine Learning Tools'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,5500])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 38 Part A: <strong style="color:black;font-size:25px;font-family:Georgia;"> Do you use any tools to help manage machine learning experiments?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q38_A_Part_1', 'Q38_A_Part_2',
       'Q38_A_Part_3', 'Q38_A_Part_4', 'Q38_A_Part_5', 'Q38_A_Part_6',
       'Q38_A_Part_7', 'Q38_A_Part_8', 'Q38_A_Part_9', 'Q38_A_Part_10',
       'Q38_A_Part_11', 'Q38_A_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'darkseagreen',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Machine Learning Experimrnt tools used to manage work',
                   xaxis = dict(title='Machine Learning Experiment Tools'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,6500])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 38 Part B: <strong style="color:black;font-size:25px;font-family:Georgia;"> In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q38_B_Part_1', 'Q38_B_Part_2',
       'Q38_B_Part_3', 'Q38_B_Part_4', 'Q38_B_Part_5', 'Q38_B_Part_6',
       'Q38_B_Part_7', 'Q38_B_Part_8', 'Q38_B_Part_9', 'Q38_B_Part_10',
       'Q38_B_Part_11', 'Q38_B_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

In [ ]:
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'indianred',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Machine Learning Experiment tools hope to familiar with them within next 2 years',
                   xaxis = dict(title='Machine Learning Experimeny Tools'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,5000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 39: <strong style="color:black;font-size:25px;font-family:Georgia;"> Where do you publicly share your data analysis or machine learning applications?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q39_Part_1', 'Q39_Part_2',
       'Q39_Part_3', 'Q39_Part_4', 'Q39_Part_5', 'Q39_Part_6',
       'Q39_Part_7', 'Q39_Part_8', 'Q39_Part_9', 'Q39_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])

data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'bisque',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Publicly share your data analysis or machine learning applications',
                   xaxis = dict(title='Public Aplications'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,5000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 40: <strong style="color:black;font-size:25px;font-family:Georgia;">On which platforms have you begun or completed data science courses?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q40_Part_1', 'Q40_Part_2', 'Q40_Part_3', 'Q40_Part_4',
       'Q40_Part_5', 'Q40_Part_6', 'Q40_Part_7', 'Q40_Part_8',
       'Q40_Part_9', 'Q40_Part_10', 'Q40_Part_11', 'Q40_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])
    
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'indigo',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Platform name where you begun or completed data science course',
                   xaxis = dict(title='Platform Name'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,12000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 41: <strong style="color:black;font-size:25px;font-family:Georgia;">What is the primary tool that you use at work or school to analyze data?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
fig = make_subplots(rows=1,cols=2,
                    subplot_titles=('Countplot',
                                    'Percentages'),
                    specs=[[{"type": "xy"},
                            {'type':'domain'}]])
fig.add_trace(go.Bar(y = df['Q41'].value_counts().values.tolist(), 
                      x = df['Q41'].value_counts().index, 
                      text=df['Q41'].value_counts().values.tolist(),
              textfont=dict(size=15),
                      textposition = 'outside',
                      showlegend=False,
              marker = dict(color = 'gainsboro',
                            line_color = 'black',
                            line_width=3)),row = 1,col = 1)
fig.add_trace((go.Pie(labels=df['Q41'].value_counts().keys(),
                             values=df['Q41'].value_counts().values,textfont = dict(size = 16),
                     textposition='auto',
                     showlegend = True,)), row = 1, col = 2)
fig.update_layout(title={'text': 'Primary Tool used most to work at school/home',
                         'y':1,
                         'x':0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},width = 1000,height = 600,
                  template='plotly_white')
fig.update_yaxes(range=[0,8000])
iplot(fig)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong>✏️Question 42: <strong style="color:black;font-size:25px;font-family:Georgia;">Who/what are your favorite media sources that report on data science topics?<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
col = ['Q42_Part_1', 'Q42_Part_2', 'Q42_Part_3', 'Q42_Part_4',
       'Q42_Part_5', 'Q42_Part_6', 'Q42_Part_7', 'Q42_Part_8',
       'Q42_Part_9', 'Q42_Part_10', 'Q42_Part_11', 'Q42_OTHER']
a = []
for i in col:
    a.append(df[i].value_counts().keys()[0])
b = []
for i in col:
    b.append(df[i].value_counts().iloc[0])
    
data = [go.Bar(x=a,y= b,text = b,
              textposition= 'outside',
              width=[0.7, 0.7],
              marker = dict(color = 'dimgrey',
                            line_color = 'black',
                            line_width=3))]

layout = go.Layout(title='Favourite Sociaal Media to report a data science topics',
                   xaxis = dict(title='Social media'),
                   width=800,
                   height=600,
                   template = 'plotly_white')

fig=go.Figure(data=data, layout=layout)
fig.update_yaxes(range=[0,13000])
iplot(fig)

<h3 style="color:red;font-size:13px;font-family:Georgia;text-align:center;"><strong> Final Observation of the students after NICK FURY completed explaining them all the 42 questions in the survey is(Top 2 options picked from all the questions):<strong style="color:black;font-size:13px;font-family:Georgia;"><p>1. What is your age?: 25-29(4931), 18-21(4901)</p><p> 2. What is your gender?: Man(20598), Woman (4890)</p><p> 3. In which country do you currently reside?: India(7434), USA(2650)</p><p> 4. What is the highest level of formal education that you have attained or plan to attain within the next 2 years?: Master's degree(10132), Bachelor's degree(9907)</p><p> 5. Select the title most similar to your current role (or most recent title if retired)?: Student(6804), Data Scientist(3616)</p><p> 6. For how many years have you been writing code and/or programming?: 1-3 years (7874), lessthan 1 year (5881)</p><p> 7.What programming languages do you use on a regular basis?: Python(21860), SQL(10756)</p><p> 8. What programming language would you recommend an aspiring data scientist to learn first?:Python (20213), R (1445), SQL (1338)</p><p> 9. Which of the following integrated development environments (IDE's) do you use on a regular basis?: Jupyter Notebook (16233), VS Code (10040)</p><p> 10. Which of the following hosted notebook products do you use on a regular basis?: Colab Notebooks (9792), Kaggle Notebooks (9507),None(7174)</p><p> 11. What type of computing platform do you use most often for your data science projects?: A laptop (16231), A personal Computer/Desktop (4916)</p><p> 12. Which types of specialized hardware do you use on a regular basis?: None(13234), NIVIDIA GPUs (8036)</p><p> 13. Approximately how many times have you used a TPU (tensor processing unit)?: Never (16457), 2-5 times (3405)</p><p> 14.What data visualization libraries or tools do you use on a regular basis?: Matplotlib (17595), Seaborn (12586)</p><p> 15. For how many years have you used machine learning methods?: Under 1 year (9163), 1-2 years (4675)</p><p> 16. Which of the following machine learning frameworks do you use on a regular basis?: Scikit-learn (13987), Tensor-Flow (9371)</p><p> 17. Which of the following ML algorithms do you use on a regular basis?: Linear or Logistic Regression (13852), Decision Trees or Random Forests (11863)</p><p> 18. Which categories of computer vision methods do you use on a regular basis?: Image classification and other general purpose networks (VGG, Inception, ResNet, ResNeXt, NASNet, EfficientNet, etc)(4373), Image segmentation methods (U-Net, Mask R-CNN, etc) (2740)</p><p> 19. Which of the following natural language processing (NLP) methods do you use on a regular basis?:
    Word embeddings/vectors (GLoVe, fastText, word2vec) (2643), Transformer language models (GPT-3, BERT, XLnet, etc) (2351)</p><p> 20. In what industry is your current employer/contract (or your most recent employer if retired)?: Computers/ Technology (4079), Acadeemics/Education (3214)</p><p> 21. What is the size of the company where you are employed?: 0-49 employees (5055), 10,000 or more employees (3416)</p><p> 22. Approximately how many individuals are responsible for data science workloads at your place of business?: 1-2 (3642), 20+ (3595)</p><p> 23. Does your current employer incorporate machine learning methods into their business?: We are exploring ML methods (and may one day put a model into production) (3390), No (we do not use ML methods)(3263)</p><p> 24. Select any activities that make up an important part of your role at work?: Analyze and understand data to influence product or business decisions(9108) , Build prototypes to explore applying machine learning to new areas (5150)</p><p> 25. What is your current yearly compensation (approximate USD)?: 0-999 USD (3369), 1,000-1999 USD (969)</p><p> 26. Approximately how much money have you (or your team) spent on machine learning and/or cloud computing services at home (or at work) in the past 5 years (approximate USD)..?: 0 USD (5903), 100-999 (2534)</p><p> 27 Part A. Which of the following cloud computing platforms do you use on a regular basis?: Amazon Web Services(AWS) (3721), Google Cloud Platform (GCP) (3142)</p><p> 27 Part B. Which of the following cloud computing platforms do you hope to become more familiar with in the next 2 years?: Amazon Web Services(AWS) (7494), Google Cloud Platform (GCP) (7484)</p><p> 28. Of the cloud platforms that you are familiar with, which has the best developer experience (most enjoyable to use)?: Amazon Web Services(AWS) (836), Google Cloud Platform (GCP) (738)</p><p> 29 Part A. Do you use any of the following cloud computing products on a regular basis?: Amazon Elastic Compute Cloud (EC2)(2270), Google Cloud Compute Engine (1960)</p><p> 29 Part B. In the next 2 years, do you hope to become more familiar with any of these specific cloud computing products?: Google Cloud Compute Engine(7497), Microsoft Azure Virtual Machines(5973)</p><p> 30 Part A. Do you use any of the following data storage products on a regular basis?: Amazon Simple Storage Service (S3)(2308), Google Cloud Storage (GCS) (1950)</p><p> 31 Part A. In the next 2 years, do you hope to become more familiar with any of these specific data storage products?: No/None (6381), Amazon SageMaker (991)</p><p> 31 Part B: In the next 2 years, do you hope to become more familiar with any of these managed machine learning products?: Google Cloud Vetex AI (5304), Azure Machine Learning Studio (5029)</p><p> 32 Part A. Which of the following big data products (relational databases, data warehouses, data lakes, or similar) do you use on a regular basis?: My Sql (3576), None (2297)</p><p> 32 Part B. Which of the following big data products (relational databases, data warehouses, data lakes, or similar) do you hope to become more familiar with in the next 2 years?: MySql (6135), MongoDB (4288)</p><p> 33. Which of the following big data products (relational database, data warehouse, data lake, or similar) do you use most often?: MySql (1110), Postgre SQL (694)</p><p> 34 Part A. Which of the following business intelligence tools do you use on a regular basis?: None (4123), Tableau (2464) </p><p> 34 Part B. Which of the following business intelligence tools do you hope to become more familiar with in the next 2 years?: Tableau (5421), Microsoft PowerBI (4923)</p><p> 35. Which of the following business intelligence tools do you use most often?: Microsoft PowerBi (790), Tableau (740)</p><p> 36 Part A. Do you use any automated machine learning tools (or partial AutoML tools) on a regular basis?: No/None 6338, Automated model selection (e.g. auto-sklearn, xcessiv) (1186)</p><p> 36 Part B. Which categories of automated machine learning tools (or partial AutoML tools) do you hope to become more familiar with in the next 2 years?: Automated model selection (e.g. auto-sklearn, xcessiv) (4761), Automation of full ML pipelines (e.g. Google Cloud AutoML, H2O Driverless AI) (4752) </p><p> 37 Part A. Which of the following automated machine learning tools (or partial AutoML tools) do you use on a regular basis?: No/None (1196), Google Cloud AutoML (751)</p><p> 37 Part B. Which specific automated machine learning tools (or partial AutoML tools) do you hope to become more familiar with in the next 2 years?: Google Cloud AutoML (4817), Azure Automated Machine Learning (3152) </p><p> 38 Part A. Do you use any tools to help manage machine learning experiments?: No/None (6239), TensorBoard (1726) </p><p> 38 Part B: In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments?: None (4542), TensorBoard (4249) </p> <p> 39. Where do you publicly share your data analysis or machine learning applications?: GitHub (4586), I do not share my work publicly (3167) </p> <p> 40. On which platforms have you begun or completed data science courses?: Coursera (9649), Kaggle Learn Courses (8670)</p><p> 41. What is the primary tool that you use at work or school to analyze data?: Basic statistical software (Microsoft Excel, Google Sheets, etc.) (7246), Local development environments (RStudio, JupyterLab, etc.) (7170)</p><p> 42. Who/what are your favorite media sources that report on data science topics?: Kaggle (notebooks, forums, etc)(11373), YouTube (Kaggle YouTube, Cloud AI Adventures, etc) (10401)</p>  <strong style="color:#fce444;font-size:13px;font-family:Georgia;"> <strong style="color:black;font-size:26px;font-family:Georgia;"> </strong></strong></strong></strong></h3>

<h6 style="color:#fce444;font-size:26px;font-family:Georgia;text-align:center;"><strong> <strong style="color:black;font-size:21px;font-family:Georgia;">NICK FURY was ok with observation made by the students and he had enough confidence and trust on the students that they will complete the task. So, he left all the students alone in the room, insisted them to proceed on the survey analysis...!!<strong style="color:#fce444;font-size:21px;font-family:Georgia;"> <strong style="color:black;font-size:26px;font-family:Georgia;"> </strong></strong></strong></strong></h6>

<img src="https://static01.nyt.com/images/2019/05/05/arts/05avengers-writers7/merlin_153837675_4394eb10-a2eb-43c4-9734-c8aefa79901e-articleLarge.jpg" width="800px">

<h2 style="color:red;font-size:16px;font-family:Georgia;text-align:center;"><strong><p>Students started to think so that they may get any question to analyze. Meanwhile, black widow observed there is a huge difference in invlovement of Men and women in the survey, only 19% are women, whereas 80% were man. Some of the questions raised by girl students are:</p> <strong style="color:black;font-size:13px;font-family:Georgia;"> <p> 1. Getting a job related to data science is possible for woman??</p> <p> 2. Nebula want to become a data Analyst with Bachelor's degree is it possible.??</p><p> 3. Wanda has no coding experience will she be able to get a job related to data science.??</p><p> 4. Black widow knows only R language will she be able to get a job related to data science?</p><p> 5. Pepper potts wants to have a doctoral degree and then want to get a job related to data science is it possible?</p><p> 6. Gamora want to do Masters and then get a job related to data science in USA is it possible?</p><p> 7. Peggy Carter knows only Python will she be able to get a job as data scientist in Austraila?</p><p>8. Does Woman above age 50 able to get a job in data science field?</p><p><p> Some additional Analysis they want to do on 2021 survey data:</p><p> 1. Employement and unemployement rate of woman</p><p> 2. Analysis of all age groups of womem</p><p> 3. Analysis of all degree groups of woman</p><p> 4. Analysis of women with respect to coding experience </p><p> 5. Analysis of women with respect to programming language used on regular basis</p><p> 6. Analysis of women with respect to income</p><p>7. Analysis of women with respect to Current Role<strong style="color:red;font-size:16px;font-family:Georgia;"> <strong style="color:red;font-size:16px;font-family:Georgia;"> </strong><p>Captain America instructed to take previous years survey data and analyze the questions asked by girls. Everyone started their analysis....</p></strong></strong></strong></h2>

In [ ]:
df_2018['Q1'].replace(['Male'],'Man',inplace = True)
df_2018['Q1'].replace(['Female'],'Woman',inplace = True)
df_2019['Q2'].replace(['Male'],'Man',inplace = True)
df_2019['Q2'].replace(['Female'],'Woman',inplace = True)
df_2020['Q2'].replace(['Male'],'Man',inplace = True)
df_2020['Q2'].replace(['Female'],'Woman',inplace = True)

In [ ]:
df_2018['Q4'].replace(['Masterâs degree'],"Master’s degree",inplace = True)
df_2019['Q4'].replace(['Masterâs degree'],"Master’s degree",inplace = True)
df_2020['Q4'].replace(['Masterâs degree'],"Master’s degree",inplace = True)

df_2018['Q4'].replace(['Bachelorâs degree'],"Bachelor’s degree",inplace = True)
df_2019['Q4'].replace(['Bachelorâs degree'],"Bachelor’s degree",inplace = True)
df_2020['Q4'].replace(['Bachelorâs degree'],"Bachelor’s degree",inplace = True)

df_2018['Q4'].replace(['Some college/university study without earning a bachelorâs degree'],"Some college/university study without earning a bachelor’s degree",inplace = True)
df_2019['Q4'].replace(['Some college/university study without earning a bachelorâs degree'],"Some college/university study without earning a bachelor’s degree",inplace = True)
df_2020['Q4'].replace(['Some college/university study without earning a bachelorâs degree'],"Some college/university study without earning a bachelor’s degree",inplace = True)

df_2018['Q4'].replace(['Professional degree'],"Professional doctorate",inplace = True)
df_2019['Q4'].replace(['Professional degree'],"Professional doctorate",inplace = True)
df_2020['Q4'].replace(['Professional degree'],"Professional doctorate",inplace = True)

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Analysis of Women in survey<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman in Survey across years<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
x = ['2018','2019','2020','2021']
y = [len(df_2018[df_2018['Q1'] == 'Woman']['Q1'].tolist()),len(df_2019[df_2019['Q2'] == 'Woman']['Q2'].tolist()),len(df_2020[df_2020['Q2'] == 'Woman']['Q2'].tolist()),len(df[df['Q2'] == 'Woman']['Q2'].tolist())]
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ('Woman Involved In survey',weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:
1. Good thing here is there is vast increase of number of women invloved in survey over the years. If this trend follows then, in upcoming years Man and Woman count in survey will be equal..!!!

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Employed Woman Across Years<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
x = ['2018','2019','2020','2021']
y = [len(df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q6'] != 'Not employed')]['Q1']),len(df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q5'] != 'Not employed')]['Q5']),len(df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q5'] != 'Currently not employed')]['Q5']),len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed')]['Q5'])]
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ('Employed Woman In survey',weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation

1. In the year <strong> 2021 </strong> highest number of <strong> employed women(4427) </strong> involved when compared to all other years
2. In <strong> 2018 </strong>there are many <strong> employed women(3829) </strong> involved in survey than in year <strong>2019,2020 </strong>.
3. In <strong> 2020 </strong> there are many <strong> employed women (3502) </strong> invloved in survey than in year <strong> 2019 (2998) </strong>.
4. Since there are many woman invloved in the survey during 2018 when compared 2019 and 2020. It is pretty obvious that the employed women count in 2018 will be greather than employed women count in 2019,2020 and same applies between 2018 and 2021.
5. There are almost 1000 employed women more invloved in 2021 when compared to 2020.
6. If we look at last 3 years there is almost a <strong> 1500 employed women were increased between 2018 and 2021</strong> and employed women are gradually increasing. So, may be in upcoming years we can see more employed woman invloving in both survey and job industry.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Unemployed Woman Across Years<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
x = ['2018','2019','2020','2021']
y = [len(df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q6'] == 'Not employed')]['Q1']),len(df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q5'] == 'Not employed')]['Q5']),len(df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q5'] == 'Currently not employed')]['Q5']),len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed')]['Q5'])]
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ('Unemployed Woman In survey',weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:

1. Count of unemployed women in the survey increased gradually from 2018 to 2021. This doesnot mean that unemployed women are increasing every year so it is a negative sign. This is actually a positive sign, I will explain why. This is the data of the survey, most of the people involved in the kaggle survey will also invlove in kaggle competitions, solving datasets, uploading notebooks or learning from others notebooks. The count of unemployed women increasing in the survey shows that people with/without knowledge are wanted to learn data science and get a job in this field or people with some knowledge in this field are willing to increase their knowledge through kaggle(Since it is the best platform to show case your skills and I feel personally we can learn a lot by seeing others work as well). So, unemployement is not a negative sign here as it helps in improvement in every individual and it also shows the willingness of the people to get the job.



2. One more thing is only around 50-150 unemployed women are increasing every year but around 500-1000 employed women are increasing every year and my prediction is more unemployed people invloving in the survey but there be also vast increasing in number of employed people invloving in the survey.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman Students Across Years<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
x = ['2018','2019','2020','2021']
y = [len(df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q6'] != 'Student')]['Q1']),len(df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q5'] != 'Student')]['Q5']),len(df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q5'] != 'Student')]['Q5']),len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Student')]['Q5'])]
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ('Woman Students In survey',weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:

1. In <strong> 2021(3316) </strong> more women invloved in the survey when compared to years <strong> 2018,2019 and 2020 </strong>.
2. When compared to <strong> 2018(2999) </strong>involvement of women in survey decreased in the years <strong>2019,2020 </strong>.
3. When compared to <strong> 2019(2448) </strong> involvement of women in survey increased in <strong> 2020(2633) </strong>.
4. From <strong> 2019 </strong>there is constant increase in women involvement in the survey

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman In Data Science related Jobs<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
a = ['Data Scientist','Data Analyst','Machine Learning Engineer',
     'Business Analyst','Data Engineer','Statistician',
     'DBA/Database Engineer','Marketing Analyst','Data Journalist']
c = 0
n = []
for i in df_2018[df_2018['Q1'] == 'Woman']['Q6']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2019[df_2019['Q2'] == 'Woman']['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2020[df_2020['Q2'] == 'Woman']['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df[df['Q2'] == 'Woman']['Q5']:
    if i in a:
        c += 1
n.append(c)
x = ['2018','2019','2020','2021']
y = n
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ('Woman in Jobs related to Data Science',weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:

1. In <strong> 2021(1632) </strong> more women are in jobs related to data science when compared to years <strong> 2018,2019 and 2020 </strong>.
2. In <strong> 2018(1464) </strong>more women are in jobs related to data science when compared to the years <strong>2019,2020 </strong>.
3. In <strong> 2019(1241) </strong> more women are in jobs related to data science when compared to <strong>2020 (1223)</strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman in Jobs related to Data Science vs Other Fields<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
# Displaying values at the top of the Grouped Bar Chart using plt.text()
plt.figure(figsize=(10,6))

# set width of bar
barWidth = 0.2
a = ['Data Scientist','Data Analyst','Machine Learning Engineer',
     'Business Analyst','Data Engineer','Statistician',
     'DBA/Database Engineer','Marketing Analyst','Data Journalist']
c = 0
n = []
for i in df_2018[df_2018['Q1'] == 'Woman']['Q6']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2019[df_2019['Q2'] == 'Woman']['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2020[df_2020['Q2'] == 'Woman']['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df[df['Q2'] == 'Woman']['Q5']:
    if i in a:
        c += 1
n.append(c)

n1 = []
c = 0
for i in df_2018[df_2018['Q1'] == 'Woman']['Q6']:
    if i not in a:
        c += 1
n1.append(c)
c = 0
for i in df_2019[df_2019['Q2'] == 'Woman']['Q5']:
    if i not in a:
        c += 1
n1.append(c)
c = 0
for i in df_2020[df_2020['Q2'] == 'Woman']['Q5']:
    if i not in a:
        c += 1
n1.append(c)
c = 0
for i in df[df['Q2'] == 'Woman']['Q5']:
    if i not in a:
        c += 1
n1.append(c)
x = ['2018','2019','2020','2021']
y1 = n
y2 = n1

pos1 = np.arange(len(y1))
pos2 = [x + barWidth for x in pos1]

# Make the plot
plt.bar(pos1, y1, color='#FBC02D', width=barWidth, label='data science field')
plt.bar(pos2, y2, color='#F57F17', width=barWidth, label='Other fields')

# Add xticks on the middle of the group bars
plt.xticks([i + barWidth for i in range(len(y1))], x,rotation=90,weight = 'bold')

for x,y in zip(pos1,y1):
    plt.text(x, y, '%d' % y, ha='center' , va= 'bottom')
    
for x,y in zip(pos2,y2):
    plt.text(x, y, '%d' % y, ha='center' , va= 'bottom')
    
plt.suptitle ('Woman in Jobs related to Data Science vs Other Fields',weight = 'bold')

# Create legend & Show graphic
plt.legend()
plt.show()

#### Observation:

1. In all years survey, women with jobs not related to data science are more when compared to women with jobs related to data science

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman with Bachelor's degree and working as a Data Analyst<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
n = []
n.append(len(df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q4'] == "Bachelor’s degree") & (df_2018['Q6'] == 'Data Analyst')]))
n.append(len(df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q4'] == "Bachelor’s degree") & (df_2019['Q5'] == 'Data Analyst')]))
n.append(len(df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q4'] == "Bachelor’s degree") & (df_2020['Q5'] == 'Data Analyst')]))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q4'] == "Bachelor’s degree") & (df['Q5'] == 'Data Analyst')]))

x = ['2018','2019','2020','2021']
y = n
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ("Woman with Bachelor's degree and working as a Data Analyst",weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:

1. In <strong> 2021(171) </strong> more women are with Bachelor's degree working as a Data Analyst when compared to years <strong> 2018,2019 and 2020 </strong>.
2. In <strong> 2018(124) </strong>more women are with Bachelor's degree working as a Data Analyst when compared to the years <strong>2019,2020 </strong>.
3. In <strong> 2020(110) </strong> more women are with Bachelor's degree working as a Data Analyst when compared to <strong>2019 (104)</strong>.


There is a significant increase of women working as a Data Analyst from 2018 to 2021. It will be a good choice if women with bachelor's degree choose their career as data analyst.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Employed Woman vs Unemployed Woman with Bachelor's degree<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
# Displaying values at the top of the Grouped Bar Chart using plt.text()
plt.figure(figsize=(10,6))

# set width of bar
barWidth = 0.2

n = []
n.append(len(df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q4'] == "Bachelor’s degree") & (df_2018['Q6'] != 'Not employed')]))
n.append(len(df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q4'] == "Bachelor’s degree") & (df_2019['Q5'] != 'Not employed')]))
n.append(len(df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q4'] == "Bachelor’s degree") & (df_2020['Q5'] != 'Currently not employed')]))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q4'] == "Bachelor’s degree") & (df['Q5'] != 'Currently not employed')]))

n1 = []

n1.append(len(df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q4'] == "Bachelor’s degree") & (df_2018['Q6'] == 'Not employed')]))
n1.append(len(df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q4'] == "Bachelor’s degree") & (df_2019['Q5'] == 'Not employed')]))
n1.append(len(df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q4'] == "Bachelor’s degree") & (df_2020['Q5'] == 'Currently not employed')]))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q4'] == "Bachelor’s degree") & (df['Q5'] == 'Currently not employed')]))


x = ['2018','2019','2020','2021']
y1 = n
y2 = n1

pos1 = np.arange(len(y1))
pos2 = [x + barWidth for x in pos1]

# Make the plot
plt.bar(pos1, y1, color='#FBC02D', width=barWidth, label='Employed')
plt.bar(pos2, y2, color='#F57F17', width=barWidth, label='Unemployed')

# Add xticks on the middle of the group bars
plt.xticks([i + barWidth for i in range(len(y1))], x,rotation=90,weight = 'bold')

for x,y in zip(pos1,y1):
    plt.text(x, y, '%d' % y, ha='center' , va= 'bottom')
    
for x,y in zip(pos2,y2):
    plt.text(x, y, '%d' % y, ha='center' , va= 'bottom')
    
plt.suptitle ("Woman with Bachelor's degree and Employed vs Not employed",weight = 'bold')

# Create legend & Show graphic
plt.legend()
plt.show()

#### Observation:

1. In every year employed women with Bachelor's degree are morethan unemployed women with Bachelor's degree

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman with No coding experience having a job in Data Science Field<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
a = ['Data Scientist','Data Analyst','Machine Learning Engineer',
     'Business Analyst','Data Engineer','Statistician',
     'DBA/Database Engineer','Marketing Analyst','Data Journalist']
c = 0
n = []
for i in df_2018[((df_2018['Q1'] == 'Woman') & (df_2018['Q24'] == 'I have never written code and I do not want to learn')) | ((df_2018['Q1'] == 'Woman') &(df_2018['Q24'] == 'I have never written code but I want to learn'))]['Q6']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q15'] == 'I have never written code')]['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q6'] == 'I have never written code')]['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df[(df['Q2'] == 'Woman') & (df['Q6'] == 'I have never written code')]['Q5']:
    if i in a:
        c += 1
n.append(c)
x = ['2018','2019','2020','2021']
y = n
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ('Woman with No coding experience getting a job in Data Science Field',weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:

1. we can see from 2018 to 2021 every year number of women getting jobs related to data science field is increasing rapidly.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman who knows only R and having a job in Data Science Field<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
a = ['Data Scientist','Data Analyst','Machine Learning Engineer',
     'Business Analyst','Data Engineer','Statistician',
     'DBA/Database Engineer','Marketing Analyst','Data Journalist']
c = 0
n = []
for i in df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q16_Part_2'] == 'R')]['Q6']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q18_Part_2'] == 'R')]['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q7_Part_2'] == 'R')]['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df[(df['Q2'] == 'Woman') & (df['Q7_Part_2'] == 'R')]['Q5']:
    if i in a:
        c += 1
n.append(c)
x = ['2018','2019','2020','2021']
y = n
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ('Woman who knows only R and having a job in Data Science Field',weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:

1. In <strong> 2018(672) </strong> more women knows only R and working having job related to data science when compared to years <strong> 2019,2020 and 2021 </strong>.
2. In <strong> 2021(495) </strong>more women knows only R and working having job related to data science when compared to the years <strong>2019,2020 </strong>.
3. In <strong> 2019(420) </strong> more women knows only R and working having job related to data science when compared to <strong>2020 (395)</strong>.


There is a significant decrease of women knows only R and working having job related to data science from 2018 to 2020 and increased in the 2021 but still lessthan 2018.

In [ ]:
# Displaying values at the top of the Grouped Bar Chart using plt.text()
plt.figure(figsize=(10,6))

# set width of bar
barWidth = 0.2

a = ['Data Scientist','Data Analyst','Machine Learning Engineer',
     'Business Analyst','Data Engineer','Statistician',
     'DBA/Database Engineer','Marketing Analyst','Data Journalist']
c = 0
n = []
for i in df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q16_Part_2'] == 'R')]['Q6']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q18_Part_2'] == 'R')]['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q7_Part_2'] == 'R')]['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df[(df['Q2'] == 'Woman') & (df['Q7_Part_2'] == 'R')]['Q5']:
    if i in a:
        c += 1
n.append(c)

c = 0
n1 = []
for i in df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q16_Part_2'] == 'R')]['Q6']:
    if i == 'Not employed':
        c += 1
n1.append(c)
c = 0
for i in df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q18_Part_2'] == 'R')]['Q5']:
    if i == 'Not employed':
        c += 1
n1.append(c)
c = 0
for i in df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q7_Part_2'] == 'R')]['Q5']:
    if i == 'Currently not employed':
        c += 1
n1.append(c)
c = 0
for i in df[(df['Q2'] == 'Woman') & (df['Q7_Part_2'] == 'R')]['Q5']:
    if i == 'Currently not employed':
        c += 1
n1.append(c)

x = ['2018','2019','2020','2021']
y1 = n
y2 = n1

pos1 = np.arange(len(y1))
pos2 = [x + barWidth for x in pos1]

# Make the plot
plt.bar(pos1, y1, color='#FBC02D', width=barWidth, label='Employed')
plt.bar(pos2, y2, color='#F57F17', width=barWidth, label='unemployed')

# Add xticks on the middle of the group bars
plt.xticks([i + barWidth for i in range(len(y1))], x,rotation=90,weight = 'bold')

for x,y in zip(pos1,y1):
    plt.text(x, y, '%d' % y, ha='center' , va= 'bottom')
    
for x,y in zip(pos2,y2):
    plt.text(x, y, '%d' % y, ha='center' , va= 'bottom')
    
plt.suptitle ("Woman who only knows R language Employed vs Not employed(Data Science Field)",weight = 'bold')

# Create legend & Show graphic
plt.legend()
plt.show()

#### Observation:

Employed women are significantly very high in very year when compared to unemployed women.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman with master degree and working as data science related jobs in USA<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
a = ['Data Scientist','Data Analyst','Machine Learning Engineer',
     'Business Analyst','Data Engineer','Statistician',
     'DBA/Database Engineer','Marketing Analyst','Data Journalist']
c = 0
n = []
for i in df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q4'] == 'Master’s degree') & (df_2018['Q3'] == 'United States of America')]['Q6']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q4'] == 'Master’s degree') & (df_2019['Q3'] == 'United States of America')]['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q4'] == 'Master’s degree') & (df_2020['Q3'] == 'United States of America')]['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df[(df['Q2'] == 'Woman') & (df['Q4'] == 'Master’s degree') & (df['Q3'] == 'United States of America')]['Q5']:
    if i in a:
        c += 1
n.append(c)
x = ['2018','2019','2020','2021']
y = n
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ('Woman with master degree and any job related to data science in United States of America',weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:

1. In <strong> 2018(288) </strong> more Woman with doctoral degree and having a job in Data Science Field when compared to years <strong> 2019,2020 and 2021 </strong>.
2. In <strong> 2019(171) </strong>more Woman with doctoral degree and having a job in Data Science Field when compared to the years <strong>2021,2020 </strong>.
3. In <strong> 2021(129) </strong> more Woman with doctoral degree and having a job in Data Science Field when compared to <strong>2020(114)</strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman with doctoral degree and having a job in Data Science Field<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
a = ['Data Scientist','Data Analyst','Machine Learning Engineer',
     'Business Analyst','Data Engineer','Statistician',
     'DBA/Database Engineer','Marketing Analyst','Data Journalist']
c = 0
n = []
for i in df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q4'] == 'Doctoral degree')]['Q6']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q4'] == 'Doctoral degree')]['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q4'] == 'Doctoral degree')]['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df[(df['Q2'] == 'Woman') & (df['Q4'] == 'Doctoral degree')]['Q5']:
    if i in a:
        c += 1
n.append(c)
x = ['2018','2019','2020','2021']
y = n
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ('Woman with doctoral degree and having a job in Data Science Field',weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:

1. In <strong> 2018(203) </strong> more Woman with doctoral degree and having a job in Data Science Field when compared to years <strong> 2019,2020 and 2021 </strong>.
2. In <strong> 2021(193) </strong>more Woman with doctoral degree and having a job in Data Science Field when compared to the years <strong>2019,2020 </strong>.
3. In <strong> 2019(186) </strong> more Woman with doctoral degree and having a job in Data Science Field when compared to <strong>2020(159)</strong>.


There is a significant decrease of Woman with doctoral degree and having a job in Data Science Field from 2018 to 2020 and increased in the 2021 but still lessthan 2018(not with much difference).

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman with master degree and working as data scientist in Australia<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
n = []
n.append(len(df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q4'] == 'Master’s degree') & (df_2018['Q6'] == 'Data Scientist') & (df_2018['Q3'] == 'Australia')]))
n.append(len(df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q4'] == 'Master’s degree') & (df_2019['Q5'] == 'Data Scientist') & (df_2019['Q3'] == 'Australia')]))
n.append(len(df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q4'] == 'Master’s degree') & (df_2020['Q5'] == 'Data Scientist') & (df_2020['Q3'] == 'Australia')]))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q4'] == 'Master’s degree') & (df['Q5'] == 'Data Scientist') & (df['Q3'] == 'Australia')]))

x = ['2018','2019','2020','2021']
y = n
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ("Woman with Maters degree and working as a Data Scientist in Australia",weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:

1. In <strong> 2019,2021(5) </strong> more Woman with Maters degree and working as a Data Scientist in Australia when compared to years <strong> 2018,2020 </strong>.
2. In <strong> 2018(3) </strong>more Woman with Maters degree and working as a Data Scientist in Australia when compared to the years <strong>2020(2)</strong>.

In [ ]:
df[(df['Q2'] == 'Woman') & (df['Q3'] == 'Australia')]['Q5'].value_counts()

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman with master degree and any job related to data science in Australia<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
a = ['Data Scientist','Data Analyst','Machine Learning Engineer',
     'Business Analyst','Data Engineer','Statistician',
     'DBA/Database Engineer','Marketing Analyst','Data Journalist']
c = 0
n = []
for i in df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q4'] == 'Master’s degree') & (df_2018['Q3'] == 'Australia')]['Q6']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q4'] == 'Master’s degree') & (df_2019['Q3'] == 'Australia')]['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q4'] == 'Master’s degree') & (df_2020['Q3'] == 'Australia')]['Q5']:
    if i in a:
        c += 1
n.append(c)
c = 0
for i in df[(df['Q2'] == 'Woman') & (df['Q4'] == 'Master’s degree') & (df['Q3'] == 'Australia')]['Q5']:
    if i in a:
        c += 1
n.append(c)
x = ['2018','2019','2020','2021']
y = n
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ('Woman with master degree and any job related to data science in Australia',weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:

1. In <strong> 2019,2021(13) </strong> more Woman with Maters degree and working as a Data Scientist in Australia when compared to years <strong> 2018,2020 </strong>.
2. In <strong> 2020(9) </strong>more Woman with Maters degree and working as a Data Scientist in Australia when compared to the years <strong>2018(7)</strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman above age 50 employement vs unemployement<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
# Displaying values at the top of the Grouped Bar Chart using plt.text()
plt.figure(figsize=(10,6))

# set width of bar
barWidth = 0.2
n = []
c = 0
for i in df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q6'] != 'Not employed')]['Q2']:
    if i in ['50-54','55-59','60-69','70-79','70+','80+']:
        c+=1
n.append(c)
c = 0
for i in df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q5'] != 'Not employed')]['Q1']:
    if i in ['50-54','55-59','60-69','70-79','70+','80+']:
        c+=1
n.append(c)
c = 0
for i in df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q5'] != 'Currently not employed')]['Q1']:
    if i in ['50-54','55-59','60-69','70-79','70+','80+']:
        c+=1
n.append(c)
c = 0
for i in df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed')]['Q1']:
    if i in ['50-54','55-59','60-69','70-79','70+','80+']:
        c+=1
n.append(c)


n1 = []
c = 0
for i in df_2018[(df_2018['Q1'] == 'Woman') & (df_2018['Q6'] == 'Not employed')]['Q2']:
    if i in ['50-54','55-59','60-69','70-79','70+','80+']:
        c+=1
n1.append(c)
c = 0
for i in df_2019[(df_2019['Q2'] == 'Woman') & (df_2019['Q5'] == 'Not employed')]['Q1']:
    if i in ['50-54','55-59','60-69','70-79','70+','80+']:
        c+=1
n1.append(c)
c = 0
for i in df_2020[(df_2020['Q2'] == 'Woman') & (df_2020['Q5'] == 'Currently not employed')]['Q1']:
    if i in ['50-54','55-59','60-69','70-79','70+','80+']:
        c+=1
n1.append(c)
c = 0
for i in df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed')]['Q1']:
    if i in ['50-54','55-59','60-69','70-79','70+','80+']:
        c+=1
n1.append(c)


x = ['2018','2019','2020','2021']
y1 = n
y2 = n1

pos1 = np.arange(len(y1))
pos2 = [x + barWidth for x in pos1]

# Make the plot
plt.bar(pos1, y1, color='#FBC02D', width=barWidth, label='Employed')
plt.bar(pos2, y2, color='#F57F17', width=barWidth, label='unemployed')

# Add xticks on the middle of the group bars
plt.xticks([i + barWidth for i in range(len(y1))], x,rotation=90,weight = 'bold')

for x,y in zip(pos1,y1):
    plt.text(x, y, '%d' % y, ha='center' , va= 'bottom')
    
for x,y in zip(pos2,y2):
    plt.text(x, y, '%d' % y, ha='center' , va= 'bottom')
    
plt.suptitle ("Woman above age 50 employement vs unemployement",weight = 'bold')

# Create legend & Show graphic
plt.legend()
plt.show()

#### Observation:

Employed women are significantly very high in very year when compared to unemployed women.

#### Answers for questions asked by girls:
1. Yes, it is possible for women to get job related to data science.Because, we already saw that in 2021 there are 1632 women having jobs related to data science invloved in the survey which is highest till now from 2018. So, getting job related data science is possible with hardwork and commitment since there are good opportunities for women to get jobs. 
2. Yes, it is possible for <strong> Nebula </strong> to get Data Analyst job with Bachelor's degree.Because, we already saw that in 2021 there are 171 women having Data Analyst job with Bachelor's degree invloved in the survey which is highest till now from 2018 and it is gradually increasing from 2018. So, in future there will be more opportunities for no only nebula but for women with Bachelor's degree and getting Data Analyst job.
3. Yes, it is possible for <strong> Wanda </strong> to get job related to data science with no coding experience.Because, we already saw that in 2021 there are 102 women having job related to data science with no coding experience invloved in the survey which is highest till now from 2018 and it is gradually increasing from 2018. So, in future there will be more opportunities for no only wanda but for women who have no coding experience and getting job retaled to data science .
4. It will be a little difficult for <strong> Wanda </strong> but not impossible to get job related to data science who knows only R programming language, because from 2018 there is significant decrease of women having job related to data science who knows only R programming language but in 2021 it is increased when compared to 2019,2020 and one more thing is in every year employed women who knows are morethan unemployed women who knows R with huge difference. So, she need to be perfect in R to get job.
5. It will be difficult for <strong> Pepper Potts </strong> but not impossible to get job related to data science in USA, because from 2018 there is significant decrease of women having job related to data science in USA but in 2021 it is increased when compared to 2020.
6. Yes, it possible for <strong> Gamora </strong> to get job related to data science with doctoral degree. In every year there are morethan 150 women invloved in the survey have jobs related to data science with doctoral degree.
7. Out of 38 women invloved in 2021 survey from Australia 5 are unemployed. Reality is we can't say <strong> Peggy Carter </strong>will get job or not by simply this but out of those 24(actually 33 but 9 are students) employed women 20 have jobs related to data science.
8. Yes, it is possible for women of age above 50 to get job .Because, we already saw that in 2021 there are 219 women having jobs invloved in the survey which is highest till now from 2018. So, getting job is possible with hardwork and commitment since there are good opportunities for women to get jobs.

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">How all age groups of woman doing in year 2021<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman count in all age groups<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
x = df[df['Q2'] == 'Woman']['Q1'].value_counts().keys().tolist()
y = df[df['Q2'] == 'Woman']['Q1'].value_counts().values.tolist()
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ("Women in all age groups",weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Employed vs Unemployed women in all age groups<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
# Displaying values at the top of the Grouped Bar Chart using plt.text()
plt.figure(figsize=(14,8))

# set width of bar
barWidth = 0.2
n = []
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q1'] == '18-21')]['Q1']))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q1'] == '25-29')]['Q1']))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q1'] == '22-24')]['Q1']))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q1'] == '30-34')]['Q1']))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q1'] == '35-39')]['Q1']))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q1'] == '40-44')]['Q1']))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q1'] == '45-49')]['Q1']))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q1'] == '50-54')]['Q1']))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q1'] == '55-59')]['Q1']))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q1'] == '60-69')]['Q1']))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q1'] == '70+')]['Q1']))

n1 = []
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q1'] == '18-21')]['Q1']))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q1'] == '25-29')]['Q1']))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q1'] == '22-24')]['Q1']))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q1'] == '30-34')]['Q1']))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q1'] == '35-39')]['Q1']))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q1'] == '40-44')]['Q1']))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q1'] == '45-49')]['Q1']))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q1'] == '50-54')]['Q1']))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q1'] == '55-59')]['Q1']))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q1'] == '60-69')]['Q1']))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q1'] == '70+')]['Q1']))

x = df[df['Q2'] == 'Woman']['Q1'].value_counts().keys().tolist()
y1 = n
y2 = n1

pos1 = np.arange(len(y1))
pos2 = [x + barWidth for x in pos1]

# Make the plot
plt.bar(pos1, y1, color='#FBC02D', width=barWidth, label='Employed')
plt.bar(pos2, y2, color='#F57F17', width=barWidth, label='unemployed')

# Add xticks on the middle of the group bars
plt.xticks([i + barWidth for i in range(len(y1))], x,rotation=90,weight = 'bold')

for x,y in zip(pos1,y1):
    plt.text(x, y, '%d' % y, ha='center' , va= 'bottom')
    
for x,y in zip(pos2,y2):
    plt.text(x, y, '%d' % y, ha='center' , va= 'bottom')
    
plt.suptitle ("Employed vs Unemployed women in all age groups",weight = 'bold')

# Create legend & Show graphic
plt.legend()
plt.show()

#### Observation:

Employed women are significantly very high in very year when compared to unemployed women.

## Note: In all heatmaps red patches indicates HIGHEST VALUE IN EVERY COLUMN and blue patches indicates HIGHEST VALUE IN EVERY ROW

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age Distribution of women by country<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
from matplotlib.patches import Rectangle
z=df[df['Q2']=='Woman'].groupby(['Q3','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 24))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black',annot_kws={"fontsize":12}, fmt='.3f', cbar=False)
plt.ylabel('Country', weight = 'bold', fontsize = 20)
plt.xlabel('Age groups of women',weight = 'bold', fontsize = 20)
plt.title('Age Distribution of women by country',weight='bold', fontsize = 20)

columns_text = z.columns

column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)

for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.yticks(fontsize=14,weight = 'bold')
plt.xticks(fontsize=14,weight = 'bold')
plt.show()

#### Observation:

1. Most of the people in age groups <strong> 18-21,22-24,25-29,30-34 </strong>are from <strong> India </strong>. This states that age group <strong> 18-34 (young to middle aged women) </strong> are more invloved in the survey from India.
2. From India there are <strong> 701 women from age group 18-21 </strong> which is highest among all, whereas <strong> Indonesia </strong> stands in second place with only <strong> 40 women </strong> invloved in survey, followed by <strong> USA </strong> with <strong> 30 women </strong> involved. We can expect this because we already saw that Indian women are more in the survey.
3. Age groups <strong> 35-39, 40-44 </strong> are also actively invloved from India when compared to other countries, actually in <strong> second place </strong> after women from USA.
4. Most of the people in age groups <strong> 35-39,40-44,45-49,50-54,55-59,60-69,70+ </strong>are from <strong> USA </strong>. This states, that age group <strong> 35-70+ (middle to old aged women) </strong> are more invloved in the survey from <strong> USA </strong>.
5. Women from <strong> USA and India </strong> are more invloved in survey when compared to all other countries.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of woman by degree<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q4','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Degree',weight = 'bold', fontsize = 20)
plt.title('Age Distribution of women by degree',weight='bold', fontsize = 20)
plt.yticks(fontsize=14,weight = 'bold')
plt.xticks(fontsize=14,weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q4','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))   
plt.ylabel('Degree',weight = 'bold', fontsize = 20)
plt.title('Age Distribution of women by degree',weight='bold', fontsize = 20)
plt.yticks(fontsize=14,weight = 'bold')
plt.xticks(fontsize=14,weight = 'bold')
plt.show()

#### Observation
##### All these observations are with respect to the women in the survey not entire women in the world 
 
 
1. In age group <strong> 18-21 </strong> most of the women<strong> (763) </strong> attained/wanted to do <strong> Bachelor's degree </strong>.
2. In age group <strong> 22-24 </strong> most of the women<strong> (435) </strong> attained/wanted to do <strong> Bachelor's degree </strong>, followed by women with/wanted to do <strong> Master's Degree(423) </strong> are more.
3. In age group <strong> 22-24 </strong> women with/wanted to do <strong> Bachelor's degree </strong> and women with/wanted to do <strong> Master's degree </strong> are almost equal.
4. In age group <strong>  25-70+ </strong> most of the women attained/wanted to do <strong> Master's degree.</strong>
5. In age group <strong> 60-69 </strong> most of thr women attained/wanted to do both <strong> Bachelor's and Master's degree </strong>.
6. There are only <strong> 8 women </strong> of age group <strong> 70+ </strong> invloved in the survey in which 4 women attained/wanted to do <strong> Master's degree </strong>, 2 women each attained/wanted to <strong> Bachelor's degree and professional doctorate </strong>.
7. Most of the Women attained/wanted to do <strong> Bachelor's degree </strong> are from age group <strong> 18-21 (763) </strong>.
8. Most of the Women attained/wanted to do <strong> Doctoral degree </strong> are from age group <strong> 35-39 (129) </strong>.
9. Most of the Women who <strong> donot prefer to answer </strong> are from age group <strong> 18-21(31) </strong>.
10. Most of the Women attained/wanted to do <strong> Master's degree </strong> are from age group <strong> 25-29 (538) </strong>.
11. Most of the Women who <strong> had no formal education past high school </strong> are from age group <strong> 18-21 (15) </strong>.
12. Most of the Women attained/wanted to do <strong> Professional doctorate </strong> are from age group <strong> 30-34 (18) </strong>.
13. Most of the Women studing in <strong> Some college/university study without earning a bachelor's degree </strong> are from age group <strong> 18-21 (147) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by Current Job<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q5','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":12}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Current Job',weight = 'bold', fontsize = 20)
plt.title('Age Distribution of women by Current Job',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:
##### All these observations are with respect to the women in the survey not entire women in the world 

1. In age group <strong> 18-29 </strong> most of the women are <strong> Students(837) </strong>, but women in age groups 22-29 are pretty much invloved in jobs.
2. In age group <strong> 30-44 </strong> most of the women are working as <strong> Data Scientist(383) </strong>.
3. In age group <strong> 45-69 </strong> most of the women are working in <strong> Other fields(189) </strong> which are not mentioned in survey options.
4. In age group <strong> 70+ </strong> most of the women are <strong> Currently not Employed </strong>
5. In age group <strong> 25-29 </strong> most of them are students but number is not much domiant like in case of age group 18-21, many women of age group <strong> 25-29 </strong> are working in <strong> Data Science related fields </strong>.


I have some doubts here may be I am wrong but I want to confess, The question is given to choose the option related to your current role many of the women of age group 18-21 have choosed student but I can see one women of this age group choosed Product manager. I think it is not possible because at this age almost all people will do bachelor's degree may be other degree as well but surely all people of age group 18-21 are invloved in study. If we need a job degree is compulsory, how can someone get job without degree??? and that too a job related to product manager which requires experience. May be the one who choosed that she is a product manager is given false information or may be I am wrong but my point is that it is not possible to become a product manager at that age even if she has degree.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by Coding Experience<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q6','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Coding Experience',weight = 'bold', fontsize = 20)
plt.title('Age Distribution of women by Coding Experience',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold',rotation = 45)
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q6','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 20)
index_text = z.index
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))   
plt.ylabel('Coding Experience',weight = 'bold', fontsize = 20)
plt.title('Age Distribution of women by Coding Experience',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold',rotation = 45)
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. In age group <strong> 18-29 </strong> most of the women have coding experience in between <strong> 1-3 years </strong>
2. In age group <strong> 30-39 </strong> most of the women have coding experience <strong> lessthan 1 year </strong>
3. In age group <strong> 40-44 </strong> most of the women have coding experience in between <strong> 10-20 years </strong>
4. In age group <strong> 45-49 </strong> most of the women have coding experience <strong> lessthan 1 year </strong>
5. In age group <strong> 50-69 </strong> most of the women have coding experience <strong> morethan than 20 years </strong>
6. In age group <strong> 70+ </strong> most of the women have coding experience <strong> morethan than 10 years </strong>


Here also I have got some questions....

How can women of age group 18-21 have coding experience morethan 20 years??????? Like if we think they are of age 21, do they start coding when their age is 1???? It is absolutley false data given by them. So how can we prevent people from giving false data?? Just need to disable some options according to their age group so that they cannot select them.

Same in case of woman of age group 22-24 who has coding experience morethan 20 years

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Python vs R vs SQL(Programming Language used on regular basis) in all Age Groups of Women<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q1']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Python is most choosed by the women of age group <strong> 18-21(959) </strong> and less choosed by the women of age group <strong> 70+(4) </strong>.
2. R is most choosed by the women of age group <strong> 25-29(243) </strong> and less choosed by the women of age group <strong> 60-69(15) </strong>. Intresting fact is no women of age group <strong> 70+ </strong> choosed <strong> R </strong>.
3. SQL is most choosed by the women of age group <strong> 25-29 (456) </strong> and less choosed by the women of age group <strong> 70+(3) </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by Programming Language recommended for aspiring Data Scientist<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q8','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 14)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Programming Language',weight = 'bold', fontsize = 14)
plt.title('Age distribution of women by Programming Language recommended for aspiring Data Scientist',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q8','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 14)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Programming Language',weight = 'bold', fontsize = 14)
plt.title('Age distribution of women by Programming Language recommended for aspiring Data Scientist',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. Not quite suprised here, women from age 18 to 70+ all recommended python programming language for aspiring data scientists

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">VSCode vs PyCharm vs Jupyter Notebook(IDE's used on Regular Basis) in all Age Groups of Women<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q1']).size()) 
              for var in {'Q9_Part_4','Q9_Part_5','Q9_Part_11'}}
multi_table([df_groupby['Q9_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q9_Part_5'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q9_Part_11'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed VSCode, PyCharm and Jupyter Notebook only these 3 because these are the most choosed option.

1. VSCode is most choosed by the women of age group <strong> 18-21(505) </strong> and less choosed by the women of age group <strong> 60-69(7) </strong>. Intresting fact is no women of age group <strong> 70+ </strong> choosed <strong> VSCode </strong>.
2. PyCharm is most choosed by the women of age group <strong> 18-21(367) </strong> and less choosed by the women of age group <strong> 60-69(6) </strong>. Intresting fact is no women of age group <strong> 70+ </strong> choosed <strong> PyCharm </strong>.
3. Jupyter Notebook is most choosed by the women of age group <strong> 18-21(690) </strong> and less choosed by the women of age group <strong> 70+(5) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Kaggle vs Colab vs Google Cloud Datalab(hosted notebooks used on Regular Basis) in all Age Groups of Women<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q1']).size()) 
              for var in {'Q10_Part_1','Q10_Part_2','Q10_Part_11'}}
multi_table([df_groupby['Q10_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q10_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q10_Part_11'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Kaggle Notebooks, Colab Notebooks and Google Cloud Datalab only these 3 because these are the most choosed option.

1. Kaggle Notebooks is most choosed by the women of age group <strong> 18-21(415) </strong> and less choosed by the women of age group <strong> 70+(1) </strong>. 
2. Colab Notebooks is most choosed by the women of age group <strong> 18-21(432) </strong> and less choosed by the women of age group <strong> 60-69(10) </strong>. Intresting fact is no women of age group <strong> 70+ </strong> choosed <strong> Colab Notebooks </strong>.
3. Google Cloud Datalab is most choosed by the women of age group <strong> 18-21(92) </strong> and less choosed by the women of age group <strong> 60-69(2) </strong>.Intresting fact is no women of age group <strong> 70+ </strong> choosed <strong> Google Cloud Datalab </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by Specialized Software used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q11','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Specialized Software', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Age groups of women',weight = 'bold', fontsize = 20)
plt.title('Age Distribution of women by Specialized Software used on regular basis',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q11','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Specialized Software', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Age groups of women',weight = 'bold', fontsize = 20)
plt.title('Age Distribution of women by Specialized Software used on regular basis',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. In age group <strong> 18-69 </strong> most of the women choosed <strong> Laptop </strong> as their specialized software used on regular basis.
2. Only women of age group <strong> 70+ </strong> choosed <strong> A personal computer/ desktop </strong> as their specialized software used on regular basis.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by Data Visualization Libraries used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q1']).size()) 
              for var in {'Q14_Part_1','Q14_Part_2','Q14_Part_3','Q14_Part_4'}}
multi_table([df_groupby['Q14_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q14_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q14_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q14_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Matplotlib, Seaborn, Plotly/ Plotly Express and Ggplot/ggplot2 only these 4 because these are the most choosed option.

1. Matplotlib is most choosed by the women of age group <strong> 25-29(659) </strong> and less choosed by the women of age group <strong> 70+(6) </strong>. 
2. Seaborn is most choosed by the women of age group <strong> 25-29(484) </strong> and less choosed by the women of age group <strong> 70+ (5) </strong>.
3. Plotly/Plotly Express is most choosed by the women of age group <strong> 25-29(216) </strong> and less choosed by the women of age group <strong> 70+(2) </strong>.
4. Ggplot/ ggplot2 is most choosed by the women of age group <strong> 25-29(237) </strong> and less choosed by the women of age group <strong> 70+(1) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by No. of years Machine Learning Methods used<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q15','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('No. of Years',weight = 'bold', fontsize = 20)
plt.title('Age distribution of women by No. of years Machine Learning Methods used',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q15','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('No. of Years',weight = 'bold', fontsize = 20)
plt.title('Age distribution of women by No. of years Machine Learning Methods used',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women of age group <strong> 18-59 </strong>used/using machine learning methods <strong> lessthan 1 year </strong>.
2. Most of the women of age group <strong> 60-69 </strong> have <strong> not used </strong>any machine learning methods.
3. Most of the women of age group <strong> 70+ </strong> used/using machine learning methods in between <strong> 1-2 years</strong>.
4. Most of the women who don't use any machine learning methods or used/using machine learning methods <strong> lessthan 1 year </strong> are of age group <strong> 18-21 </strong>.
5. Most of the women who used/using machine learning methods in between <strong> 1-2 years </strong> are of age group <strong> 22-24 </strong>.
6. Most of the women who used/using machine learning methods in between <strong> 2-4 years </strong> are of age group <strong> 25-29 </strong>.
7. Most of the women who used/using machine learning methods in between <strong> 4-20 years </strong> are of age group <strong> 35-39 </strong>.
8. Most of the women who used/using machine learning methods from <strong> morethan 20 years </strong> are of age group <strong> 50-54 </strong>.


Here also couple of women given false information, How can women of age groups 22-24 have used/using Machine learning methods from morethan 20 years??? It is false information because practically from the age of 2 or 3, it is not possible to learn ML methods....!!!!

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by Machine Learning Frameworks used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q1']).size()) 
              for var in {'Q16_Part_1','Q16_Part_2','Q16_Part_3','Q16_Part_4','Q16_Part_7'}}
multi_table([df_groupby['Q16_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q16_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q16_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q16_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q16_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Scikit-learn, TensorFlow, Keras, PyTorch and Xgboost only these 5 because these are the most choosed option.


1. Scikit-learn is most choosed by the women of age group <strong> 25-29(521) </strong> and less choosed by the women of age group <strong> 70+(5) </strong>. 
2. TensorFlow is most choosed by the women of age group <strong> 25-29(316) </strong> and less choosed by the women of age group <strong> 70+ (1) </strong>.
3. Keras is most choosed by the women of age group <strong> 25-29(267) </strong> and less choosed by the women of age group 
<strong> 70+(1) </strong>.
4. PyTorch is most choosed by the women of age group <strong> 25-29(197) </strong> and less choosed by the women of age group <strong> 60-69(4) </strong>.Intresting fact is no women of age group <strong> 70+ </strong> choosed <strong> PyTorch </strong>.
5. Xgboost is most choosed by the women of age group <strong> 25-29(194) </strong> and less choosed by the women of age group <strong> 70+(1) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by Machine Learning Algorithms used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q1']).size()) 
              for var in {'Q17_Part_1','Q17_Part_2','Q17_Part_3','Q17_Part_7'}}
multi_table([df_groupby['Q17_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q17_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q17_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q17_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Linear or Logistic Regression, Desision Trees or Random Forests, Gradient Boosting Machines (xgboost, lightgbm, etc) and Convolutional Neural Networks only these 4 because these are the most choosed option.


1. Linear or Logistic Regression is most choosed by the women of age group <strong> 25-29(502) </strong> and less choosed by the women of age group <strong> 70+(5) </strong>. 
2.  Desision Trees or Random Forests is most choosed by the women of age group <strong> 25-29(428) </strong> and less choosed by the women of age group <strong> 70+ (5) </strong>.
3. Gradient Boosting Machines (xgboost, lightgbm, etc) is most choosed by the women of age group <strong> 25-29(232) </strong> and less choosed by the women of age group  <strong> 70+(2) </strong>.
4. Convolutional Neural Networks is most choosed by the women of age group <strong> 25-29(225) </strong> and less choosed by the women of age group <strong> 70+(1) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by Current Employer/ Contract<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q20','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 14)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Current Employer/ contract',weight = 'bold', fontsize = 14)
plt.title('Age distribution of women by Current Employer/ Contract',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q20','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 14)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Current Employer/ contract',weight = 'bold', fontsize = 14)
plt.title('Age distribution of women by Current Employer/ Contract',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women of age group <strong> 18-21 </strong> have current Employer/contract as <strong> Academics/Education </strong>
2. Most of the women of age group <strong> 22-29 </strong> have current Employer/contract as <strong> Computers/Technology </strong>
3. Most of the women of age group <strong> 30-70+ </strong> have current Employer/contract as <strong> Academics/Education </strong>
4. Most of the women with Current Employer/Contract as <strong> Academics/Education, Accounting/Finance,
Broadcasting/Communications, Computers/Technology, Hospitality/Entertainment/Sports,Manufacturing/Fabrication,Marketing/CRM, Medical/Pharmaceutical, Non-profit/Service, Online Business/Internet-based Sales,Online Service/Internet-based Services, Other, Retail/Sales </strong> are of age group <strong> 25-29 </strong>
5. Most of the women with Current Employert/Contract as <strong> Energy/Mining,Government/Public Service,Insurance/Risk Assessment,Shipping/Transportation </strong> are of age group <strong> 30-34 </strong>.
6. Most of the women with Current Employer/Contract as <strong> Military/Security/Defense </strong> are of age group <strong> 22-24 </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by Current Yearly Compensation <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q25','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(20, 13))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Compensation in USD',weight = 'bold', fontsize = 20)
plt.title('Age distribution of women by Current Yearly Compensation',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q25','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(20, 13))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Compensation in USD',weight = 'bold', fontsize = 20)
plt.title('Age distribution of women by Current Yearly Compensation',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women of age group <strong> 18-49 </strong> and <strong> 55-69 </strong> are earning <strong> 0-999 USD </strong> yearly.
2. Most of the women of age group <strong> 50-54 </strong> and <strong> 70+ </strong> are earning <strong> 100,000 - 124,999 USD </strong> yearly.
3. Most of the women who earn <strong> 0-999 USD,$4,000 - 4,999,$300,000 - 499,999 </strong> are of age group <strong> 22-24 </strong>.
4. Most of the women who earn <strong> 1,000-1,999 USD, $10,000-14,999, $15,000-19,999, $2,000-2,999, $20,000-24,999,$200,000-249,999, $25,000-29,999, $3,000-3,999, $30,000-39,999, $40,000-49,999,$5,000-7,499,$50,000-59,999,$7,500-9,999 </strong> are of age group <strong> 25-29 </strong>.
5. Most of the women who earn <strong> $125,000-149,999, $80,000-89,999 </strong> are of age group <strong> 30-34 </strong>.
6. Most of the women who earn <strong> 500,000-999,999 USD, $150,000-199,999,$60,000-69,999,$70,000-79,999,$90,000-99,999 </strong> are of age group <strong> 35-39 </strong>.
7. Most of the women who earn <strong> 100,000-124,999 USD, $>$1,000,000 </strong> are of age group <strong> 40-44 </strong>.
8. Most of the women who earn <strong> 250,000-299,999 </strong> are of age group <strong> 55-59 </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by Money spent on learning Machine Learning/ Cloud Computing services in the past 5 years <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q26','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 14)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Compensation in USD',weight = 'bold', fontsize = 14)
plt.title('Age distribution of women by Money spent on learning Machine Learning/ Cloud Computing services in the past 5 years',weight='bold', fontsize = 20)
plt.yticks(fontsize=14,weight = 'bold')
plt.xticks(fontsize=14,weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q26','Q1']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Age groups of women', weight = 'bold', fontsize = 14)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Compensation in USD',weight = 'bold', fontsize = 14)
plt.title('Age distribution of women by Money spent on learning Machine Learning/ Cloud Computing services in the past 5 years',weight='bold', fontsize = 20)
plt.yticks(fontsize=14,weight = 'bold')
plt.xticks(fontsize=14,weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women of age group <strong> 18-70+ </strong> have not spent money to learn Machine Learning/ Cloud Computing services in the past 5 years.
2. Most of the women who spend <strong> 0-99,999 USD </strong> to learn Machine Learning/ Cloud Computing services in the past 5 years are of age group <strong> 25-29 </strong>.
3. Most of the women who spend <strong> more than 100,000 USD </strong> to learn Machine Learning/ Cloud Computing services in the past 5 years are of age group <strong> 40-44 </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by public application to share your data analysis or machine learning <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q1']).size()) 
              for var in {'Q39_Part_4','Q39_Part_6','Q39_Part_7','Q39_Part_9'}}
multi_table([df_groupby['Q39_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q39_Part_6'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q39_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q39_Part_9'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed GitHub, Kaggle, Colab, I do not share my work publicly only these 4 because these are the most choosed option.


1. GitHub is most choosed by the women of age group <strong> 25-29(157) </strong> and less choosed by the women of age group <strong> 70+(2) </strong>. 
2.  Kaggle is most choosed by the women of age group <strong> 25-29(91) </strong> and less choosed by the women of age group <strong> 70+ (1) </strong>.
3. Colab is most choosed by the women of age group <strong> 25-29(64) </strong> and less choosed by the women of age group  <strong> 55-69(2) </strong>.Intresting fact is no women of age group <strong> 70+ </strong> choosed <strong> Colab </strong>.
4.  I do not share my work publicly is most choosed by the women of age group <strong> 25-29(111) </strong> and less choosed by the women of age group <strong> 60-69(4) </strong>.Intresting fact is no women of age group <strong> 70+ </strong> choosed <strong>  I do not share my work publicly </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by platforms they begun or completed data science courses<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q1']).size()) 
              for var in {'Q40_Part_1','Q40_Part_3','Q40_Part_7','Q40_Part_10'}}
multi_table([df_groupby['Q40_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q40_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q40_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q40_Part_10'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Linear or Coursera, Kaggle Learn Courses, Udemy and University Courses (resulting in a university degree) only these 4 because these are the most choosed option.


1. Coursera is most choosed by the women of age group <strong> 25-29(358) </strong> and less choosed by the women of age group <strong> 70+(5) </strong>. 
2. Kaggle Learn Courses is most choosed by the women of age group <strong> 18-21(303) </strong> and less choosed by the women of age group <strong> 70+ (5) </strong>.
3. Udemy is most choosed by the women of age group <strong> 25-29(252) </strong> and less choosed by the women of age group  <strong> 70+(3) </strong>.
4. University Courses (resulting in a university degree is most choosed by the women of age group <strong> 25-29(238) </strong> and less choosed by the women of age group <strong> 70+(3) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Age distribution of women by favorite media sources that report on data science topics<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q1']).size()) 
              for var in {'Q42_Part_4','Q42_Part_6','Q42_Part_8'}}
multi_table([df_groupby['Q42_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q42_Part_6'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q42_Part_8'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed  Kaggle (notebooks, forums, etc), YouTube (Kaggle YouTube, Cloud AI Adventures, etc), Blogs (Towards Data Science, Analytics Vidhya, etc) only these 3 because these are the most choosed option.


1. Kaggle (notebooks, forums, etc) is most choosed by the women of age group <strong> 25-29(405) </strong> and less choosed by the women of age group <strong> 70+(6) </strong>. 
2. YouTube (Kaggle YouTube, Cloud AI Adventures, etc) is most choosed by the women of age group <strong> 18-21(369) </strong> and less choosed by the women of age group <strong> 70+ (4) </strong>.
3. Blogs (Towards Data Science, Analytics Vidhya, etc) is most choosed by the women of age group <strong> 25-29(315) </strong> and less choosed by the women of age group  <strong> 70+(4) </strong>.

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Analysis with respect to Degree Distribution of women<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman count in all Degrees<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
x = df[df['Q2'] == 'Woman']['Q4'].value_counts().keys().tolist()
y = df[df['Q2'] == 'Woman']['Q4'].value_counts().values.tolist()
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ("Women in all Degrees",weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women involved in <strong> 2021 </strong> survey attained/wanted to do <strong> Master's degree(1950) </strong>
2. Women attained/wanted to do <strong> Bachelor's degree(1843) </strong> stands in 2nd place in <strong> 2021 </strong>.
3. Very less women invloved in <strong> 2021 </strong> survey had <strong> No formal education past high school </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Employed vs Unemployed women in all Degrees<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
# Displaying values at the top of the Grouped Bar Chart using plt.text()
plt.figure(figsize=(14,8))

# set width of bar
barWidth = 0.2
n = []
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q4'] == "Master’s degree")]))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q4'] == "Bachelor’s degree")]))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q4'] == "Doctoral degree")]))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q4'] == "Some college/university study without earning a bachelor’s degree")]))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q4'] == "I prefer not to answer")]))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q4'] == "No formal education past high school")]))
n.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] != 'Currently not employed') & (df['Q4'] == "Professional doctorate")]))

n1 = []
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q4'] == "Master’s degree")]))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q4'] == "Bachelor’s degree")]))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q4'] == "Doctoral degree")]))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q4'] == "Some college/university study without earning a bachelor’s degree")]))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q4'] == "I prefer not to answer")]))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q4'] == "No formal education past high school")]))
n1.append(len(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed') & (df['Q4'] == 'Professional doctorate')]))

x = df[df['Q2'] == 'Woman']['Q4'].value_counts().keys().tolist()
y1 = n
y2 = n1

pos1 = np.arange(len(y1))
pos2 = [x + barWidth for x in pos1]

# Make the plot
plt.bar(pos1, y1, color='#FBC02D', width=barWidth, label='Employed')
plt.bar(pos2, y2, color='#F57F17', width=barWidth, label='unemployed')

# Add xticks on the middle of the group bars
plt.xticks([i + barWidth for i in range(len(y1))], x,rotation=90,weight = 'bold')

for x,y in zip(pos1,y1):
    plt.text(x, y, '%d' % y, ha='center' , va= 'bottom')
    
for x,y in zip(pos2,y2):
    plt.text(x, y, '%d' % y, ha='center' , va= 'bottom')
    
plt.suptitle ("Employed vs Unemployed women in all Degrees",weight = 'bold')

# Create legend & Show graphic
plt.legend()
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. In every degree employed women are morethan the unemployed women with good margin.
2. Women with <strong> Master's Degree(1763) </strong> have more employed when compared to women with other degree.
3. Women with <strong> Master's Degree(187) </strong> have more unemployed when compared to women with other degree, but it is not a problem because when compared to 1763 employed women 187 is negligible this also states that employement rate is very high for women.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree Distribution of women by age<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
from matplotlib.patches import Rectangle
z=df[df['Q2']=='Woman'].groupby(['Q1','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black',annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.ylabel('Age Groups', weight = 'bold', fontsize = 14)
plt.xlabel('Degrees of women',weight = 'bold', fontsize = 14)
plt.title('Degree Distribution of women by Age Groups',weight='bold', fontsize = 20)

columns_text = z.columns

column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)

for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
from matplotlib.patches import Rectangle
z=df[df['Q2']=='Woman'].groupby(['Q1','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black',annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.ylabel('Age Groups', weight = 'bold', fontsize = 14)
plt.xlabel('Degrees of women',weight = 'bold', fontsize = 14)
plt.title('Degree Distribution of women by Age Groups',weight='bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation
##### All these observations are with respect to the women in the survey not entire women in the world 
 
 
1. In age group <strong> 18-21 </strong> most of the women<strong> (763) </strong> attained/wanted to do <strong> Bachelor's degree </strong>.
2. In age group <strong> 22-24 </strong> most of the women<strong> (435) </strong> attained/wanted to do <strong> Bachelor's degree </strong>, followed by women with/wanted to do <strong> Master's Degree(423) </strong> are more.
3. In age group <strong> 22-24 </strong> women with/wanted to do <strong> Bachelor's degree </strong> and women with/wanted to do <strong> Master's degree </strong> are almost equal.
4. In age group <strong>  25-70+ </strong> most of the women attained/wanted to do <strong> Master's degree.</strong>
5. In age group <strong> 60-69 </strong> most of thr women attained/wanted to do both <strong> Bachelor's and Master's degree </strong>.
6. There are only <strong> 8 women </strong> of age group <strong> 70+ </strong> invloved in the survey in which 4 women attained/wanted to do <strong> Master's degree </strong>, 2 women each attained/wanted to <strong> Bachelor's degree and professional doctorate </strong>.
7. Most of the Women attained/wanted to do <strong> Bachelor's degree </strong> are from age group <strong> 18-21 (763) </strong>.
8. Most of the Women attained/wanted to do <strong> Doctoral degree </strong> are from age group <strong> 35-39 (129) </strong>.
9. Most of the Women who <strong> donot prefer to answer </strong> are from age group <strong> 18-21(31) </strong>.
10. Most of the Women attained/wanted to do <strong> Master's degree </strong> are from age group <strong> 25-29 (538) </strong>.
11. Most of the Women who <strong> had no formal education past high school </strong> are from age group <strong> 18-21 (15) </strong>.
12. Most of the Women attained/wanted to do <strong> Professional doctorate </strong> are from age group <strong> 30-34 (18) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree Distribution of women by country<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
from matplotlib.patches import Rectangle
z=df[df['Q2']=='Woman'].groupby(['Q3','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 24))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black',annot_kws={"fontsize":12}, fmt='.3f', cbar=False)
plt.ylabel('Country', weight = 'bold', fontsize = 14)
plt.xlabel('Degrees of women',weight = 'bold', fontsize = 14)
plt.title('Degree Distribution of women by country',weight='bold', fontsize = 20)

columns_text = z.columns

column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)

for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation
##### All these observations are with respect to the women in the survey not entire women in the world 

1. <strong> Indian women </strong> are more when compared to all other women across world in attained/want to do any degree followed by <strong> USA women </strong> in second place

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by Current Job<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q5','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Current Job',weight = 'bold', fontsize = 14)
plt.title('Degree Distribution of women by Current Job',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q5','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Current Job',weight = 'bold', fontsize = 14)
plt.title('Degree Distribution of women by Current Job',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:
##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women who attained/wanted to do <strong>  Bachelor's degree, Prefer not to answer, Master's degree,No formal education past high school, some college/university study without earning a bachelor's degree </strong> are <strong> Students </strong>.
2. Most of the women who attained/wanted to do <strong>  Doctoral degree, Professional doctorate </strong> are <strong> Research Scientist </strong>.
3. Most of the women with current job as <strong> Business Analyst,Currently not employed,DBA/Database Engineer,Data Analyst, Data Engineer,Data Scientist,Developer Relations/Advocacy, Machine Learning Engineer,Other,Product Manager,Program/Project Manager </strong> have attained <strong> Master's Degree </strong>.
4. Most of the women with current job as <strong> Software Engineer </strong> have attained <strong> Bachelor's Degree </strong>
5. Most of the <strong> Student </strong> women attained/want to do <strong> Bachelor's Degree </strong>
6. Most of the women with current job as <strong> Research Scientist </strong> have attained <strong> Doctoral Degree </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by Coding Experience<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q6','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Coding Experience',weight = 'bold', fontsize = 14)
plt.title('Degree Distribution of women by Coding Experience',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold',rotation = 45)
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q6','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Coding Experience',weight = 'bold', fontsize = 14)
plt.title('Degree Distribution of women by Coding Experience',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold',rotation = 45)
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:
##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women who attained/wanted to do <strong>  Bachelor's degree, Prefer not to answer, Master's degree </strong> have coding experience in between <strong> 1-3 years </strong>.
2. Most of the women who attained/wanted to do <strong>  No formal education past high school, Professional Doctorate,Some college/university study without earning a bachelor's degree </strong> have coding experience <strong> lessthan 1 year </strong>.
3. Most of the women who attained/wanted to do <strong>  Doctoral degree </strong> have coding experience in between <strong> 3-5 years </strong>.
4. Most of the women with coding experience <strong> 3-20+ years </strong> have attained/want to do <strong> Master's Degree </strong>
5. Most of the women with no coding experience or <strong> 0-3 years </strong> of coding experience have attained/want to do <strong> Bachelor's Degree </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Python vs R vs SQL(Programming Language used on regular basis) in all Degrees of Women<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q4']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Python is most choosed by the women who attained/want to do <strong> Master's degree(1574) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(30) </strong>.
2. R is most choosed by the women who attained/want to do <strong> Master's degree(540) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(5) </strong>.
3. SQL is most choosed by the women who attained/want to do <strong> Master's degree(954) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(15) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by Programming Language recommended for aspiring Data Scientist<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q8','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Programming Language',weight = 'bold', fontsize = 20)
plt.title('Degree distribution of women by Programming Language recommended for aspiring Data Scientist',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q8','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Programming Language',weight = 'bold', fontsize = 20)
plt.title('Degree distribution of women by Programming Language recommended for aspiring Data Scientist',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:
##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women in all degrees recommended <strong> Python </strong> programming language for aspiring Data Scientists
2. Most of the women who recommended <strong> C,C++,Java,MATLAB </strong> programming languages for aspiring Data Scientists have attined/want to do <strong> Bachelor's degree </strong>.
3. Most of the women who recommended <strong> Java Script,Julia,None,Other,Python,R,SQL </strong> programming languages for aspiring Data Scientists have attined/want to do <strong> Master's degree </strong>.
4. In total survey only one women recommended <strong> Swift </strong> programming language for aspiring Data Scientists and she attained/want to do <strong> Doctoral Degree </strong>.
5. In total survey only 5 women recommended <strong> Bash </strong> programming language for aspiring Data Scientists, in that majority of women have attained/want to do <strong> Some college/University study without earning a Bachelor's degree </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">VSCode vs PyCharm vs Jupyter Notebook(IDE's used on Regular Basis) in all Degrees of Women<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q4']).size()) 
              for var in {'Q9_Part_4','Q9_Part_5','Q9_Part_11'}}
multi_table([df_groupby['Q9_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q9_Part_5'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q9_Part_11'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed VSCode,PyCharm and Jupyter Notebook only these 3 because these are the most choosed option.


1. VSCode is most choosed by the women who attained/want to do <strong> Bachelor's degree(705) </strong> and less choosed by the women who attained/want to do <strong> Professional Doctorate(12) </strong>.
2. PyCharm is most choosed by the women who attained/want to do <strong> Bachelor's degree(507) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(7) </strong>.
3. Jupyter Notebook is most choosed by the women who attained/want to do <strong> Master's degree(1264) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(18) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Kaggle vs Colab vs Google Cloud Datalab(hosted notebooks used on Regular Basis) in all Degrees of Women<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q4']).size()) 
              for var in {'Q10_Part_1','Q10_Part_2','Q10_Part_11'}}
multi_table([df_groupby['Q10_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q10_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q10_Part_11'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Kaggle Notebooks,Colab Notebooks and Google Cloud Datalab only these 3 because these are the most choosed option.


1. Kaggle Notebooks is most choosed by the women who attained/want to do <strong> Master's degree(677) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(5) </strong>.
2. PyCharm is most choosed by the women who attained/want to do <strong> Bachelor's degree(663) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(8) </strong>.
3. Jupyter Notebook is most choosed by the women who attained/want to do <strong> Bachelor's degree(133) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(3) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by Specialized Software used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q11','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Specialized Software',weight = 'bold', fontsize = 20)
plt.title('Degree Distribution of women by Specialized Software used on regular basis',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q11','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Specialized Software',weight = 'bold', fontsize = 20)
plt.title('Degree Distribution of women by Specialized Software used on regular basis',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:
##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women of all degrees are using <strong> Laptop </strong> as specialized software used on regular basis
2. Most of the women who are using <strong> A cloud computing platform (AWS, Azure, GCP, hosted notebooks, etc),A deep learning workstation (NVIDIA GTX, LambdaLabs, etc),A personal computer / desktop,None,Other </strong> as specialized software used on regular basis have attained/want to do <strong> Master's Degree </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by Data Visualization Libraries used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q4']).size()) 
              for var in {'Q14_Part_1','Q14_Part_2','Q14_Part_3','Q14_Part_4'}}
multi_table([df_groupby['Q14_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q14_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q14_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q14_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Matplotlib,Seaborn,Plotly/Plotly Express and Ggplot/ggplot2 only these 4 because these are the most choosed option.


1. Matplotlib is most choosed by the women who attained/want to do <strong> Master's degree(1242) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(16) </strong>.
2. Seaborn is most choosed by the women who attained/want to do <strong> Master's degree(921) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(9) </strong>.
3. Plotly/Plotly Express is most choosed by the women who attained/want to do <strong> Master's degree(446) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(3) </strong>.
4. Ggplot/ggplot2 is most choosed by the women who attained/want to do <strong> Master's degree(539) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(3) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by No. of years Machine Learning Methods used<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q15','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('No. of Years',weight = 'bold', fontsize = 20)
plt.title('Degree distribution of women by No. of years Machine Learning Methods used',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q15','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('No. of Years',weight = 'bold', fontsize = 20)
plt.title('Degree distribution of women by No. of years Machine Learning Methods used',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:
##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women of all degrees are used/using Machine learning methods <strong> lessthan 1 year </strong>
2. Most of the women who are using/used Machine learning methods <strong> 1-10 years</strong> have attained/want to do <strong> Master's Degree </strong>
3. Most of the women who are using/used Machine learning methods <strong> 10-20+ years</strong> have attained/want to do <strong> Doctoral Degree </strong>
4. Most of the women who not used/using Machine learning Methods or using/used Machine learning methods <strong> lessthan 1 year</strong> have attained/want to do <strong> Bachelo's Degree </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by Machine Learning Frameworks used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q4']).size()) 
              for var in {'Q16_Part_1','Q16_Part_2','Q16_Part_3','Q16_Part_4','Q16_Part_7'}}
multi_table([df_groupby['Q16_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q16_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q16_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q16_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q16_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Scikit-learn,TensorFlow,Keras,PyTorch and Xgboost only these 5 because these are the most choosed option.


1. Scikit-learn is most choosed by the women who attained/want to do <strong> Master's degree(1002) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(9) </strong>.
2. TensorFlow is most choosed by the women who attained/want to do <strong> Master's degree(566) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(8) </strong>.
3. Keras is most choosed by the women who attained/want to do <strong> Master's degree(484) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(6) </strong>.
4. PyTorch is most choosed by the women who attained/want to do <strong> Master's degree(339) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(5) </strong>.
5. Xgboost is most choosed by the women who attained/want to do <strong> Master's degree(383) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(3) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by Machine Learning Algorithms used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q4']).size()) 
              for var in {'Q17_Part_1','Q17_Part_2','Q17_Part_3','Q17_Part_7'}}
multi_table([df_groupby['Q17_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q17_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q17_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q17_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed  Linear or Logistic Regression,Decision Trees or Random Forests,Gradient Boosting Machines (xgboost, lightgbm, etc) and Convolutional Neural Networks only these 4 because these are the most choosed option.


1. Linear or Logistic Regression is most choosed by the women who attained/want to do <strong> Master's degree(1031) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(9) </strong>.
2. Decision Trees or Random Forests is most choosed by the women who attained/want to do <strong> Master's degree(909) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(10) </strong>.
3. Gradient Boosting Machines (xgboost, lightgbm, etc) is most choosed by the women who attained/want to do <strong> Master's degree(479) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(5) </strong>.
4. Convolutional Neural Networks is most choosed by the women who attained/want to do <strong> Master's degree(436) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(7) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by Current Employer/ Contract<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q20','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(18, 12))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Current Employer/ contract',weight = 'bold', fontsize = 20)
plt.title('Degree distribution of women by Current Employer/ Contract',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q20','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(18, 12))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Current Employer/ contract',weight = 'bold', fontsize = 20)
plt.title('Degree distribution of women by Current Employer/ Contract',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:
##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women who attained/want to do <strong> Bachelor's Degree, Master's Degree, Some college/University study without earning a abachelor's degree </strong> have Current Employer/Contract as <strong> Computers/Technology </strong>.
2. Most of the women who attained/want to do <strong> Doctoral Degree,I prefer not to answer, No formal education past high school, professional doctorate </strong> have Current Employer/Contract as<strong> Academics/Education </strong>.
3. Most of the people who have Current Employer/Contract as <strong> Accounting/Finance,Broadcasting/Communications,Computers/Technology,Energy/Mining,Government/Public Service,Hospitality/Entertainment/Sports,Insurance/Risk Assessment,Manufacturing/Fabrication,Marketing/CRM,Medical/Pharmaceutical,Military/Security/Defense, Non-profit/Service,Online Business/Internet-based Sales,Online Service/Internet-based Services,Retail/Sales,Shipping/Transportation </strong> have attained/want to do <strong> Master's degree </strong>
4. Most of the people who have Current Employer/Contract as <strong> Academics/Education </strong> have attained/want to do <strong> Doctoral degree </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by Current Yearly Compensation <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q25','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(20, 16))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Compensation in USD', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Degrees of women',weight = 'bold', fontsize = 20)
plt.title('Degree distribution of women by Current Yearly Compensation',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q25','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(20, 16))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Compensation in USD', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Degrees of women',weight = 'bold', fontsize = 20)
plt.title('Degree distribution of women by Current Yearly Compensation',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:
##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women of all degrees are currently earning <strong> 0-999 USD </strong> every year.
2. Most of the women who are earning <strong> 0-999 USD,1,000-1,999 USD,10,000-14,999 USD, 100,000-124,999USD,125,000-149,999 USD, 15,000-19,999 USD,150,000-199,999 USD, 2,000-2,999 USD, 20,000-24,999 USD, 200,000-249,999 USD, 25,000-29,999 USD, 250,000-299,999 USD, 3,000-3,999 USD, 30,000-39,999 USD </strong> have attained/want to do <strong> Master's Degree </strong>.
3. Most of the women who are earning <strong> 5,000 - 7,499 USD, > 1,000,000 USD </strong> have attained/want to do <strong> Bachelor's Degree </strong>.
4. 3. Most of the women who are earning <strong> 500,000-999,999 USD, 300,000-499,999 USD </strong> have attained/want to do <strong> Doctoral Degree </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by Money spent on learning Machine Learning/ Cloud Computing services in the past 5 years <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q26','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Compensation in USD',weight = 'bold', fontsize = 20)
plt.title('Degree distribution of women by Money spent on learning Machine Learning/ Cloud Computing services in the past 5 years',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q26','Q4']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Degrees of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Compensation in USD',weight = 'bold', fontsize = 20)
plt.title('Degree distribution of women by Money spent on learning Machine Learning/ Cloud Computing services in the past 5 years',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:
##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women of all degrees doesnot spend any money for learning Machine Learning/ Cloud Computing services in the past 5 years
2. Most of women who spend <strong> 0-100,000 or more USD</strong> or learning Machine Learning/ Cloud Computing services in the past 5 years have attained/want to do <strong> Master's Degree </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by public application to share your data analysis or machine learning <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q4']).size()) 
              for var in {'Q39_Part_4','Q39_Part_6','Q39_Part_7','Q39_Part_9'}}
multi_table([df_groupby['Q39_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q39_Part_6'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q39_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q39_Part_9'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed  GitHub, Kaggle, Colab and I do not share my work publicly only these 4 because these are the most choosed option.


1. GitHub is most choosed by the women who attained/want to do <strong> Master's degree(322) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(4) </strong>.
2. Kaggle is most choosed by the women who attained/want to do <strong> Master's degree(197) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(2) </strong>.
3. Colab is most choosed by the women who attained/want to do <strong> Master's degree(112) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(2) </strong>.
4. I do not share my work publicly is most choosed by the women who attained/want to do <strong> Master's degree(221) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(2) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by platforms they begun or completed data science courses<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q4']).size()) 
              for var in {'Q40_Part_1','Q40_Part_3','Q40_Part_7','Q40_Part_10'}}
multi_table([df_groupby['Q40_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q40_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q40_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q40_Part_10'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed  Coursera, Kaggle Learn Courses, Udemy and University Courses (resulting in a university degree) only these 4 because these are the most choosed option.


1. Coursera is most choosed by the women who attained/want to do <strong> Master's degree(718) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(9) </strong>.
2. Kaggle Learn Courses is most choosed by the women who attained/want to do <strong> Master's degree(601) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(7) </strong>.
3. Udemy is most choosed by the women who attained/want to do <strong> Master's degree(465) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(7) </strong>.
4. University Courses (resulting in a university degree) is most choosed by the women who attained/want to do <strong> Master's degree(470) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(4) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Degree distribution of women by favorite media sources that report on data science topics<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q4']).size()) 
              for var in {'Q42_Part_4','Q42_Part_6','Q42_Part_8'}}
multi_table([df_groupby['Q42_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q42_Part_6'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q42_Part_8'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed  Kaggle (notebooks, forums, etc), YouTube (Kaggle YouTube, Cloud AI Adventures, etc) and Blogs (Towards Data Science, Analytics Vidhya, etc) only these 3 because these are the most choosed option.


1. Kaggle (notebooks, forums, etc) is most choosed by the women who attained/want to do <strong> Master's degree(795) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(5) </strong>.
2. YouTube (Kaggle YouTube, Cloud AI Adventures, etc) is most choosed by the women who attained/want to do <strong> Master's degree(674) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(9) </strong>.
3. Blogs (Towards Data Science, Analytics Vidhya, etc) is most choosed by the women who attained/want to do <strong> Master's degree(645) </strong> and less choosed by the women who attained/want to do <strong> No formal education past high school(6) </strong>.

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Analysis of women in 2021 with respect to Current Role<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Woman count in Current Role<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
x = df[df['Q2'] == 'Woman']['Q5'].value_counts().keys().tolist()
y = df[df['Q2'] == 'Woman']['Q5'].value_counts().values.tolist()
fig = plt.figure(figsize=(10, 6))
sns.set(style="dark", color_codes=True)
pal = sns.color_palette("YlGnBu", len(x))
ax = sns.barplot(x=x,y=y,palette=pal)
for p in ax.patches:
        ax.annotate('{:.0f}'.format(p.get_height()), (p.get_x()+0.3, p.get_height()),
                    ha='center', va='bottom',
                    color= 'black')
plt.suptitle ("Women in Current Role",weight = 'bold')
plt.xticks(rotation=90,weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women involved in <strong> 2021 </strong>survey are <strong> Students(1574) </strong>
2. Women with Current Role  <strong> Data Scientist(584) </strong> stands in 2nd place.
3. Very less women with Current Role <strong> Developer Relations/Advocacy(16) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Role Distribution of women by Age<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
from matplotlib.patches import Rectangle
z=df[df['Q2']=='Woman'].groupby(['Q1','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black',annot_kws={"fontsize":12}, fmt='.3f', cbar=False)
plt.ylabel('Age Groups', weight = 'bold', fontsize = 20)
plt.xlabel('Current Roles of women',weight = 'bold', fontsize = 20)
plt.title('Current Role Distribution of women by country',weight='bold', fontsize = 20)

columns_text = z.columns

column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)

for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.yticks(fontsize=14,weight = 'bold',rotation = 45)
plt.xticks(fontsize=14,weight = 'bold')
plt.show()

In [ ]:
from matplotlib.patches import Rectangle
z=df[df['Q2']=='Woman'].groupby(['Q1','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black',annot_kws={"fontsize":12}, fmt='.3f', cbar=False)
plt.ylabel('Age Groups', weight = 'bold', fontsize = 20)
plt.xlabel('Current Roles of women',weight = 'bold', fontsize = 20)
plt.title('Current Role Distribution of women by country',weight='bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.yticks(fontsize=14,weight = 'bold',rotation = 45)
plt.xticks(fontsize=14,weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women with Current Role <strong> Business Analyst, Currently not employed, DBA/Database Engineer,Data Analyst, Data Engineer,Data Scientist,Developer Relations/Advocacy, Machine Learning Engineer, Other,Product Manager </strong> are of age group <strong> 25-29 </strong>.
2. Most of the women with Current Role <strong> Program/Project Manager,Research Scientist </strong> are of age group <strong> 30-34 </strong>.
3. Most of the women with Current Role <strong> Software Engineer, Statistician </strong> are of age group <strong> 22-24 </strong>.
4. Most of the women <strong> Students </strong> are of age group <strong> 18-21 </strong>.
5. In age group <strong> 18-29 </strong> most of the women are <strong> Students(837) </strong>, but women in age groups 22-29 are pretty much invloved in jobs.
6. In age group <strong> 30-44 </strong> most of the women are working as <strong> Data Scientist(383) </strong>.
7. In age group <strong> 45-69 </strong> most of the women are working in <strong> Other fields(189) </strong> which are not mentioned in survey options.
8. In age group <strong> 70+ </strong> most of the women are <strong> Currently not Employed </strong>
9. In age group <strong> 25-29 </strong> most of them are students but number is not much domiant like in case of age group 18-21, many women of age group <strong> 25-29 </strong> are working in <strong> Data Science related fields </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Role Distribution of women by country<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
from matplotlib.patches import Rectangle
z=df[df['Q2']=='Woman'].groupby(['Q3','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 24))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black',annot_kws={"fontsize":12}, fmt='.3f', cbar=False)
plt.ylabel('Country', weight = 'bold', fontsize = 20)
plt.xlabel('Current Roles of women',weight = 'bold', fontsize = 20)
plt.title('Current Role Distribution of women by country',weight='bold', fontsize = 20)

columns_text = z.columns

column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)

for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.yticks(fontsize=14,weight = 'bold')
plt.xticks(fontsize=14,weight = 'bold')
plt.show()

#### Observation:
##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women with current job as <strong> Business Analyst,Currently not employed,DBA/Database Engineer,Data Analyst, Data Engineer,Data Scientist,Developer Relations/Advocacy, Machine Learning Engineer,Other,Research Scientist,Statistician,Software Engineer,Student </strong> are <strong> Indians </strong>.
2. Most of the women with current job as <strong> Product Manager,Program/Project Manager </strong> are from <strong> USA </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Role distribution of women by Coding Experience<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q6','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(18, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Coding Experience',weight = 'bold', fontsize = 14)
plt.title('Current Role Distribution of women by Coding Experience',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold',rotation = 45)
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q6','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(18, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Coding Experience',weight = 'bold', fontsize = 14)
plt.title('Current Role Distribution of women by Coding Experience',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold',rotation = 45)
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:
##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women with Current Job <strong> Data Engineer,Data Scientist, Machine Learning Engineer,Research Scientist,Statistician,Software Engineer,Student </strong> have coding experience <strong> 1-3 years </strong>
2. Most of the women with Current Job <strong> Developer Relations/Advocacy </strong> have coding experience <strong> 10-20 years </strong>
3. Most of the women with Current Job <strong> DBA/Database Engineer </strong> have coding experience <strong> 3-5 years </strong>
4. Most of the women with Current Job <strong> Business Analyst,Currently not employed,Data Analyst,Other, Product Manager,Program/Project Manager </strong> have coding experience <strong> lessthan 1 year </strong>
5. Most of the women who has coding experience <strong> 5-20+ years </strong> are working as <strong> Data Scientist </strong>
6. Most of the women who has coding experience <strong> 0-5 years </strong> are <strong> Students </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Python vs R vs SQL(Programming Language used on regular basis) in all Current Roles of Women<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q5']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Python is most choosed by the women <strong> Students (1363) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(10) </strong>.
2. R is most choosed by the women <strong> Students (359) </strong> and less choosed by the women with Current Role <strong> DBA/Database Engineer(1) </strong>.
3. SQL is most choosed by the women <strong> Students (1363) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(10) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Role distribution of women by Programming Language recommended for aspiring Data Scientist<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q8','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Programming Language',weight = 'bold', fontsize = 20)
plt.title('Current Roles distribution of women by Programming Language recommended for aspiring Data Scientist',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q8','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap="pink", annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Programming Language',weight = 'bold', fontsize = 20)
plt.title('Current Roles distribution of women by Programming Language recommended for aspiring Data Scientist',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women of all Current Roles recommended <strong> Python </strong> programming language for aspiring Data Scientists.
2. Most of the women who recommended <strong> C,C++,Java,Java script,MATLAB,Python,R,SQL,Julia,Bash </strong> programming languages for aspiring Data Scientists are <strong> Students </strong>.
3. Most of the women who recommended <strong> Julia </strong> programming language for aspiring Data Scientists are of with Current Role<strong> Data Analyst </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">VSCode vs PyCharm vs Jupyter Notebook(IDE's used on Regular Basis) in all Current Roles of Women<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q5']).size()) 
              for var in {'Q9_Part_4','Q9_Part_5','Q9_Part_11'}}
multi_table([df_groupby['Q9_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q9_Part_5'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q9_Part_11'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed VSCode,PyCharm and Jupyter Notebook only these 3 because these are the most choosed option.


1. VsCode is most choosed by the women <strong> Students (608) </strong> and less choosed by the women with Current Role <strong>DBA/Database Engineer(3) </strong>.
2. PyCharm is most choosed by the women <strong> Students (471) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(2) </strong>.
3. Jupyter Notebook is most choosed by the women <strong> Students (1010) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(9) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Kaggle vs Colab vs Google Cloud Datalab(hosted notebooks used on Regular Basis) in all Current Roles of Women<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q5']).size()) 
              for var in {'Q10_Part_1','Q10_Part_2','Q10_Part_11'}}
multi_table([df_groupby['Q10_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q10_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q10_Part_11'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Kaggle Notebooks,Colab Notebooks and Goggle Cloud Datalab only these 3 because these are the most choosed option.


1. Kaggle Notebooks is most choosed by the women <strong> Students (549) </strong> and less choosed by the women with Current Role <strong>DBA/Database Engineer(3) </strong>.
2. Colab Notebooks is most choosed by the women <strong> Students (598) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(3), DBA/Database Engineer(3)</strong>.
3. Google Cloud Datalab is most choosed by the women <strong> Students (109) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(1) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Roles distribution of women by Specialized Software used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q11','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(18, 12))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Specialized Software',weight = 'bold', fontsize = 20)
plt.title('Current Roles Distribution of women by Specialized Software used on regular basis',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q11','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(18, 12))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Specialized Software',weight = 'bold', fontsize = 20)
plt.title('Current Roles Distribution of women by Specialized Software used on regular basis',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women of all Current roles are using <strong> Laptop </strong> as their specialized software.
2. Most of the women who use <strong> A deep learning workstation (NVIDIA GTX, LambdaLabs, etc),A laptop,A personal computer / desktop </strong> as their specialized software are <strong> Students </strong>.
3. Most of the women who use <strong> A cloud computing platform (AWS, Azure, GCP, hosted notebooks, etc) </strong> as their specialized software are of Current Role <strong> Data Scientist </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Role distribution of women by Data Visualization Libraries used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q5']).size()) 
              for var in {'Q14_Part_1','Q14_Part_2','Q14_Part_3','Q14_Part_4'}}
multi_table([df_groupby['Q14_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q14_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q14_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q14_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Matplotlib,Seaborn,Plotly/Plotly Express and Ggplot/ggplot2 only these 4 because these are the most choosed option.


1. Matplotlib is most choosed by the women <strong> Students (953) </strong> and less choosed by the women with Current Role <strong>Developer Relations/Advocacy(6) </strong>.
2. Seaborn is most choosed by the women <strong> Students (620) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(4)</strong>.
3. Plotly/Plotly Express is most choosed by the women <strong> Students (246) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(3), DBA/Database Engineer(3) </strong>.
4. Ggplot/ggplot2 is most choosed by the women <strong> Students (280) </strong> and less choosed by the women with Current Role <strong> DBA/Database Engineer(3) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Role distribution of women by No. of years Machine Learning Methods used<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q15','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('No. of Years',weight = 'bold', fontsize = 20)
plt.title('Current Role distribution of women by No. of years Machine Learning Methods used',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q15','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('No. of Years',weight = 'bold', fontsize = 20)
plt.title('Current Role distribution of women by No. of years Machine Learning Methods used',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women with Current Role <strong> DBA/Database Engineer, Developer Relations/Advocacy </strong> have/are not used/using Machine learning Methods.
2. Most of the women with Current Role <strong> Business Analyst,Currently not employed,Data Analyst,Data Engineer,Data Scientist,Other,Machine Learning Engineer, Product Manager,Program/Project Manager,Research Scientist, Software Engineer,Statistician,Students </strong> have/are used/using Machine learning Methods <strong> lessthan 1 year </strong>.
3. Most of the women who has coding experience <strong> 2-20+ years </strong> are working as a <strong> Data Scientist </strong>.
4.  Most of the women who has coding experience <strong> 0-2 years </strong> are <strong> Students </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Roles distribution of women by Machine Learning Frameworks used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q5']).size()) 
              for var in {'Q16_Part_1','Q16_Part_2','Q16_Part_3','Q16_Part_4','Q16_Part_7'}}
multi_table([df_groupby['Q16_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q16_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q16_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q16_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q16_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Scikit-learn,TensorFlow,keras,PyTorch and Xgboost only these 5 because these are the most choosed option.


1. Scikit-learn is most choosed by the women <strong> Students (643) </strong> and less choosed by the women with Current Role <strong>Developer Relations/Advocacy(4) </strong>.
2. TensorFlow is most choosed by the women <strong> Students (416) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(4),DBA/Database Engineer(4)</strong>.
3. keras is most choosed by the women <strong> Students (363) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(3), DBA/Database Engineer(3) </strong>.
4. PyTorch is most choosed by the women <strong> Students (246) </strong> and less choosed by the women with Current Role <strong> DBA/Database Engineer(2) </strong>.
5. Xgboost is most choosed by the women of Current Role<strong> Data Scientist (643) </strong> and less choosed by the women with Current Role <strong>Developer Relations/Advocacy(2) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Roles distribution of women by Machine Learning Algorithms used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q5']).size()) 
              for var in {'Q17_Part_1','Q17_Part_2','Q17_Part_3','Q17_Part_7'}}
multi_table([df_groupby['Q17_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q17_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q17_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q17_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed only Linear or Logistic Regression,Decision Trees or Random Forests,Gradient Boosting Machines (xgboost, lightgbm, etc) and Convolutional Neural Networks these 4 because these are the most choosed option.


1. Linear or Logistic Regression is most choosed by the women <strong> Students (677) </strong> and less choosed by the women with Current Role <strong>Developer Relations/Advocacy(5) </strong>.
2. Decision Trees or Random Forests is most choosed by the women <strong> Students (577) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(5)</strong>.
3. Gradient Boosting Machines (xgboost, lightgbm, etc) is most choosed by the women of Current Role<strong> Data Scientist (266) </strong> and less choosed by the women with Current Role <strong>Developer Relations/Advocacy(3),DBA/Database Engineer(3) </strong>.
4. Convolutional Neural Networks is most choosed by the women <strong> Students (320) </strong> and less choosed by the women with Current Role <strong> DBA/Database Engineer(1) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Roles distribution of women by Current Employer/ Contract<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q20','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Current Employer/ contract',weight = 'bold', fontsize = 20)
plt.title('Current Roles distribution of women by Current Employer/ Contract',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q20','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Current Employer/ contract',weight = 'bold', fontsize = 20)
plt.title('Current Roles distribution of women by Current Employer/ Contract',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women of Current Role <strong> Business Analyst,DBA/Database Engineer,Data Engineer,Data Scientist,DBA/Database Engineer,Machine Learning Engineering, Product Manager,Program/Project Manager, Software Engineer,Students </strong> have Current Employer/Contract as <strong> Computers/Technology </strong>
2. Most of the women of Current Role <strong> Data Analyst, Research Scientist, Statistician </strong> have Current Employer/Contract as <strong> Academics/Education </strong>
3. Most of the women of Current Employer/Contract <strong> Accounting/Finance,Broadcasting/Communications,Government/Public Service,Hospitality/Entertainment/Sports,Marketing/CRM,Online Business/Internet-based Sales,Online Service/Internet-based Services,Retail/Sales,Shipping/Transportation </strong> have Current Role as <strong> Data Analyst </strong>
4. Most of the women of Current Employer/Contract <strong> Energy/Mining,Insurance/Risk Assessment,Manufacturing/Fabrication,Medical/Pharmaceutical,Military/Security/Defense</strong> have Current Role as <strong> Data Scientist </strong>
5. Most of the women of Current Employer/Contract <strong> Academics/Education </strong> have Current Role as <strong> Research Scientist </strong>
6. Most of the women of Current Employer/Contract <strong> Computers/Technology </strong> have Current Role as <strong> Software Engineer </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Roles distribution of women by Current Yearly Compensation <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q25','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(20, 16))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Compensation in USD',weight = 'bold', fontsize = 20)
plt.title('Current Roles distribution of women by Current Yearly Compensation',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q25','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(20, 16))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Compensation in USD',weight = 'bold', fontsize = 20)
plt.title('Current Roles distribution of women by Current Yearly Compensation',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women of all Current Roles are earning <strong> 0-999 USD </strong> as their yearly compensation.
2. Most of the womem who earn <strong> 500,000-999,999 USD, 1,000-1,999 USD, 10,000-14,999 USD, 15,000 - 19,999 USD, 25,000 - 29,999 USD, 3,000 - 3,999 USD,300,000-499,999 USD, 4,000-4,999 USD, 40,000-49,999 USD, 7,500-9,999 USD, 70,000-79,999 USD </strong> have current role <strong> Data Analyst </strong>.
3. Most of the womem who earn <strong> 0-999 USD, 100,000-124,999 USD, 125,000-149,999 USD, 150,000-199,999 USD, 2,000-2,999 USD, 20,000-24,999 USD, 200,000-249,999 USD, 30,000-39,999 USD, 60,000-69,999 USD, 80,000-89,999 USD, 90,000-99,999 USD</strong> have current role <strong> Data Scientist </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Roles distribution of women by Money spent on learning Machine Learning/ Cloud Computing services in the past 5 years <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q26','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
columns_text = z.columns
column_max = z.apply(lambda x: x, axis=1).idxmax(axis=0)
for col, variable in enumerate(columns_text):
    position = z.apply(lambda x: x, axis=1).index.get_loc(column_max[variable])
    ax.add_patch(Rectangle((col, position),1,1, fill=False, edgecolor='red', lw=3))
plt.ylabel('Compensation in USD',weight = 'bold', fontsize = 20)
plt.title('Current Roles distribution of women by Money spent on learning Machine Learning/ Cloud Computing services in the past 5 years',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

In [ ]:
z=df[df['Q2']=='Woman'].groupby(['Q26','Q5']).size().unstack().fillna(0).astype('int16')
fig, ax = plt.subplots(figsize=(16, 10))
sns.heatmap(z.apply(lambda x: x, axis=1), xticklabels=True, yticklabels=True, cmap='pink', annot=True, linewidths=0.005, linecolor='black', annot_kws={"fontsize":14}, fmt='.3f', cbar=False)
plt.xlabel('Current Roles of women', weight = 'bold', fontsize = 20)
index_text = z.index    
row_max = z.apply(lambda x: x, axis=1).idxmax(axis=1)
for row, index in enumerate(index_text):
    position = z.apply(lambda x: x, axis=1).columns.get_loc(row_max[index])
    ax.add_patch(Rectangle((position, row),1,1, fill=False, edgecolor='blue', lw=3))
plt.ylabel('Compensation in USD',weight = 'bold', fontsize = 20)
plt.title('Current Roles distribution of women by Money spent on learning Machine Learning/ Cloud Computing services in the past 5 years',weight='bold', fontsize = 20)
plt.yticks(fontsize=14, weight = 'bold')
plt.xticks(fontsize=14, weight = 'bold')
plt.show()

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 


1. Most of the women of all Current Roles didn't spent any money on learning Machine Learning/ Cloud Computing services in the past 5 years
2. Most of the women who spent <strong> 1-100,000 or more USD </strong> have Current Role <strong> Data Scientist </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Roles distribution of women by public application to share your data analysis or machine learning <strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q5']).size()) 
              for var in {'Q39_Part_4','Q39_Part_6','Q39_Part_7','Q39_Part_9'}}
multi_table([df_groupby['Q39_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q39_Part_6'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q39_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q39_Part_9'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed GitHub,Kaggle,Colab,PyTorch and Xgboost only these 4 because these are the most choosed option.


1. GitHub is most choosed is most choosed by the women of Current Role<strong> Data Scientist (172) </strong> and less choosed by the women with Current Role <strong>DBA/Database Engineer(2) </strong>.
2. Kaggle is most choosed by the women of Current Role<strong> Data Scientist (91) </strong> and less choosed by the women with Current Role <strong>Developer Relations/Advocacy(2), Product Manager(2) </strong>.
3. Colab is most choosed by the women of Current Role<strong> Data Scientist (61) </strong> and less choosed by the women with Current Role <strong>Developer Relations/Advocacy(1), Product Manager(1) </strong>.
4. I do not share my work publicly is most choosed by the women of Current Role<strong> Data Scientist (94) </strong> and less choosed by the women with Current Role <strong>Developer Relations/Advocacy(1) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Roles distribution of women by platforms they begun or completed data science courses<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q5']).size()) 
              for var in {'Q40_Part_1','Q40_Part_3','Q40_Part_7','Q40_Part_10'}}
multi_table([df_groupby['Q40_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q40_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q40_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'),df_groupby['Q40_Part_10'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Coursera, Kaggle Learn Courses,Udemy and University Courses (resulting in a university degree) only these 4 because these are the most choosed option.


1. Coursera is most choosed by the women <strong> Students (460) </strong> and less choosed by the women with Current Role <strong>Developer Relations/Advocacy(4),DBA/Database Engineer(4) </strong>.
2. Kaggle Learn Courses is most choosed by the women <strong> Students (423) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(4)</strong>.
3. Udemy is most choosed by the women <strong> Students (287) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(4) </strong>.
4. University Courses (resulting in a university degree) is most choosed by the women <strong> Students (357) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(4),DBA/Database Engineer(4) </strong>.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Current Roles distribution of women by favorite media sources that report on data science topics<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[df['Q2'] == 'Woman'].groupby([var, 'Q5']).size()) 
              for var in {'Q42_Part_4','Q42_Part_6','Q42_Part_8'}}
multi_table([df_groupby['Q42_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q42_Part_6'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q42_Part_8'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Kaggle (notebooks, forums, etc), YouTube (Kaggle YouTube, Cloud AI Adventures, etc), Blogs (Towards Data Science, Analytics Vidhya, etc) only these 3 because these are the most choosed option.


1. Kaggle (notebooks, forums, etc) is most choosed by the women <strong> Students (504) </strong> and less choosed by the women with Current Role <strong>Developer Relations/Advocacy(6) </strong>.
2. YouTube (Kaggle YouTube, Cloud AI Adventures, etc) is most choosed by the women <strong> Students (500) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(6)</strong>.
3. Blogs (Towards Data Science, Analytics Vidhya, etc) is most choosed by the women <strong> Students (374) </strong> and less choosed by the women with Current Role <strong> Developer Relations/Advocacy(2) </strong>.

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of all age groups by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of age group 18-21 by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q1'] == '18-21')].groupby([var,'Q1','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of age group <strong> 18-21 </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(109) </strong> as yearly compensation and less number of women are earning <strong> 10,000 -14,999 USD(1), 60,000-69,999 USD(1), 200,000-249,999 USD(1) </strong> as yearly compensation.
2. Most of the women of age group <strong> 18-21 </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(17) </strong> as yearly compensation and less number of women are earning <strong> 10,000 - 14,999 USD(1), 60,000-69,999 USD(1), 200,000-249,999 USD(1) </strong> as yearly compensation.
3. Most of the women of age group <strong> 18-21 </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(53) </strong> as yearly compensation and less number of women are earning <strong> 200,000-249,999 USD(1) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>


If we compare women of age group <strong> 18-21 </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the them on regular basis and how much they are earning,it would look like:


<strong> python > SQL> R </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of age group 22-24 by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q1'] == '22-24')].groupby([var,'Q1','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of age group <strong> 22-24 </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(147) </strong> as yearly compensation and less number of women are earning <strong> > 1,000,000 USD(1) </strong> as yearly compensation.
2. Most of the women of age group <strong> 22-24 </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(41) </strong> as yearly compensation and less number of women are earning <strong> 100,000-124,999 USD (1), 20,000 - 24,999 USD(1), 300,000-499,999 USD (1),50,000-59,999(1),80,000-89,999(1)</strong> as yearly compensation.
3. Most of the women of age group <strong> 22-24 </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(85) </strong> as yearly compensation and less number of women are earning <strong> 60,000-69,999 USD(1), 80,000-89,999 USD (1) </strong> as yearly compensation.\
4. Here we can see one woman is earning <strong> morethan 1,000,000 USD </strong> she uses <strong> python </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> morethan 1,000,000 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>


If we compare women of age group <strong> 22-24 </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the languages on regular basis and how much they are earning, it would look like:<strong> python > SQL> R </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of age group 25-29 by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q1'] == '25-29')].groupby([var,'Q1','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of age group <strong> 25-29 </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(140) </strong> as yearly compensation and less number of women are earning <strong> 250,000 - 299,999 USD(1) </strong> as yearly compensation.
2. Most of the women of age group <strong> 25-29 </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(39) </strong> as yearly compensation and less number of women are earning <strong> 125,000-149,999 USD(1),150,000-199,999 USD(1)</strong> as yearly compensation.
3. Most of the women of age group <strong> 25-29 </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(77) </strong> as yearly compensation and less number of women are earning <strong> > 1,000,000 USD(1) </strong> as yearly compensation.\
4. Here we can see one woman is earning <strong> morethan 1,000,000 USD </strong> she uses <strong> SQL </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> morethan 1,000,000 USD </strong>


If we compare women of age group <strong> 25-29 </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the languages on regular basis and how much they are earning, it would look like:<strong> python > SQL> R </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of age group 30-34 by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q1'] == '30-34')].groupby([var,'Q1','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of age group <strong> 30-34 </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(72) </strong> as yearly compensation and less number of women are earning <strong> 250,000 - 299,999 USD(1), 300,000-499,999 USD (1) </strong> as yearly compensation.
2. Most of the women of age group <strong> 30-34 </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(20) </strong> as yearly compensation and less number of women are earning <strong> 200,000-249,999 USD (1)</strong> as yearly compensation.
3. Most of the women of age group <strong> 30-34 </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(27) </strong> as yearly compensation and less number of women are earning <strong> 250,000 - 299,999 USD(1), 300,000-499,999 USD (1) </strong> as yearly compensation.
4. Here we can see two woman are earning <strong> 300,000-499,999 USD </strong> one use <strong> SQL </strong> and another one use <strong> Python </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>



If we compare women of age group <strong> 30-34 </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the languages on regular basis and how much they are earning, it would look like:<strong> python > SQL> R </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of age group 35-39 by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q1'] == '35-39')].groupby([var,'Q1','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of age group <strong> 35-39 </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(49) </strong> as yearly compensation and less number of women are earning <strong> 200,000-249,999 USD (1), 300,000-499,999 USD (1), 500,000-999,999 USD(1) </strong> as yearly compensation.
2. Most of the women of age group <strong> 35-39 </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(9) </strong> as yearly compensation and less number of women are earning <strong> 100,000-124,999 USD (1), 300,000-499,999 USD (1), 40,000-49,999 USD (1)</strong> as yearly compensation.
3. Most of the women of age group <strong> 35-39 </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(27) </strong> as yearly compensation and less number of women are earning <strong> 200,000-249,999 USD (1), 300,000-499,999 USD (1), 4,000-4,999 USD (1) </strong> as yearly compensation.
4. Here we can see three woman are earning <strong> 300,000-499,999 USD </strong> one use <strong> R </strong>,one use <strong> SQL </strong> and another one use <strong> Python </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>



If we compare women of age group <strong> 35-39 </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the languages on regular basis and how much they are earning, it would look like:<strong> python > SQL> R </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of age group 40-44 by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q1'] == '40-44')].groupby([var,'Q1','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of age group <strong> 40-44 </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(30) </strong> as yearly compensation and less number of women are earning <strong> 125,000-149,999 USD (1), 300,000-499,999 USD (1), >1,000,000 USD(1) </strong> as yearly compensation.
2. Most of the women of age group <strong> 40-44 </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 100,000-124,999 USD(10) </strong> as yearly compensation and less number of women are earning <strong> 20,000-24,999 USD (1),60,000-69,999 USD (1),250,000-299,999 USD (1),300,000-499,999 USD (1), 500,000-999,999 USD (1),>1,000,000 USD(1)</strong> as yearly compensation.
3. Most of the women of age group <strong> 40-44 </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(13) </strong> as yearly compensation and less number of women are earning <strong> 125,000-149,999 USD (1) </strong> as yearly compensation.
4. Here we can see two woman are earning <strong> >1,000,000 USD </strong> one use <strong> R </strong> and another one use <strong> Python </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> >1,000,000 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> >1,000,000 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>


If we compare women of age group <strong> 40-44 </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the languages on regular basis and how much they are earning it would look like:<strong> python > R> SQL </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of age group 45-49 by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q1'] == '45-49')].groupby([var,'Q1','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of age group <strong> 45-49 </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(17) </strong> as yearly compensation and less number of women are earning <strong> 5,000-7,499 USD (1), 7,500-9,999 USD (1), 90,000-99,999 USD(1) </strong> as yearly compensation.
2. Most of the women of age group <strong> 45-49 </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(7) </strong> as yearly compensation and less number of women are earning <strong> 1,000-1,999 USD(1),100,000-124,999 USD(1),15,000-19,999 USD(1),200,000-249,999 USD(1),4,000-4,999 USD(1),40,000-49,999 USD(1), 50,000-59,999 USD (1)  </strong> as yearly compensation.
3. Most of the women of age group <strong> 45-49 </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(9) </strong> as yearly compensation and less number of women are earning <strong> 100,000-124,999 USD(1),15,000-19,999 USD(1),250,000-299,999 USD(1),60,000-69,999 USD(1),7,500-9,999 USD(1) </strong> as yearly compensation.
4. Here we can see two woman are earning <strong> >1,000,000 USD </strong> one use <strong> R </strong> and another one use <strong> Python </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 200,000-249,999	 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>


If we compare women of age group <strong> 45-49 </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the languages on regular basis and how much they are earning it would look like:<strong> SQL>python > R </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of age group 50-54 by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q1'] == '50-54')].groupby([var,'Q1','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of age group <strong> 50-54 </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 100,000-124,999 USD(9),150,000-199,999 USD(9) </strong> as yearly compensation and less number of women are earning <strong> 200,000-249,999 USD(1), 30,000-39,999 USD (1), 5,000-7,499 USD(1), 70,000-79,999 USD(1)   </strong> as yearly compensation.
2. Most of the women of age group <strong> 50-54 </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 150,000-199,999 USD(6) </strong> as yearly compensation and less number of women are earning <strong> 0-999 USD(1), 1,000-1,999 USD(1),15,000-19,999 USD(1),15,000-19,999 USD(1),20,000-24,999 USD(1),200,000-249,999 USD(1),3,000-3,999 USD(1),70,000-79,999 USD(1), 80,000-89,999 USD (1), 90,000-99,999 USD(1)  </strong> as yearly compensation.
3. Most of the women of age group <strong> 50-54 </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 100,000-124,999 USD(10) </strong> as yearly compensation and less number of women are earning <strong> 1,000-1,999	USD(1), 20,000-24,999 USD (1), 3,000-3,999 USD(1), 30,000-39,999 USD (1), 40,000-49,999 USD(1), 7,500-9,999 USD(1),70,000-79,999 USD(1), 80,000-89,999 USD (1) </strong> as yearly compensation.
4. Here we can see two woman are earning <strong> 200,000-249,999 USD </strong> one use <strong> R </strong> and another one use <strong> Python </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 200,000-249,999	 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>


If we compare women of age group <strong> 50-54 </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the languages on regular basis and how much they are earning it would look like:<strong> python >SQL> R </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of age group 55-59 by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q1'] == '55-59')].groupby([var,'Q1','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of age group <strong> 55-59 </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(8) </strong> as yearly compensation 
2. Most of the women of age group <strong> 55-59 </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(3) </strong> as yearly compensation 
3. Most of the women of age group <strong> 55-59 </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(5) </strong> as yearly compensation 
4. Here we can see four woman are earning <strong> 250,000-299,999 USD </strong> one use <strong> R </strong>, two of them use <strong> Python </strong> and another one use <strong> SQL </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 250,000-299,999	 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of age group 60-69 by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q1'] == '60-69')].groupby([var,'Q1','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of age group <strong> 60-69 </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(3) </strong> as yearly compensation 
2. Most of the women of age group <strong> 60-69 </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(3) </strong> as yearly compensation 
3. Most of the women of age group <strong> 60-69 </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(4) </strong> as yearly compensation 
4. Here we can see three woman are earning <strong> 250,000-299,999 USD </strong> one use <strong> R </strong>, one use <strong> Python </strong> and another one use <strong> SQL </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 250,000-299,999	 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of age group 70+ by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q1'] == '70+')].groupby([var,'Q1','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.

1. There are only 2 women of age group <strong> 70+ </strong> who use <strong> python </strong>programming language on regular basis and one of them earning <strong> 100,000-124,999	USD </strong> and another one earning <strong> 7,500-9,999 </strong> as their yearly compensation.
2. No women of age group <strong> 70+ </strong> who use <strong> R </strong> programming language on regular basis.
3. There are only 2 women of age group <strong> 70+ </strong> who use <strong> SQL </strong>programming language on regular basis and both of them are earning <strong> 100,000-124,999	USD </strong> as their yearly compensation.

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of all Degrees by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of Bachelors degree by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q4'] == 'Bachelor’s degree')].groupby([var,'Q4','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women who attained/want to do  <strong> Bachelor's Degree </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(218) </strong> as yearly compensation and less number of women are earning <strong> 250,000-299,999 USD(1), 300,000-499,999 USD(1)   </strong> as yearly compensation.
2. Most of the women who attained/want to do  <strong> Bachelor's Degree </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(37) </strong> as yearly compensation and less number of women are earning <strong>125,000-149,999 USD (1), 200,000-249,999 USD(1),250,000-299,999 USD(1), 300,000-499,999 USD(1)  </strong> as yearly compensation.
3. Most of the women who attained/want to do  <strong> Bachelor's Degree </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(120) </strong> as yearly compensation and less number of women are earning <strong>250,000-299,999 USD(1), 300,000-499,999 USD(1), morethan 1,000,000 USD(1)  </strong> as yearly compensation.
4. Here we can see one woman is earning <strong> morethan 1,000,000 USD </strong> and she use <strong> SQL </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 300,000-499,999	 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> morethan 1,000,000 USD </strong>


If we compare women who attained/want to do  <strong> Bachelor's Degree </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the languages on regular basis and how much they are earning it would look like:<strong> python >SQL> R </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of Masters degree by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q4'] == 'Master’s degree')].groupby([var,'Q4','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women who attained/want to do  <strong> Master's Degree </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(233) </strong> as yearly compensation and less number of women are earning <strong> 300,000-499,999 USD(1), morethan 1,000,000 USD(1)</strong> as yearly compensation.
2. Most of the women who attained/want to do  <strong> Master's Degree </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(73) </strong> as yearly compensation and less number of women are earning <strong>250,000-299,999 USD(1)</strong> as yearly compensation.
3. Most of the women who attained/want to do  <strong> Master's Degree </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(127) </strong> as yearly compensation and less number of women are earning <strong>300,000-499,999 USD(1)</strong> as yearly compensation.
4. Here we can see one woman is earning <strong> morethan 1,000,000 USD </strong> and she use <strong> Python </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> morethan 1,000,000 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>


If we compare women who attained/want to do  <strong> Master's Degree </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the languages on regular basis and how much they are earning it would look like:<strong> python >SQL> R </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of Doctoral degree by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q4'] == 'Doctoral degree')].groupby([var,'Q4','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women who attained/want to do  <strong> Doctoral Degree </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(69) </strong> as yearly compensation and less number of women are earning <strong> 500,000-999,999 USD(1)</strong> as yearly compensation.
2. Most of the women who attained/want to do  <strong> Doctoral Degree </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(20) </strong> as yearly compensation and less number of women are earning <strong>125,000-149,999 USD (1),200,000-249,999 USD (1),250,000-299,999 USD(1)</strong> as yearly compensation.
3. Most of the women who attained/want to do  <strong> Doctoral Degree </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(27) </strong> as yearly compensation and less number of women are earning <strong>,250,000-299,999 USD(1),80,000-89,999 USD(1), 15,000-19,999 USD (1)</strong> as yearly compensation.
4. Here we can see one woman is earning <strong> 500,000-999,999 USD </strong> and she use <strong> Python </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 500,000-999,999 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>


If we compare women who attained/want to do  <strong> Doctoral Degree </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the languages on regular basis and how much they are earning it would look like:<strong> python >SQL> R </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of Some college/university study without earning a bachelor’s degree by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q4'] == 'Some college/university study without earning a bachelor’s degree')].groupby([var,'Q4','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women who attained/want to do  <strong> Some college/university study without earning a bachelor’s degree </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(27) </strong> as yearly compensation.
2. Most of the women who attained/want to do  <strong> Some college/university study without earning a bachelor’s degree </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(5) </strong> as yearly compensation.
3. Most of the women who attained/want to do  <strong> Some college/university study without earning a bachelor’s degree </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(9) </strong> as yearly compensation.
4. Here we can see two woman are earning <strong> morethan 1,000,000 USD </strong>, one of them use <strong> Python </strong> and another uses <strong> R </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> morethan 1,000,000 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> morethan 1,000,000 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of No formal education past high school by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q4'] == 'No formal education past high school')].groupby([var,'Q4','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women who have<strong> No formal education past high school </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(2) </strong> as yearly compensation.
2. Most of the women who have<strong> No formal education past high school </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 30,000-39,999 USD(1) </strong> as yearly compensation.
3. Most of the women who have<strong> No formal education past high school </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(2) </strong> as yearly compensation.
4. Here we can see one woman is earning <strong> 150,000-199,999 USD </strong>and she use <strong> Python </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 30,000-39,999 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 60,000-69,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of Professional doctorate by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q4'] == 'Professional doctorate')].groupby([var,'Q4','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women who attained/want to do  <strong> Professional Doctorate </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(10) </strong> as yearly compensation.
2. Most of the women who attained/want to do  <strong> Professional Doctorate </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(4) </strong> as yearly compensation.
3. Most of the women who attained/want to do  <strong> Professional Doctorate </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(6) </strong> as yearly compensation.
4. Here we can see one woman is earning <strong> 500,000-999,999 USD </strong>and she use <strong> R </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 500,000-999,999 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 90,000-99,999 USD </strong>

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of all Current Roles by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women Students by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Student')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


<strong> Students </strong> are not earning.

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women Data Scientist by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Data Scientist')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of Current Role as <strong> Data Scientist </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(149) </strong> as yearly compensation and less number of women are earning <strong> 250,000-299,999 USD(1),300,000-499,999 USD(1)</strong> as yearly compensation.
2. Most of the women of Current Role as <strong> Data Scientist </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(42) </strong> as yearly compensation and less number of women are earning <strong>125,000-149,999 USD (2),50,000-59,999 USD(2)</strong> as yearly compensation.
3. Most of the women of Current Role as <strong> Data Scientist </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(71) </strong> as yearly compensation and less number of women are earning <strong>250,000-299,999 USD(1),300,000-499,999 USD(1)</strong> as yearly compensation.
4. Here we can see two woman are earning <strong> 300,000-499,999 USD </strong>,one of them use <strong> Python </strong> and another uses <strong> SQL </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>


If we compare women of Current Role as <strong> Data Scientist </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the languages on regular basis and how much they are earning it would look like:<strong> python >SQL> R </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women Students by Software Engineer used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Software Engineer')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of Current Role as <strong> Software Engineer </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(80) </strong> as yearly compensation and less number of women are earning <strong> 300,000-499,999 USD(1), morethan 1,000,000 USD(1)</strong> as yearly compensation.
2. Most of the women of Current Role as <strong> Software Engineer</strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(5) </strong> as yearly compensation.
3. Most of the women of Current Role as <strong> Software Engineer </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(53) </strong> as yearly compensation and less number of women are earning <strong>80,000-89,999 USD(1),90,000-99,999 USD(1),300,000-499,999 USD(1)</strong> as yearly compensation.
4. Here we can see one woman is earning <strong> morethan 1,000,000 USD </strong>and she use <strong> Python </strong> programming language on regular basis.
5. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> morethan 1,000,000 USD </strong>
6. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>
7. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>


If we compare women of Current Role as  <strong> Software Engineer </strong> on programming language used on regular basis, we can see that women who use python on regular basis are earning morethan women who use R and SQL and we can also see that women who use python are also more than women who use R,SQl.

If we arrange Python,R and SQL with respect to number of women using the languages on regular basis and how much they are earning it would look like:<strong> python >SQL> R </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women Data Analysts by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Data Analyst')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of Current Role as <strong> Data Analyst </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(109) </strong> as yearly compensation and less number of women are earning <strong> 200,000-249,999 USD(1)</strong> as yearly compensation.
2. Most of the women of Current Role as <strong> Data Analyst</strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(47) </strong> as yearly compensation and less number of women are earning <strong> 250,000-299,999 USD(1), 300,000-499,999 USD(1), 500,000-999,999 USD(1)</strong> as yearly compensation.
3. Most of the women of Current Role as <strong> Data Analyst </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(66) </strong> as yearly compensation and less number of women are earning <strong>150,000-199,999 USD(1), 200,000-249,999 USD(1)</strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong>300,000-499,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 500,000-999,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of Currently Not employed woman by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Currently not employed')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


Obvious that unemployed women have no earning(with respect to the jobs given survey)

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women Research Scientists by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Research Scientist')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of Current Role as <strong> Research Scientist </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(51) </strong> as yearly compensation.
2. Most of the women of Current Role as <strong> Research Scientist</strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(11) </strong> as yearly compensation.
3. Most of the women of Current Role as <strong> Research Scientist </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(18) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong>300,000-499,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women Machine Learning Engineers by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Machine Learning Engineer')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of Current Role as <strong> Research Scientist </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(60) </strong> as yearly compensation.
2. Most of the women of Current Role as <strong> Research Scientist</strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(4) </strong> as yearly compensation.
3. Most of the women of Current Role as <strong> Research Scientist </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(16) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong>500,000-999,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 100,000-124,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women Business Analysts by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Business Analyst')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of Current Role as <strong> Business Analyst </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(21) </strong> as yearly compensation.
2. Most of the women of Current Role as <strong> Business Analyst</strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(5),10,000-14,999 USD(5) </strong> as yearly compensation.
3. Most of the women of Current Role as <strong> Business Analyst </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(17) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong>125,000-149,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 125,000-149,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 125,000-149,999USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women Program/Project Manager by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Program/Project Manager')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of Current Role as <strong> Program/Project Manager </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(8) </strong> as yearly compensation.
2. Most of the women of Current Role as <strong> Program/Project Manager</strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 100,000-124,999 USD(3) </strong> as yearly compensation.
3. Most of the women of Current Role as <strong> Program/Project Manager </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(5) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong>200,000-249,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of Data Engineers by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Data Engineer')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of Current Role as <strong> Data Engineers </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(20) </strong> as yearly compensation.
2. Most of the women of Current Role as <strong> Data Engineers </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(6) </strong> as yearly compensation.
3. Most of the women of Current Role as <strong> Data Engineers </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(18) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong>125,000-149,999	 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 100,000-124,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 125,000-149,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women Product Managers by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Product Manager')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of Current Role as <strong> Product Managers </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(3), 150,000-199,999 USD(3) </strong> as yearly compensation.
2. Most of the women of Current Role as <strong> Product Managers </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 250,000-299,999 USD(1) </strong> as yearly compensation.
3. Most of the women of Current Role as <strong> Product Managers </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(2),50,000-59,999 USD(2),150,000-199,999 USD(2) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong>250,000-299,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women Statisticians by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Statistician')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of Current Role as <strong> Statisticians </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(8)</strong> as yearly compensation.
2. Most of the women of Current Role as <strong> Statisticians </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(14) </strong> as yearly compensation.
3. Most of the women of Current Role as <strong> Statisticians </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(3) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong>125,000-149,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 30,000-39,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women DBA/Database Engineer by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'DBA/Database Engineer')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of Current Role as <strong> DBA/Database Engineer </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(4)</strong> as yearly compensation.
2. Only one of Current Role as <strong> DBA/Database Engineer </strong> who use <strong> R </strong> Programming Language on regular basis and earning <strong> 3,000-3,999 USD </strong> as yearly compensation.
3. Most of the women of Current Role as <strong> DBA/Database Engineer </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(4) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong>150,000-199,999 USD </strong>
5. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women Developer Relations/Advocacy by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q5'] == 'Developer Relations/Advocacy')].groupby([var,'Q5','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women of Current Role as <strong> Developer Relations/Advocacy </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(3)</strong> as yearly compensation.
2. Most of the women of Current Role as <strong> Developer Relations/Advocacy </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 250,000-299,999 USD(1) </strong> as yearly compensation.
3. Most of the women of Current Role as <strong> Developer Relations/Advocacy </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 250,000-299,999 USD(1) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong>250,000-299,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with coding experience by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with coding experience 1-3 years by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q6'] == '1-3 years')].groupby([var,'Q6','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with coding experience <strong> 1-3 years </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(204) </strong> as yearly compensation and less number of women are earning <strong> 125,000-149,999 USD(1), 150,000-199,999 USD(1)</strong> as yearly compensation.
2. Most of the women with coding experience <strong> 1-3 years </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(45) </strong> as yearly compensation and less number of women are earning <strong> 300,000-499,999 USD(1)</strong> as yearly compensation.
3. Most of the womenwith coding experience <strong> 1-3 years </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(110) </strong> as yearly compensation and less number of women are earning <strong> 125,000-149,999 USD(1), 150,000-199,999 USD(1)</strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with coding experience less than 1 years by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q6'] == '< 1 years')].groupby([var,'Q6','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with coding experience <strong> lessthan 1 year </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(204) </strong> as yearly compensation and less number of women are earning <strong> 300,000-499,999 USD(1), 90,000-99,999 USD(1)</strong> as yearly compensation.
2. Most of the women with coding experience <strong> lessthan 1 year </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(45) </strong> as yearly compensation and less number of women are earning <strong> 125,000-149,999 USD(1), 150,000-199,999 USD(1), 200,000-249,999 USD(1), 60,000-69,999 USD(1)</strong> as yearly compensation.
3. Most of the womenwith coding experience <strong> lessthan 1 year </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(110) </strong> as yearly compensation and less number of women are earning <strong> 125,000-149,999 USD(1), 150,000-199,999 USD(1), 300,000-499,999 USD(1), morethan 1,000,000 USD(1)</strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> morethan 1,000,000 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with coding experience 3-5 years by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q6'] == '3-5 years')].groupby([var,'Q6','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with coding experience <strong> 3-5 years </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(93) </strong> as yearly compensation and less number of women are earning <strong> 200,000-249,999 USD(1), morethan 1,000,000 USD(1)</strong> as yearly compensation.
2. Most of the women with coding experience <strong> 3-5 years </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(27) </strong> as yearly compensation and less number of women are earning <strong> 250,000-299,999 USD(1)</strong> as yearly compensation.
3. Most of the womenwith coding experience <strong> 3-5 years </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(51) </strong> as yearly compensation and less number of women are earning <strong> 200,000-249,999 USD(1)</strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> morethan 1,000,000 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with coding experience 5-10 years by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q6'] == '5-10 years')].groupby([var,'Q6','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with coding experience <strong> 5-10 years </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(49) </strong> as yearly compensation and less number of women are earning <strong> 250,000-299,999 USD(1)</strong> as yearly compensation.
2. Most of the women with coding experience <strong> 5-10 years </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 30,000-39,999	 USD(9) </strong> as yearly compensation and less number of women are earning <strong> 500,000-999,999 USD(1),150,000-199,999 USD(1),200,000-249,999 USD(1),40,000-49,999 USD(1)</strong> as yearly compensation.
3. Most of the womenwith coding experience <strong> 5-10 years </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(26) </strong> as yearly compensation and less number of women are earning <strong> 250,000-299,999 USD(1)</strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 500,000-999,999 USD</strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with coding experience 10-20 years by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q6'] == '10-20 years')].groupby([var,'Q6','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with coding experience <strong> 10-20 years </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(27) </strong> as yearly compensation and less number of women are earning <strong> 500,000-999,999 USD(1)</strong> as yearly compensation.
2. Most of the women with coding experience <strong> 10-20 years </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 150,000-199,999 USD(9) </strong> as yearly compensation and less number of women are earning <strong> 250,000-299,999 USD(1),25,000-29,999 USD(1),200,000-249,999 USD(1),4,000-4,999 USD(1)</strong> as yearly compensation.
3. Most of the womenwith coding experience <strong> 10-20 years </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(25) </strong> as yearly compensation and less number of women are earning <strong> 300,000-499,999 USD(1)</strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 500,000-999,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 300,000-499,999 USD</strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with coding experience 20+ years by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q6'] == '20+ years')].groupby([var,'Q6','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with coding experience <strong> 20+ years </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(16) </strong> as yearly compensation.
2. Most of the women with coding experience <strong> 20+ years </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(10) </strong> as yearly compensation.
3. Most of the womenwith coding experience <strong> 20+ years </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(15) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> morethan 1,000,000 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> morethan 1,000,000 USD</strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women of all current employer/contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Computers/Technology contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Computers/Technology')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong> Computers/Technology </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(151) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Computers/Technology </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(23) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Computers/Technology </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(83) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> morethan 1,000,000 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Academics/Education contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Academics/Education')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong> Academics/Education </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(208) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Academics/Education </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(59) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Academics/Education </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(99) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Accounting/Finance contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Accounting/Finance')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong> Accounting/Finance </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(29) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Accounting/Finance </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(11) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Accounting/Finance </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(21) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 200,000-249,999	 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Manufacturing/Fabrication contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Manufacturing/Fabrication')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong> Manufacturing/Fabrication </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(14) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Manufacturing/Fabrication </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(4),40,000-49,999 USD(4) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Manufacturing/Fabrication </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(7) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 200,000-249,999	 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Medical/Pharmaceutical contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Medical/Pharmaceutical')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong> Medical/Pharmaceutical </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(21) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Medical/Pharmaceutical </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 30,000-39,999 USD(5) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Medical/Pharmaceutical </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(8),30,000-39,999 USD(8) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 250,000-299,999	 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Government/Public Service contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Government/Public Service')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong> Government/Public Service </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(12) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Government/Public Service </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 100,000-124,99 USD(5) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Government/Public Service </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(7) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 150,000-199,999		 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Online Service/Internet-based Services contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Online Service/Internet-based Services')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong> Online Service/Internet-based Services </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(16) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Online Service/Internet-based Services </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(7) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Online Service/Internet-based Services </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(8) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 90,000-99,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 250,000-299,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Energy/Mining contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Energy/Mining')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong>Energy/Mining </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(12) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Energy/Mining </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 30,000-39,999(3) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Energy/Mining </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(4) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 125,000-149,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 100,000-124,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 100,000-124,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Retail/Sales contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Retail/Sales')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong>Retail/Sales </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(11) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Retail/Sales </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 7,500-9,999(3) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Retail/Sales </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 10,000-14,999(6) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Insurance/Risk Assessment contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Insurance/Risk Assessment')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong>Retail/Sales </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 20,000-24,999 USD(5) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Retail/Sales </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999(3) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Retail/Sales </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 1,000-1,999 USD(3),20,000-24,999 USD(3), 20,000-24,999 USD(3), 30,000-39,999 USD(3), 70,000-79,999 USD(3), 80,000-89,999 USD(3) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Marketing/CRM Assessment contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Marketing/CRM')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong>Marketing/CRM Assessment </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(11) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Marketing/CRM Assessment </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999(3) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Marketing/CRM Assessment </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(10) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 125,000-149,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 100,000-124,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Broadcasting/Communications contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Broadcasting/Communications')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong>Marketing/CRM Assessment </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 10,000-14,999 USD(5) </strong> as yearly compensation.
2. Most of the womenwith Current Employer/Contract as <strong> Marketing/CRM Assessment </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 10,000-14,999 USD(5) </strong> as yearly compensation.
3. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>
4. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 100,000-124,999 USD </strong>
5. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 200,000-249,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Shipping/Transportation contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Shipping/Transportation')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong>Shipping/Transportation </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(4) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Shipping/Transportation </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 100,000-124,999 USD(2),60,000-69,999 USD(2) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Shipping/Transportation </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD(2), 20,000-24,999 USD(2) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 125,000-149,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 100,000-124,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 125,000-149,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Non-profit/Service contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Non-profit/Service')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong>Non-profit/Service </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(14) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Non-profit/Service </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(5) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Non-profit/Service </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 1,000-1,999 USD (6) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 150,000-199,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Online Business/Internet-based Sales contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Online Business/Internet-based Sales')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong>Online Business/Internet-based Sales </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(14) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Online Business/Internet-based Sales </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(2), 30,000-39,999 USD(2) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Online Business/Internet-based Sales </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD (10) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 125,000-149,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 125,000-149,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 100,000-124,999 USD </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with Hospitality/Entertainment/Sports contract by programming language used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman') & (df['Q20'] == 'Hospitality/Entertainment/Sports')].groupby([var,'Q20','Q25']).size()) 
              for var in {'Q7_Part_1','Q7_Part_2','Q7_Part_3'}}
multi_table([df_groupby['Q7_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q7_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 
##### Here I choosed Python,R and SQL only these 3 because these are the most choosed option.


1. Most of the women with Current Employer/Contract as <strong>Hospitality/Entertainment/Sports </strong> who use <strong> Python </strong> Programming Language on regular basis are earning <strong> 0-999 USD(6) </strong> as yearly compensation.
2. Most of the women with Current Employer/Contract as <strong> Hospitality/Entertainment/Sports </strong> who use <strong> R </strong> Programming Language on regular basis are earning <strong> 0-999 USD(2) </strong> as yearly compensation.
3. Most of the womenwith Current Employer/Contract as <strong> Hospitality/Entertainment/Sports </strong> who use <strong> SQL </strong> Programming Language on regular basis are earning <strong> 0-999 USD (3) </strong> as yearly compensation.
4. Highest Salary of women who use <strong> Python </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
5. Highest Salary of women who use <strong> R </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>
6. Highest Salary of women who use <strong> SQL </strong> programming language on regular basis is <strong> 300,000-499,999 USD </strong>

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Analysis with respect to Income Distribution<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with by Cloud Computing Platforms used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman')].groupby([var,'Q25']).size()) 
              for var in {'Q27_A_Part_1', 'Q27_A_Part_2',
       'Q27_A_Part_3', 'Q27_A_Part_4', 'Q27_A_Part_5', 'Q27_A_Part_6',
       'Q27_A_Part_7', 'Q27_A_Part_8', 'Q27_A_Part_9', 'Q27_A_Part_10',
       'Q27_A_Part_11', 'Q27_A_OTHER'}}
multi_table([df_groupby['Q27_A_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q27_A_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q27_A_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q27_A_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q27_A_Part_5'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q27_A_Part_6'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q27_A_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q27_A_Part_8'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q27_A_Part_9'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q27_A_Part_10'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q27_A_Part_11'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q27_A_OTHER'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women who use <strong> Amazon Web Services (AWS) </strong> are earning <strong> 0-999 USD (82) </strong> as yearly Compensation. Highest salary of women who use <strong> Amazon Web Services (AWS) </strong> is <strong> morethan 1,000,000 USD </strong>
2. Most of the women who use <strong> Microsoft Azure </strong> are earning <strong> 0-999 USD (75) </strong> as yearly Compensation. Highest salary of women who use <strong> Microsoft Azure </strong> is <strong> morethan 1,000,000 USD </strong>
3. Most of the women who use <strong> Google Cloud Platform (GCP) </strong> are earning <strong> 0-999 USD (98) </strong> as yearly Compensation. Highest salary of women who use <strong> Google Cloud Platform (GCP) </strong> is <strong> 500,000-999,999 USD </strong>
4. Most of the women who use <strong> IBM Cloud / Red Hat </strong> are earning <strong> 0-999 USD (34) </strong> as yearly Compensation. Highest salary of women who use <strong> IBM Cloud / Red Hat </strong> is <strong> morethan 1,000,000 USD </strong>
5. Most of the women who use <strong> Oracle Cloud </strong> are earning <strong> 0-999 USD (28) </strong> as yearly Compensation. Highest salary of women who use <strong> Oracle Cloud (GCP) </strong> is <strong> 500,000-999,999 USD </strong>
6. Most of the women who use <strong>SAP Cloud </strong> are earning <strong> 0-999 USD (14) </strong> as yearly Compensation. Highest salary of women who use <strong> SAP Cloud </strong> is <strong> morethan 1,000,000 USD </strong>
7. Most of the women who use <strong>Sales force Cloud </strong> are earning <strong> 0-999 USD (14) </strong> as yearly Compensation. Highest salary of women who use <strong> Sales force Cloud </strong> is <strong> morethan 1,000,000 USD </strong>
8. Most of the women who use <strong>VM Ware Cloud </strong> are earning <strong> 0-999 USD (29) </strong> as yearly Compensation. Highest salary of women who use <strong> VM Ware Cloud </strong> is <strong> morethan 1,000,000 USD </strong>\
9. Most of the women who use <strong>Alibaba Cloud </strong> are earning <strong> 0-999 USD (5) </strong> as yearly Compensation. Highest salary of women who use <strong> Alibaba Cloud </strong> is <strong> morethan 1,000,000 USD </strong>
10. Most of the women who use <strong>Tenset Cloud </strong> are earning <strong> 0-999 USD (6) </strong> as yearly Compensation. Highest salary of women who use <strong> Tenset Cloud </strong> is <strong> morethan 1,000,000 USD </strong>
11. Most of the women who <strong>doesnot use Cloud Platform </strong> are earning <strong> 0-999 USD (119) </strong> as yearly Compensation. Highest salary of women who use <strong> doesnot use Cloud Platform </strong> is <strong> 300,000-499,999 </strong>
12. Most of the women who use <strong> Other Cloud Platforms</strong> are earning <strong> 0-999 USD (7), 1,000-1,999 USD (7) </strong> as yearly Compensation. Highest salary of women who use <strong>Other Cloud Platforms </strong> is <strong> 250,000-299,999	 </strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with by Cloud Computing Products used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman')].groupby([var,'Q25']).size()) 
              for var in {'Q29_A_Part_1', 'Q29_A_Part_2',
       'Q29_A_Part_3', 'Q29_A_Part_4', 'Q29_A_OTHER'}}
multi_table([df_groupby['Q29_A_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q29_A_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q29_A_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q29_A_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q29_A_OTHER'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women who use <strong> Amazon Elastic Compute Cloud (EC2) </strong> are earning <strong> 0-999 USD (31) </strong> as yearly Compensation. Highest salary of women who use <strong> Amazon Elastic Compute Cloud (EC2) </strong> is <strong> morethan 1,000,000 USD </strong>
2. Most of the women who use <strong> Microsoft Azure Virtual Machines </strong> are earning <strong> 0-999 USD (45) </strong> as yearly Compensation. Highest salary of women who use <strong> Microsoft Azure Virtual Machines </strong> is <strong> morethan 1,000,000 USD </strong>
3. Most of the women who use <strong> Google Cloud Compute Engine </strong> are earning <strong> 0-999 USD (63) </strong> as yearly Compensation. Highest salary of women who use <strong> Google Cloud Compute Engine </strong> is <strong> morethan 1,000,000 USD </strong>
4. Most of the women who <strong>doesnot use Cloud Products </strong> are earning <strong> 0-999 USD (69) </strong> as yearly Compensation. Highest salary of women who use <strong> doesnot use Cloud Products </strong> is <strong> 250,000-299,999 USD </strong>
5. Most of the women who use <strong> Other Cloud Products</strong> are earning <strong> 150,000-199,999 USD (3) </strong> as yearly Compensation. Highest salary of women who use <strong>Other Cloud Products </strong> is <strong> 150,000-199,999 USD</strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with by Machine Learning Products used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman')].groupby([var,'Q25']).size()) 
              for var in {'Q31_A_Part_1', 'Q31_A_Part_2', 'Q31_A_Part_3', 'Q31_A_Part_4',
       'Q31_A_Part_5', 'Q31_A_Part_6', 'Q31_A_Part_7', 'Q31_A_Part_8',
       'Q31_A_Part_9', 'Q31_A_OTHER'}}
multi_table([df_groupby['Q31_A_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q31_A_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q31_A_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q31_A_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q31_A_Part_5'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q31_A_Part_6'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q31_A_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q31_A_Part_8'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q31_A_Part_9'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q31_A_OTHER'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women who use <strong> Amazon SageMaker </strong> are earning <strong> 0-999 USD (24) </strong> as yearly Compensation. Highest salary of women who use <strong> Amazon SageMaker </strong> is <strong> morethan 1,000,000 USD </strong>
2. Most of the women who use <strong> Azure Machine Learning Studio </strong> are earning <strong> 0-999 USD (34) </strong> as yearly Compensation. Highest salary of women who use <strong> Azure Machine Learning Studio </strong> is <strong> morethan 1,000,000 USD </strong>
3. Most of the women who use <strong> Google Cloud Vertex AI </strong> are earning <strong> 0-999 USD (34) </strong> as yearly Compensation. Highest salary of women who use <strong> Google Cloud Vertex AI </strong> is <strong> morethan 1,000,000 USD </strong>
4. Most of the women who use <strong> Data Robot </strong> are earning <strong> 0-999 USD (16) </strong> as yearly Compensation. Highest salary of women who use <strong> Data Robot </strong> is <strong> morethan 1,000,000 USD </strong>
5. Most of the women who use <strong> Databricks </strong> are earning <strong> 0-999 USD (15) </strong> as yearly Compensation. Highest salary of women who use <strong> Databricks </strong> is <strong> morethan 1,000,000 USD </strong>
6. Most of the women who use <strong> Dataiku </strong> are earning <strong> 0-999 USD (6) </strong> as yearly Compensation. Highest salary of women who use <strong> Dataiku </strong> is <strong> morethan 1,000,000 USD </strong>
7. Most of the women who use <strong> Alteryx </strong> are earning <strong> 0-999 USD (8) </strong> as yearly Compensation. Highest salary of women who use <strong> Alteryx </strong> is <strong> morethan 1,000,000 USD </strong>
8. Most of the women who use <strong> Rapidminer </strong> are earning <strong> 0-999 USD (10) </strong> as yearly Compensation. Highest salary of women who use <strong> Rapidminer </strong> is <strong> 250,000-299,999 USD </strong>
9. Most of the women who <strong>doesnot use Machine Learning Products </strong> are earning <strong> 0-999 USD (220) </strong> as yearly Compensation. Highest salary of women who use <strong> doesnot use Machine Learning Products </strong> is <strong> 300,000-499,999 USD </strong>
10. Most of the women who use <strong> Other Machine Learning Products</strong> are earning <strong> 0-999 USD (14) </strong> as yearly Compensation. Highest salary of women who use <strong>Other Machine Learning Products </strong> is <strong> 250,000-299,999 USD</strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with by big data products used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman')].groupby([var,'Q25']).size()) 
              for var in {'Q32_A_Part_1', 'Q32_A_Part_2',
       'Q32_A_Part_3', 'Q32_A_Part_4', 'Q32_A_Part_5', 'Q32_A_Part_6',
       'Q32_A_Part_7', 'Q32_A_Part_8', 'Q32_A_Part_9', 'Q32_A_Part_10',
       'Q32_A_Part_11', 'Q32_A_Part_12', 'Q32_A_Part_13', 'Q32_A_Part_14',
       'Q32_A_Part_15', 'Q32_A_Part_16', 'Q32_A_Part_17', 'Q32_A_Part_18',
       'Q32_A_Part_19', 'Q32_A_Part_20', 'Q32_A_OTHER'}}
multi_table([df_groupby['Q32_A_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_5'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_6'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_8'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_9'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_10'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_11'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_12'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_13'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_14'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_15'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_16'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_17'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_18'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_19'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_Part_20'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q32_A_OTHER'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women who use <strong> MySQL </strong> are earning <strong> 0-999 USD (148) </strong> as yearly Compensation. Highest salary of women who use <strong> MySQL </strong> is <strong> morethan 1,000,000 USD </strong>
2. Most of the women who use <strong> Postgre SQL </strong> are earning <strong> 0-999 USD (54) </strong> as yearly Compensation. Highest salary of women who use <strong> Postgre SQL </strong> is <strong> morethan 1,000,000 USD </strong>
3. Most of the women who use <strong> SQLite </strong> are earning <strong> 0-999 USD (53) </strong> as yearly Compensation. Highest salary of women who use <strong> SQLite </strong> is <strong> morethan 1,000,000 USD </strong>
4. Most of the women who use <strong> Oracle Databases </strong> are earning <strong> 0-999 USD (44) </strong> as yearly Compensation. Highest salary of women who use <strong> Oracle Databases </strong> is <strong> morethan 1,000,000 USD </strong>
5. Most of the women who use <strong> MongoDB </strong> are earning <strong> 0-999 USD (49) </strong> as yearly Compensation. Highest salary of women who use <strong> MongoDB </strong> is <strong> morethan 1,000,000 USD </strong>
6. Most of the women who use <strong> Snowflake </strong> are earning <strong> 150,000-199,999 USD(8) </strong> as yearly Compensation. Highest salary of women who use <strong> Snowflake </strong> is <strong> morethan 1,000,000 USD </strong>
7. Most of the women who use <strong> IBMdb2 </strong> are earning <strong> 0-999 USD (12) </strong> as yearly Compensation. Highest salary of women who use <strong> IBMdb2 </strong> is <strong> morethan 1,000,000 USD </strong>
8. Most of the women who use <strong> Microsoft SQL Server </strong> are earning <strong> 0-999 USD (55) </strong> as yearly Compensation. Highest salary of women who use <strong> Microsoft SQL Server </strong> is <strong> morethan 1,000,000 USD </strong>
9. Most of the women who use <strong> Microsoft Azure SQL Database </strong> are earning <strong> 0-999 USD (19) </strong> as yearly Compensation. Highest salary of women who use <strong> Microsoft Azure SQL Database </strong> is <strong> 500,000-999,999 USD </strong>
10. Most of the women who use <strong> Microsoft Azure Cosmos DB </strong> are earning <strong> 0-999 USD (11) </strong> as yearly Compensation. Highest salary of women who use <strong> Microsoft Azure Cosmos DB </strong> is <strong> morethan 1,000,000 USD </strong>
11. Most of the women who use <strong> Amazon Redshift </strong> are earning <strong> 0-999 USD (11) </strong> as yearly Compensation. Highest salary of women who use <strong> Amazon Redshift </strong> is <strong> 500,000-999,999 USD </strong>
12. Most of the women who use <strong> Amazon Aurora </strong> are earning <strong> 0-999 USD (6) </strong> as yearly Compensation. Highest salary of women who use <strong> Amazon Aurora </strong> is <strong> morethan 1,000,000 USD </strong>
13. Most of the women who use <strong> Amazon RDS </strong> are earning <strong> 0-999 USD (14) </strong> as yearly Compensation. Highest salary of women who use <strong> Amazon RDS </strong> is <strong> 500,000-999,999 USD </strong>
14. Most of the women who use <strong> Amazon DynamoDB </strong> are earning <strong> 0-999 USD (11) </strong> as yearly Compensation. Highest salary of women who use <strong> Amazon DynamoDB </strong> is <strong> 500,000-999,999 USD </strong>
15. Most of the women who use <strong> Google Cloud BigQuery </strong> are earning <strong> 0-999 USD (20) </strong> as yearly Compensation. Highest salary of women who use <strong> Google Cloud BigQuery </strong> is <strong> 500,000-999,999 USD </strong>
16. Most of the women who use <strong> Google Cloud SQL </strong> are earning <strong> 0-999 USD (22) </strong> as yearly Compensation. Highest salary of women who use <strong> Google Cloud SQL </strong> is <strong> morethan 1,000,000 USD </strong>
17. Most of the women who use <strong> Google Cloud Firestore </strong> are earning <strong> 0-999 USD (13) </strong> as yearly Compensation. Highest salary of women who use <strong> Google Cloud FireStore </strong> is <strong> morethan 1,000,000 USD </strong>
18. Most of the women who use <strong> Google Cloud BigTable </strong> are earning <strong> 0-999 USD (12) </strong> as yearly Compensation. Highest salary of women who use <strong> Google Cloud BigTable </strong> is <strong> 500,000-999,999 USD </strong>
19. Most of the women who use <strong> Google Cloud Spanner </strong> are earning <strong> 0-999 USD (7) </strong> as yearly Compensation. Highest salary of women who use <strong> Google Cloud Spanner </strong> is <strong> 500,000-999,999 USD </strong>
20. Most of the women who <strong>doesnot use Big Data Products </strong> are earning <strong> 0-999 USD (77) </strong> as yearly Compensation. Highest salary of women who use <strong> doesnot use Machine Learning Products </strong> is <strong> 300,000-499,999 USD </strong>
21. Most of the women who use <strong> Other Big Data Products</strong> are earning <strong> 0-999 USD (10) </strong> as yearly Compensation. Highest salary of women who use <strong>Other Machine Learning Products </strong> is <strong> 150,000-199,999 USD</strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with by business intelligence tools used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman')].groupby([var,'Q25']).size()) 
              for var in {'Q34_A_Part_1', 'Q34_A_Part_2', 'Q34_A_Part_3', 'Q34_A_Part_4',
       'Q34_A_Part_5', 'Q34_A_Part_6', 'Q34_A_Part_7', 'Q34_A_Part_8',
       'Q34_A_Part_9', 'Q34_A_Part_10', 'Q34_A_Part_11', 'Q34_A_Part_12',
       'Q34_A_Part_13', 'Q34_A_Part_14', 'Q34_A_Part_15', 'Q34_A_Part_16',
       'Q34_A_OTHER'}}
multi_table([df_groupby['Q34_A_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_5'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_6'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_8'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_9'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_10'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_11'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_12'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_13'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_14'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_15'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_Part_16'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q34_A_OTHER'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women who use <strong> Amazon QuickSight </strong> are earning <strong> 0-999 USD (9) </strong> as yearly Compensation. Highest salary of women who use <strong> Amazon QuickSight </strong> is <strong> 500,000-999,999 USD </strong>
2. Most of the women who use <strong> Microsoft Power BI </strong> are earning <strong> 0-999 USD (66) </strong> as yearly Compensation. Highest salary of women who use <strong> Microsoft Power BI </strong> is <strong> 500,000-999,999 USD </strong>
3. Most of the women who use <strong> Google Data Studio </strong> are earning <strong> 0-999 USD (31) </strong> as yearly Compensation. Highest salary of women who use <strong> Google Data Studio </strong> is <strong> 500,000-999,999 USD </strong>
4. Most of the women who use <strong> Looker </strong> are earning <strong> 0-999 USD (3), 100,000-124,999 USD(3), 150,000-199,999 USD (3) </strong> as yearly Compensation. Highest salary of women who use <strong> Looker </strong> is <strong> 500,000-999,999 USD </strong>
5. Most of the women who use <strong> Tableau </strong> are earning <strong> 0-999 USD (81) </strong> as yearly Compensation. Highest salary of women who use <strong> Tableau </strong> is <strong> morethan 1,000,000 USD </strong>
6. Most of the women who use <strong> Salesforce </strong> are earning <strong> 0-999 USD(16) </strong> as yearly Compensation. Highest salary of women who use <strong> Salesforce </strong> is <strong> morethan 1,000,000 USD </strong>
7. Most of the women who use <strong> Tableau CRM </strong> are earning <strong> 0-999 USD (13) </strong> as yearly Compensation. Highest salary of women who use <strong> Tableau CRM </strong> is <strong> 500,000-999,999 USD </strong>
8. Most of the women who use <strong>Qlik </strong> are earning <strong> 0-999 USD (6), 1,000-1,999 USD(6) </strong> as yearly Compensation. Highest salary of women who use <strong> Qlik </strong> is <strong> 500,000-999,999 USD </strong>
9. Most of the women who use <strong> Domo </strong> are earning <strong> 0-999 USD (2) </strong> as yearly Compensation. Highest salary of women who use <strong> Domo </strong> is <strong> 500,000-999,999 USD </strong>
10. Most of the women who use <strong> TIBCO Spotfire </strong> are earning <strong> 0-999 USD (4) </strong> as yearly Compensation. Highest salary of women who use <strong> TIBCO Spotfire </strong> is <strong> 500,000-999,999 USD </strong>
11. Most of the women who use <strong> Alteryx </strong> are earning <strong> 100,000-124,999 USD (5) </strong> as yearly Compensation. Highest salary of women who use <strong> Alteryx </strong> is <strong> morethan 1,000,000 USD</strong>
12. Most of the women who use <strong> Sisense </strong> are earning <strong> 0-999 USD (3) </strong> as yearly Compensation. Highest salary of women who use <strong> Sisense </strong> is <strong> 500,000-999,999 USD </strong>
13. Most of the women who use <strong> SAP Analytics Cloud </strong> are earning <strong> 0-999 USD (7) </strong> as yearly Compensation. Highest salary of women who use <strong> SAP Analytics Cloud </strong> is <strong> 500,000-999,999 USD </strong>
14. Most of the women who use <strong> Microsoft Azure Synapse </strong> are earning <strong> 0-999 USD (9) </strong> as yearly Compensation. Highest salary of women who use <strong> Microsoft Azure Synapse </strong> is <strong> 500,000-999,999 USD </strong>
15. Most of the women who use <strong> Thoughtspot </strong> are earning <strong> 0-999 USD (3) </strong> as yearly Compensation. Highest salary of women who use <strong> Thoughtspot </strong> is <strong> morethan 1,000,000 USD </strong>
16. Most of the women who <strong>doesnot use business intelligence tools </strong> are earning <strong> 0-999 USD (148) </strong> as yearly Compensation. Highest salary of women who use <strong> doesnot use Machine Learning Products </strong> is <strong> 300,000-499,999 USD </strong>
17. Most of the women who use <strong> Other business intelligence tools </strong> are earning <strong> 0-999 USD (10) </strong> as yearly Compensation. Highest salary of women who use <strong>Other Machine Learning Products </strong> is <strong> 150,000-199,999 USD</strong>

<h2 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Income Distribution of women with by automated machine learning tools (or partial AutoML tools) used on regular basis<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h2>

In [ ]:
df_groupby = {var: pd.DataFrame(df[(df['Q2'] == 'Woman')].groupby([var,'Q25']).size()) 
              for var in {'Q36_A_Part_1', 'Q36_A_Part_2',
       'Q36_A_Part_3', 'Q36_A_Part_4', 'Q36_A_Part_5', 'Q36_A_Part_6',
       'Q36_A_Part_7', 'Q36_A_OTHER'}}
multi_table([df_groupby['Q36_A_Part_1'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q36_A_Part_2'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q36_A_Part_3'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q36_A_Part_4'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q36_A_Part_5'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q36_A_Part_6'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q36_A_Part_7'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow'), df_groupby['Q36_A_OTHER'].style\
      .format('{:.2f}')\
      .highlight_max(color = 'lightgreen')\
      .highlight_min(color = 'coral')\
      .highlight_null(null_color='yellow')])

#### Observation:


##### All these observations are with respect to the women in the survey not entire women in the world 

1. Most of the women who use <strong> Automated data augmentation (e.g. imgaug, albumentations) </strong> are earning <strong> 0-999 USD (38) </strong> as yearly Compensation. Highest salary of women who use <strong> Automated data augmentation (e.g. imgaug, albumentations) </strong> is <strong> 500,000-999,999 USD </strong>
2. Most of the women who use <strong> Automated feature engineering/selection (e.g. tpot, boruta_py) </strong> are earning <strong> 0-999 USD (22) </strong> as yearly Compensation. Highest salary of women who use <strong> Automated feature engineering/selection (e.g. tpot, boruta_py) </strong> is <strong> 500,000-999,999 USD </strong>
3. Most of the women who use <strong> Automated model selection (e.g. auto-sklearn, xcessiv) </strong> are earning <strong> 0-999 USD (38) </strong> as yearly Compensation. Highest salary of women who use <strong> Automated model selection (e.g. auto-sklearn, xcessiv) </strong> is <strong> 500,000-999,999 USD </strong>
4. Most of the women who use <strong> Automated model architecture searches (e.g. darts, enas) </strong> are earning <strong> 0-999 USD (11) </strong> as yearly Compensation. Highest salary of women who use <strong> Automated model architecture searches (e.g. darts, enas) </strong> is <strong> 500,000-999,999 USD </strong>
5. Most of the women who use <strong> Automated hyperparameter tuning (e.g. hyperopt, ray.tune, Vizier) </strong> are earning <strong> 0-999 USD (17) </strong> as yearly Compensation. Highest salary of women who use <strong> Automated hyperparameter tuning (e.g. hyperopt, ray.tune, Vizier) </strong> is <strong> 500,000-999,999 USD</strong>
6. Most of the women who use <strong> Automation of full ML pipelines (e.g. Google AutoML, H2O Driverless AI) </strong> are earning <strong> 0-999 USD(24) </strong> as yearly Compensation. Highest salary of women who use <strong> Automation of full ML pipelines (e.g. Google AutoML, H2O Driverless AI) </strong> is <strong> morethan 1,000,000 USD </strong>
7. Most of the women who <strong>doesnot use automated machine learning tools (or partial AutoML tools) </strong> are earning <strong> 0-999 USD (213) </strong> as yearly Compensation. Highest salary of women who use <strong> doesnot use Machine Learning Products </strong> is <strong> 500,000-999,999 USD </strong>
8. Most of the women who use <strong> Other automated machine learning tools (or partial AutoML tools) </strong> are earning <strong> 0-999 USD (10) </strong> as yearly Compensation. Highest salary of women who use <strong>Other Machine Learning Products </strong> is <strong> 250,000-299,999 USD</strong>

<h1 style="color:#fce444;font-size:30px;font-family:Georgia;text-align:center;"><strong><strong style="color:black;font-size:25px;font-family:Georgia;">Conclusion<strong style="color:#fce444;font-size:25px;font-family:Georgia;"><strong style="color:black;font-size:30px;font-family:Georgia;">:- </strong></strong></strong></strong></h1>

<h2 style="color:red;font-size:16px;font-family:Georgia;text-align:center;"><strong><p></p> <strong style="color:black;font-size:20px;font-family:Georgia;"> Students submitted all these observations to NICK FURY. See what he is quite impressive and appreciated all the students,given some compensation as well. He also told each and every student to work hard to achieve their goals. All the students were happy and they went to their hostels/home at the end of the day.</strong></strong></h2>

<img src="https://d.newsweek.com/en/full/1868100/what-if-watcher.png" width="800px">

<h6 style="color:#fce444;font-size:26px;font-family:Georgia;text-align:center;"><strong> <strong style="color:black;font-size:21px;font-family:Georgia;">This is the story for today thanks for listening and if you also want be successful in life start working from today.........Signing off.... <strong style="color:#fce444;font-size:21px;font-family:Georgia;"> <strong style="color:black;font-size:26px;font-family:Georgia;"> </strong></strong></strong></strong></h6>

<h6 style="color:#fce444;font-size:26px;font-family:Georgia;text-align:center;"><strong> <strong style="color:black;font-size:21px;font-family:Georgia;"> <strong style="color:#fce444;font-size:21px;font-family:Georgia;"> <strong style="color:black;font-size:26px;font-family:Georgia;"> THE END</strong></strong></strong></strong></h6>

### References:
1. Headings HTML style is suggested by : Sonali Singh 
2. Heatmaps are inspiration from https://www.kaggle.com/datafan07/what-takes-to-be-a-data-scientist-story-of-robert
3. All images are taken from google.