
# Data Science Survey EDA with all Countries
### 2021 Kaggle Machine Learning & Data Science Survey

#### Contents


* **data-purifier**
* **autoviz**
* **pandas_profiling**
* **Visualisation all the qusetion from Q1 to Q41**
* **Explore Data scientists from all Countries**

In [ ]:
from IPython.display import YouTubeVideo
YOUTUBE_ID = 'b_xXtPi7ABI'
YouTubeVideo(YOUTUBE_ID,width=960, height=800)

### Table of Contents
* Data Science Survey EDA with all Countries
* Data-Purifier
* Autoviz: Automatically Visualize
* Q1: What is your age (# years)?
* Q2: What is your gender?
* Q3: In which country do you currently reside?
* Q4: What is the highest level of formal education that you have attained or plan to attain within the next 2 years?
* Q5: Select the title most similar to your current role (or most recent title if retired)
* Q6: For how many years have you been writing code and/or programming?
* Q8: What programming language would you recommend an aspiring data scientist to learn first?
* Q11: What type of computing platform do you use most often for your data science projects?
* Q13: Approximately how many times have you used a TPU (tensor processing unit)?
* Q15: For how many years have you used machine learning methods?
* Q20: In what industry is your current employer/contract (or your most recent employer if retired)?
* Q21: What is the size of the company where you are employed?
* Q22: Approximately how many individuals are responsible for data science workloads at your place of business?
* Q23: Does your current employer incorporate machine learning methods into their business?
* Q26: Approximately how much money have you (or your team) spent on machine learning and/or cloud computing services at home (or at work) in the past 5 years (approximate $USD)?
* Q28: Of the cloud platforms that you are familiar with, which has the best developer experience (most enjoyable to use)?
* Q33: Which of the following big data products (relational database, data warehouse, data lake, or similar) do you use most often?
* 35Q: Which of the following business intelligence tools do you use most often?
* Q41: What is the primary tool that you use at work or school to analyze data? (Include text response)?
* Data scientists from all Countries
* India Data Scientists
* Indonesia Data Scientists
* Pakistan Data Scientists
* Mexico Data Scientists
* Russia Data Scientists
* Turkey Data Scientists
* Australia Data Scientists
* Nigeria Data Scientists
* Greece Data Scientists
* Belgium Data Scientists
* Japan Data Scientists
* Egypt Data Scientists
* Singapore Data Scientists
* Brazil Data Scientists
* Poland Data Scientists
* Chaina Data Scientists
* Iran Data Scientists
* United States of America Data Scientists
* Viet Nam Data Scientists
* Israel Data Scientists
* Peru Data Scientists
* South Africa Data Scientists
* Other Data Scientists
* Spain Data Scientists
* Bangladesh Data Scientists
* United Kingdom of Great Britain and Northern Ireland Data Scientists
* France Data Scientists
* Switzerland Data Scientists
* Algeria Data Scientists
* Tunisia Data Scientists
* Argentina Data Scientists
* Sweden Data Scientists
* Colombia Data Scientists
* Canada Data Scientists
* Chile Data Scientists
* Netherland Data Scientists
* Ukraine Data Scientists
* Iraq Data Scientists
* Explore data science Iraq

#### Data Description

This year, as in 2017, 2018, 2019, and 2020 we set out to conduct an industry-wide survey that presents a truly comprehensive view of the state of data science and machine learning. The survey was live from 09/01/2021 to 10/04/2021, and after cleaning the data we finished with 25,973 responses!

##### Main Data: 

kaggle_survey_2021_responses.csv: 42+ questions and 25,973 responses

* Responses to multiple choice questions (only a single choice can be selected) were recorded in individual columns. Responses to multiple selection questions (multiple choices can be selected) were split into multiple columns (with one column per answer choice).

##### Supplementary Data:

kaggle_survey_2021_answer_choices.pdf: list of answer choices for every question

* With footnotes describing which questions were asked to which respondents.

kaggle_survey_2021_methodology.pdf: a description of how the survey was conducted

* You can ask additional questions by posting in the pinned Q&A thread.

#### Link dataset 

[HERE](https://www.kaggle.com/c/kaggle-survey-2021/data)

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(rc={'figure.figsize': [20, 5]}, font_scale=.90)

In [ ]:
df_Q = pd.read_csv('../input/kaggel/kaggle_survey_2021_responses.csv')

df_Q.head(5)

In [ ]:
pip install data-purifier==0.3.0

# Data-Purifier
* A Python library for Automated Exploratory Data Analysis, Automated Data Cleaning and Automated Data Preprocessing For Machine Learning and Natural Language Processing Applications in Python.

![](https://github.com/Elysian01/Data-Purifier/raw/master/static/demo.gif)

In [ ]:
import datapurifier as dp
from datapurifier import Mleda
df = pd.read_csv("../input/kaggel/kaggle_survey_2021_responses.csv")
df1 = Mleda(df)
df1

In [ ]:
pip install xlrd

In [ ]:
pip install autoviz

# Autoviz: Automatically Visualize

* Automatically Visualize any dataset, any size with a single line of code.

![](https://miro.medium.com/max/750/1*lgVdi9ZpL5_kK8s9ccPNtw.png)

In [ ]:
from autoviz.AutoViz_Class import AutoViz_Class
AV = AutoViz_Class()
df_Q = AV.AutoViz('../input/kaggel/kaggle_survey_2021_responses.csv')

In [ ]:
import pandas_profiling as pp
pp.ProfileReport(df_Q)

In [ ]:
%matplotlib inline
sns.set(rc={'figure.figsize': [20, 5]}, font_scale=.90)

In [ ]:
df_Q = pd.read_csv("../input/kaggel/kaggle_survey_2021_responses.csv")

# Q1: What is your age (# years)?

In [ ]:
sns.countplot(df_Q['Q1'])

# Q2: What is your gender?

In [ ]:
sns.countplot(df_Q['Q2'])

# Q3: In which country do you currently reside?

In [ ]:
sns.countplot(df_Q['Q3'])

#  Q4: What is the highest level of formal education that you have attained or plan to attain within the next 2 years?

In [ ]:
sns.countplot(df_Q['Q4'])

# Q5: Select the title most similar to your current role (or most recent title if retired)

In [ ]:
sns.countplot(df_Q['Q5'])

#  Q6: For how many years have you been writing code and/or programming?

In [ ]:
sns.countplot(df_Q['Q6'])

# Q8: What programming language would you recommend an aspiring data scientist to learn first?

In [ ]:
sns.countplot(df_Q['Q8'])

# Q11: What type of computing platform do you use most often for your data science projects?

In [ ]:
sns.countplot(df_Q['Q11'])

# Q13: Approximately how many times have you used a TPU (tensor processing unit)?

In [ ]:
sns.countplot(df_Q['Q13'])

# Q15: For how many years have you used machine learning methods?

In [ ]:
sns.countplot(df_Q['Q15'])

# Q20: In what industry is your current employer/contract (or your most recent employer if retired)?

In [ ]:
sns.countplot(df_Q['Q20'])

# Q21: What is the size of the company where you are employed?

In [ ]:
sns.countplot(df_Q['Q21'])

# Q22: Approximately how many individuals are responsible for data science workloads at your place of business?

In [ ]:
sns.countplot(df_Q['Q22'])

# Q23: Does your current employer incorporate machine learning methods into their business?

In [ ]:
sns.countplot(df_Q['Q23'])

# Q26: Approximately how much money have you (or your team) spent on machine learning and/or cloud computing services at home (or at work) in the past 5 years (approximate $USD)?

In [ ]:
sns.countplot(df_Q['Q26'])

# Q28: Of the cloud platforms that you are familiar with, which has the best developer experience (most enjoyable to use)?

In [ ]:
sns.countplot(df_Q['Q28'])

# Q33: Which of the following big data products (relational database, data warehouse, data lake, or similar) do you use most often?

In [ ]:
sns.countplot(df_Q['Q33'])

# 35Q: Which of the following business intelligence tools do you use most often?

In [ ]:
sns.countplot(df_Q['Q35'])

# Q41: What is the primary tool that you use at work or school to analyze data? (Include text response)?

In [ ]:
sns.countplot(df_Q['Q41'])

# Data scientists from all Countries

# India Data Scientists

In [ ]:
India = df_Q[df_Q.Q3 == 'India']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(India)

# Indonesia Data Scientists

In [ ]:
Indonesia = df_Q[df_Q.Q3 == 'Indonesia']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Indonesia)

# Pakistan Data Scientists

In [ ]:
Pakistan = df_Q[df_Q.Q3 == 'Pakistan']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Pakistan)

# Mexico Data Scientists

In [ ]:
Mexico = df_Q[df_Q.Q3 == 'Mexico']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Mexico)

# Russia Data Scientists

In [ ]:
Russia = df_Q[df_Q.Q3 == 'Russia']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Russia)

# Turkey Data Scientists

In [ ]:
Turkey = df_Q[df_Q.Q3 == 'Turkey']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Turkey)

# Australia Data Scientists

In [ ]:
Australia = df_Q[df_Q.Q3 == 'Australia']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Australia)

# Nigeria Data Scientists

In [ ]:
Nigeria = df_Q[df_Q.Q3 == 'Nigeria']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Nigeria)

# Greece Data Scientists

In [ ]:
Greece = df_Q[df_Q.Q3 == 'Greece']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Greece)

# Belgium Data Scientists

In [ ]:
Belgium = df_Q[df_Q.Q3 == 'Belgium']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Belgium)

# Belgium Data Scientists

In [ ]:
Belgium = df_Q[df_Q.Q3 == 'Belgium']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Belgium)

# Japan Data Scientists

In [ ]:
Japan = df_Q[df_Q.Q3 == 'Japan']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Japan)

# Egypt Data Scientists

In [ ]:
Egypt = df_Q[df_Q.Q3 == 'Egypt']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Egypt)

# Singapore Data Scientists

In [ ]:
Singapore = df_Q[df_Q.Q3 == 'Singapore']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Singapore)

# Brazil Data Scientists

In [ ]:
Brazil = df_Q[df_Q.Q3 == 'Brazil']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Brazil)

# Poland Data Scientists

In [ ]:
Poland = df_Q[df_Q.Q3 == 'Poland']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Poland)

# Chaina Data Scientists

In [ ]:
China = df_Q[df_Q.Q3 == 'China']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(China)

# Iran Data Scientists

In [ ]:
Iran = df_Q[df_Q.Q3 == 'Iran']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Iran)

# United States of America Data Scientists

In [ ]:
UnitedStatesofAmerica = df_Q[df_Q.Q3 == 'United States of America']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(UnitedStatesofAmerica)

# Viet Nam Data Scientists

In [ ]:
VietNam= df_Q[df_Q.Q3 == 'Viet Nam']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(VietNam)

# Israel Data Scientists

In [ ]:
Israel= df_Q[df_Q.Q3 == 'Israel']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Israel)

# Peru Data Scientists

In [ ]:
Peru= df_Q[df_Q.Q3 == 'Peru']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Peru)

# South Africa Data Scientists

In [ ]:
SouthAfrica= df_Q[df_Q.Q3 == 'South Africa']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(SouthAfrica)

# Other Data Scientists

In [ ]:
Other= df_Q[df_Q.Q3 == 'Other']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Other)

# Spain Data Scientists

In [ ]:
Spain= df_Q[df_Q.Q3 == 'Spain']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Spain)

# Bangladesh Data Scientists

In [ ]:
Bangladesh= df_Q[df_Q.Q3 == 'Bangladesh']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Bangladesh)

# United Kingdom of Great Britain and Northern Ireland Data Scientists

In [ ]:
UnitedKingdomofGreatBritainandNorthernIreland= df_Q[df_Q.Q3 == 'United Kingdom of Great Britain and Northern Ireland']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(UnitedKingdomofGreatBritainandNorthernIreland)

# France Data Scientists

In [ ]:
France= df_Q[df_Q.Q3 == 'France']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(France)

# Switzerland Data Scientists

In [ ]:
Switzerland= df_Q[df_Q.Q3 == 'Switzerland']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Switzerland)

# Algeria Data Scientists

In [ ]:
Algeria= df_Q[df_Q.Q3 == 'Algeria']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Algeria)

# Tunisia Data Scientists

In [ ]:
Tunisia= df_Q[df_Q.Q3 == 'Tunisia']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Tunisia)

# Argentina Data Scientists

In [ ]:
Argentina= df_Q[df_Q.Q3 == 'Argentina']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Argentina)

# Sweden Data Scientists

In [ ]:
Sweden= df_Q[df_Q.Q3 == 'Sweden']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Sweden)

# Colombia Data Scientists

In [ ]:
Colombia= df_Q[df_Q.Q3 == 'Colombia']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Colombia)

# Canada Data Scientists

In [ ]:
Canada= df_Q[df_Q.Q3 == 'Canada']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Canada)

# Chile Data Scientists

In [ ]:
Chile= df_Q[df_Q.Q3 == 'Chile']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Chile)

# Netherland  Data Scientists

In [ ]:
Netherlands= df_Q[df_Q.Q3 == 'Netherlands']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Netherlands)

# Ukraine Data Scientists

In [ ]:
Ukraine= df_Q[df_Q.Q3 == 'Ukraine']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Ukraine)

In [ ]:
SaudiArabia= df_Q[df_Q.Q3 == 'Saudi Arabia']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(SaudiArabia)

In [ ]:
Romania= df_Q[df_Q.Q3 == 'Romania']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Romania)

In [ ]:
Morocco= df_Q[df_Q.Q3 == 'Morocco']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Morocco)

In [ ]:
Austria= df_Q[df_Q.Q3 == 'Austria']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Austria)

In [ ]:
Taiwan= df_Q[df_Q.Q3 == 'Taiwan']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Taiwan)

In [ ]:
Kenya= df_Q[df_Q.Q3 == 'Kenya']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Kenya)

In [ ]:
Belarus= df_Q[df_Q.Q3 == 'Belarus']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Belarus)

In [ ]:
Ireland= df_Q[df_Q.Q3 == 'Ireland']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Ireland)

In [ ]:
Portugal= df_Q[df_Q.Q3 == 'Portugal']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Portugal)

In [ ]:
HongKong= df_Q[df_Q.Q3 == 'Hong Kong (S.A.R.)']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(HongKong)

In [ ]:
Denmark= df_Q[df_Q.Q3 == 'Denmark']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Denmark)

In [ ]:
SouthKorea= df_Q[df_Q.Q3 == 'South Korea']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(SouthKorea)

In [ ]:
Philippines= df_Q[df_Q.Q3 == 'Philippines']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Philippines)

In [ ]:
SriLanka= df_Q[df_Q.Q3 == 'Sri Lanka']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(SriLanka)

In [ ]:
UnitedArabEmirates= df_Q[df_Q.Q3 == 'United Arab Emirates']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(UnitedArabEmirates)

In [ ]:
Uganda= df_Q[df_Q.Q3 == 'Uganda']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Uganda)

In [ ]:
Ghana= df_Q[df_Q.Q3 == 'Ghana']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Ghana)

In [ ]:
Malaysia= df_Q[df_Q.Q3 == 'Malaysia']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Malaysia)

In [ ]:
Thailand= df_Q[df_Q.Q3 == 'Thailand']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Thailand)

In [ ]:
Nepal= df_Q[df_Q.Q3 == 'Nepal']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Nepal)

In [ ]:
Kazakhstan= df_Q[df_Q.Q3 == 'Kazakhstan']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Kazakhstan)

In [ ]:
Ethiopia= df_Q[df_Q.Q3 == 'Ethiopia']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Ethiopia)

In [ ]:
Ecuador= df_Q[df_Q.Q3 == 'Ecuador']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Ecuador)

In [ ]:
Norway= df_Q[df_Q.Q3 == 'Norway']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(Norway)

In [ ]:
CzechRepublic= df_Q[df_Q.Q3 == 'Czech Republic']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(CzechRepublic)

![](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/255px-Flag_of_Iraq.svg.png)

# Iraq Data Scientists

In [ ]:
df_Iraq = df_Q[df_Q.Q3 == 'Iraq']

def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)
    print("##################### convert_dtypes #####################")
    print(dataframe.convert_dtypes())
    print("##################### columns #####################")
    print(dataframe.columns)
check_df(df_Iraq)

# Explore data science Iraq

In [ ]:
df_iraq = df_Q[df_Q.Q3 == 'Iraq'],df_Q[df_Q.Q2 == 'Man']
df_iraq

In [ ]:
df_iraq = df_Q[df_Q.Q3 == 'Iraq'],df_Q[df_Q.Q5 == 'Data Scientist']
df_iraq

In [ ]:
df_iraq = df_Q[df_Q.Q3 == 'Iraq'],df_Q[df_Q.Q6 == '20+ years']
df_iraq

In [ ]:
df_iraq = df_Q[df_Q.Q3 == 'Iraq'],df_Q[df_Q.Q7_Part_1 == 'Python']
df_iraq

In [ ]:
df_iraqdf_iraq = df_Q[df_Q.Q3 == 'Iraq'],df_Q[df_Q.Q5 == 'Data Scientist']
df_iraqdf_iraq

In [ ]:
df_iraq = df_Q[df_Q.Q3 == 'Iraq'],df_Q[df_Q.Q6 == '20+ years']
df_iraq

In [ ]:
df_iraq = df_Q[df_Q.Q3 == 'Iraq'],df_Q[df_Q.Q7_Part_1 == 'Python']
df_iraq

In [ ]:
pp.ProfileReport(df_Iraq)