# **WELCOME TO MY FIRST EDA!!**
This is my first kaggle notebook and first EDA!
As you expected, actually I'm not confident in my work and it was not that easy to me... But I tried my best!
I tried to show data analysis specially about Korea because I'm korean! haha..

Anyway I hope you guys to enjoy the newbie's work! 
Thanks

**BASIC INGREDIENTS TO ANALYZE**

In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

**DATA LOAD**

In [ ]:
df = pd.read_csv('/kaggle/input/kaggle-survey-2020/kaggle_survey_2020_responses.csv')
df.head(10)

**DELETE UNUSEFUL COLUMN**

In [ ]:
df.drop(['Time from Start to Finish (seconds)'], axis=1, inplace= True)
df

> **WORLD AGE DISTRIBUTION**

In [ ]:
df_age = df.iloc[1:,0]
age_sorted = df_age.value_counts().sort_index()
X = age_sorted.index
Y = age_sorted.values
title = 'Age Distribution'

plt.title(title)
plt.bar(X,Y)
plt.show()

> **WORLD GENDER DISTRIBUTION**

In [ ]:
df_gender = df.iloc[1:,1]
gender_sorted = df_gender.value_counts().sort_index()

man_percent = gender_sorted.values[0]/sum(gender_sorted.values)*100
nobinary = gender_sorted.values[1]/sum(gender_sorted.values)*100
Prefer_not_to_say= gender_sorted.values[2]/sum(gender_sorted.values)*100
Prefer_to_self_describe= gender_sorted.values[3]/sum(gender_sorted.values)*100
Woman = gender_sorted.values[4]/sum(gender_sorted.values)*100

X = gender_sorted.index
Y = [man_percent, nobinary, Prefer_not_to_say, Prefer_to_self_describe, Woman]

title = 'World Gender Distribution'


plt.title(title)
gender_dis = plt.bar(X,Y)
gender_dis[0].set_color('lightgreen')
gender_dis[-1].set_color('orange')

plt.show()

In [ ]:
plt.pie(Y, labels=X, autopct='%.1f%%')
plt.legend(loc=(1.0, 0.5))

> **COUNTRY DISTRIBUTION**

In [ ]:
df_country = df.iloc[1:,2]
country_sorted = df_country.value_counts(ascending = True)
top_21 = country_sorted[-21:] ##It is too many.. 

X = country_sorted.index[-21:]
Y = top_21
title = 'Country Distribution'

plt.title(title)
gra = plt.barh(X,Y)
gra[0].set_color('orange')
plt.show()

**Korean is 21th. From now on, we will see how the korean data is distributed.**

> **Extract Korean Data**

In [ ]:
df_korea = df[df['Q3']=='South Korea'].reset_index()
df_korea.drop('index', axis=1, inplace = True)
df_korea.head(10)

> **KOREAN AGE DISTRIBUTION**

In [ ]:
df_korea_age = df_korea.iloc[0:,0]
korean_age_sorted = df_korea_age.value_counts().sort_index()
X = korean_age_sorted.index
Y = korean_age_sorted.values
title = 'Korean Age Distribution'


plt.title(title)
plt.bar(X,Y)
plt.show()

**Compare with world age distribution, the 18-21 and 22-24 have a small proportion.**

In [ ]:
X1 = age_sorted.index
Y1 = age_sorted.values

plt.subplot(111)
plt.title('World Age Distribution')
age_bar = plt.bar(X1,Y1)
age_bar[0].set_color('orange')
age_bar[1].set_color('orange')
plt.show()


X2 = korean_age_sorted.index
Y2 = korean_age_sorted.values

plt.subplot(111)
plt.title('Korean Age Distribution')
age_kor_bar = plt.bar(X2,Y2)
age_kor_bar[0].set_color('lightgreen')
age_kor_bar[1].set_color('lightgreen')
plt.show()

> **KOREAN GENDER DISTRIBUTION**

In [ ]:
df_korea_gender = df_korea.iloc[0:,1]
korean_gender_sorted = df_korea_gender.value_counts()

X = ['Man','Woman']
Y = [korean_gender_sorted.values[0],korean_gender_sorted[1]]

title = 'Korean Gender Distribution'

plt.title(title)
plt.bar(X,Y, color=['lightblue','#D247B7'])
plt.show()

**Like other contries, Korean gender distribution shows similar graph with world's**

> **KOREAN CODING-EXPERIENCE DISTRIBUTION**

In [ ]:
korean_code = df_korea.iloc[0:,5]
korean_code_sorted = korean_code.value_counts()
kcs1 = korean_code_sorted.reindex(['< 1 years','1-2 years','3-5 years',
                            '5-10 years','10-20 years',
                            '20+ years','never'])
kcs1[6]=8

X = kcs1.index
Y = kcs1.values
title = 'Korean Coding/Programming Experience Distribution'

plt.title(title)
plt.bar(X,Y)
plt.xticks(fontsize=8)
plt.show()

> **KOREAN USING LIBRARY DISTRIBUTION**

In [ ]:
kor_lib = df_korea.loc[:,'Q14_Part_1':'Q14_OTHER']
lib_info = kor_lib.describe() #CHECK INFORMATION of dataframe
lib_info

In [ ]:
X = ['Matplotlib','Seaborn','Plotly / Plotly Express','Ggplot / ggplot2','Shiny','D3 js','Bokeh','Geoplotlib','Leaflet / Folium','None','Other']
Y = [99,63,22,34,8,12,2,4,1,12,2]

title = 'Library Using Distribution of Korean'

plt.xticks(ha='right',rotation =45)
plt.title(title)
lib = plt.bar(X,Y)
plt.xticks(fontsize=10)
lib[0].set_color('orange')
lib[1].set_color('orange')

plt.show()

> **MACINE LEARING USING EXPERIENCE PERIOD OF KOREAN**

In [ ]:
df_korea_ml = df_korea.loc[:,'Q15']
ml_sort = df_korea_ml.value_counts()

X = ml_sort.index
Y = ml_sort.values

plt.title('machine learning using experience period of korean')
peri = plt.bar(X,Y)
peri[0].set_color('orange')
plt.xticks(ha='right',rotation =45)
plt.show()

Like me, "Under 1 year" users were the most.

> **ML FRAMEWORKS USING OF HIGH FREQUENCY OF KOREAN**

In [ ]:
df_korea_mllib = df_korea.loc[:,'Q16_Part_1':'Q16_OTHER']

sk = df_korea_mllib.count()

X = ['Scikit-learn','TensorFlow','Keras','PyTorch','Fast.ai',
     'MXNet','Xgboost','LightGBM','CatBoost','Prophet','H2O 3','Caret',
     'Tidymodels','JAX','None','Other']
     #I did it one-by-one... 
Y = sk.values

plt.title('ML Frameworks Using of High Frequency')
plt.xticks(ha='right',rotation =45)
plt.bar(X,Y)
plt.show()

> **ML ALGORITHMS USING OF HIGH FREQUENCY OF KOREAN**

In [ ]:
ml_al = df_korea.loc[:,'Q17_Part_1':'Q17_OTHER']
Y = ml_al.describe().iloc[0,:].values
X = ml_al.describe().iloc[2,:].values 

plt.title('ML Algorithms Using of High Frequency')
plt.xticks(ha='right',rotation =45)
bar = plt.bar(X,Y)
plt.show()

> **EMPLOYEES DISTRIBUTION AND ROLE ANALIYSIS OF KOREAN**

In [ ]:
employees = df_korea.loc[:,'Q20']
kor_em_not = employees.fillna('NAN')
kor_em_sorted = kor_em_not.value_counts()
kor_em_sorted


X1 = ['0-49','50-249','250-999','1000-9,999','10,000 or more']
Y1 = [45, 14, 14, 11, 7] 

plt.subplot(211)
plt.title('[KOR]employees of your company')
plt.xticks(ha='right',rotation =45)
plt.bar(X1,Y1)
plt.show()


role = df_korea.loc[:,'Q5']
X2 = role.value_counts().index
Y2 = role.value_counts().values

plt.subplot(211)
plt.title('[KOR]role of your company')
plt.xticks(ha='right',rotation =45)
plt.bar(X2,Y2)
plt.show()

> **COMPENSATION**

In [ ]:
df_korea_sal = df_korea.loc[:,'Q24']
sal_sort = df_korea_sal.value_counts()


X = ['$0-999','1,000-1,999','2,000-2,999','3,000-3,999','4,000-4,999','5,000-7,499','7,500-9,999',
     '10,000-14,999','15,000-19,999','25,000-29,999','30,000-39,999','40,000-49,999','50,000-59,999',
     '60,000-69,999','70,000-79,999','80,000-89,999','100,000-124,999','300,000-500,000','> $500,000']
Y = df_korea['Q24'].value_counts()[X]



plt.title('Salary Distribution of Korean')
plt.xticks(ha='right',rotation =45)
plt.bar(X,Y)
plt.show()

**From here, I wonder if that there is some difference bwteewn "BIG COMPANY" and "SMALL COMPANY". 
So... I decided to compare them by pivot_table**

> **SALARY BY ENTERPRISE SIZE**

In [ ]:
#Check the pivot_table
df_uni = df_korea[['Q20','Q24']]
a = pd.pivot_table(df_uni, index=['Q20'], columns=['Q24'],aggfunc=len).fillna(0).astype(int)
a

In [ ]:
ax = sns.heatmap(a, annot=True, fmt='d',cmap='YlGnBu')
plt.title('Salary by Enterprise Size', fontsize=20)
plt.show()

**Thank you for reading my first EDA.
It is so inexperienced.. I know. But this is the only first step! 
How far I will go?**

> **THANKS!!**